FROM syndesis/godev:1.10 as builder

WORKDIR /gopath/src/github.com/syndesisio/syndesis/install/operator

COPY . .

RUN dep ensure -vendor-only -v

ENV CGO_ENABLED=0

RUN go build -o syndesis-operator ./cmd/syndesis-operator
# ================================================================================
# Final image
FROM centos:7

RUN adduser -r syndesis-operator
USER syndesis-operator

# Use that template for creating the operator
ADD syndesis-template.yml /conf/syndesis-template.yml

# Add the operator
COPY --from=builder /gopath/src/github.com/syndesisio/syndesis/install/operator/syndesis-operator /usr/local/bin/syndesis-operator

ENTRYPOINT [ "/usr/local/bin/syndesis-operator", "-template", "/conf/syndesis-template.yml" ]
