// This assembly is included in the following assemblies:
// Upstream: connecting/master.adoc  
// Downstream: connecting-fuse-online-to-applications-and-services/master.adoc

[id='connecting-to-fhir_{context}']
= Connecting to FHIR
:context: fhir

Fast Healthcare Interoperability Resources (FHIR) is a standard
for exchanging healthcare data. In an integration, you can 
obtain one or more FHIR resources, create or update a 
resource, update one or more fields in a resource, or use a
transaction to create multiple resources. To do this, add a FHIR 
connection to the middle of a flow or as a simple integration's
finish connection. 

{prodname} connections to FHIR:

* Can communicate with FHIR servers that use basic or bearer token (OAuth) authentication.
* Can operate on all FHIR resources that comply with FHIR DSTU3. 
* Cannot operate on extensions, which allow for storing custom data in a resource. 
If an extension is in data that is received from a FHIR server, the integration
silently ignores it. 

In an integration that connects to FHIR, in a data mapper step, you can map only 
one level of depth for a FHIR list field. In other words, if a FHIR list contains 
a list then you cannot map the fields in the nested list. To mitigate 
this limitation, {prodname} converts some FHIR resource 
list fields to single-value fields, for example, an address that is in 
a list field might be displayed in the data mapper as a single field. 

Details for connecting to FHIR are in the following topics:

* xref:creating-fhir-connections_{context}[]
* xref:adding-fhir-connection-read_{context}[]
* xref:adding-fhir-connection-search_{context}[]
* xref:adding-fhir-connection-create_{context}[]
* xref:adding-fhir-connection-update_{context}[]
* xref:adding-fhir-connection-patch_{context}[]
* xref:adding-fhir-connection-transaction_{context}[]
* xref:adding-fhir-connection-delete_{context}[]

include::../../modules/connecting/p_creating-fhir-connections.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-read.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-search.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-create.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-update.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-patch.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-transaction.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-fhir-connection-delete.adoc[leveloffset=+1]

:context: connectors
