// This assembly is included in the following assemblies:
// Upstream: connecting/master.adoc  
// Downstream: connecting-fuse-online-to-applications-and-services/master.adoc

[id='connecting-to-amqp_{context}']
= Connecting to AMQP
:context: amqp

In an integration, you can obtain messages from or publish messages
to an Advanced Message Queue Protocol (AMQP) broker. AMQP defines communication 
between clients and message brokers. To communicate with the following 
broker types, use the AMQP connector to create a connection to the
broker of interest:

* Apache ActiveMQ broker that supports AMQP
* Apache ActiveMQ Artemis 
* AMQ 7 broker
* EnMasse, which is an open source messaging platform

To communicate with one of the following broker types, 
link:{LinkFuseOnlineConnectorGuide}#connecting-to-amq_amq[use the Red Hat AMQ connector] 
to create a connection to the broker of interest:

* Apache ActiveMQ broker that does not support AMQP
* AMQ 6 broker

[NOTE]
It is possible to use the AMQP connector to create a connection to an
Apache ActiveMQ broker that does not support AMQP or to an AMQ 6 broker.
Doing this requires transport configuration in the broker. 
For information about configuring the broker, see 
https://access.redhat.com/documentation/en-us/red_hat_jboss_a-mq/6.3/html/managing_and_monitoring_a_broker/fmqadmintransportconnectors[Red Hat JBoss A-MQ Managing and Monitoring Brokers, Adding Client Connection Points].
For information about the configuration values to specify, see 
https://access.redhat.com/documentation/en-us/red_hat_jboss_a-mq/6.3/html-single/connection_reference/index#AMQP[Red Hat JBoss A-MQ Connection Reference, Advanced Message Queuing Protocol (AMQP)]. 

To use the AMQP connector, see:

* xref:create-amqp-connection_{context}[] 
* xref:adding-amqp-connection-start_{context}[]
* xref:adding-amqp-connection-middle_{context}[]

include::../../modules/connecting/p_create-amqp-connection.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-amqp-connection-start.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-amqp-connection-middle.adoc[leveloffset=+1]

:context: connectors
