// This assembly is included in the following assemblies:
// Upstream: connecting/master.adoc  
// Downstream: connecting-fuse-online-to-applications-and-services/master.adoc

[id='connecting-to-irc_{context}']
= Connecting to IRC
:context: irc_

Internet Relay Chat (IRC) is a protocol that lets anyone with 
an IRC client send and receive text messages in real time. In an integration, 
a connection to IRC can do one of the following:

* Trigger execution of a simple integration when an IRC nickname that you specify
receives a private message. The integration passes the message to the next
step in the flow. For example, you can designate an IRC nickname for 
receiving names of possible customers. Upon receiving a message, the 
integration could connect to Salesforce to create a lead. 

* Deliver a message to a particular channel. The message is from the nickname that you
specify. For example, this 
is useful when an integration downloads a file from an FTP server and 
processes it in some way. An integration flow can send a message 
to a particular channel to indicate that the process was successful.

To connect to IRC in an integration, create an IRC 
connection and then add the connection to an integration flow. 
Details are in the following topics:

* xref:creating-irc-connections_{context}[]
* xref:adding-irc-connections-receive_{context}[]
* xref:adding-irc-connections-send_{context}[]

include::../../modules/connecting/p_creating-irc-connections.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-irc-connection-receive.adoc[leveloffset=+1]

include::../../modules/connecting/p_adding-irc-connection-send.adoc[leveloffset=+1]

:context: connectors
