// This assembly is included in the following assemblies:
// Upstream: connecting/master.adoc  
// Downstream: connecting-fuse-online-to-applications-and-services/master.adoc

[id='connecting-to-knative-resources_{context}']
= Connecting to Knative resources
:context: knative

You can create a simple integration that does any of the following: 

* Connects to a Knative channel to obtain or send messages
* Exposes the integration as a Knative service
* Calls a Knative service

ifeval::["{location}" == "downstream"]
[IMPORTANT]
====
Connecting to Knative resources is a Technology Preview feature only. Technology Preview features are 
not supported with Red Hat production service level agreements (SLAs) and might not be 
functionally complete. Red Hat does not recommend using them in production. 
These features provide early access to upcoming product features, enabling 
customers to test functionality and provide feedback during the development process. 
For more information about the support scope of Red Hat Technology Preview features, 
see link:https://access.redhat.com/support/offerings/techpreview/[]. 
====
endif::[]

The exchanged messages can be of any format, however, messages are 
typically in JSON format. 

For example, a simple integration might periodically poll Salesforce 
for new leads. When a Salesforce connection finds a new lead it can 
send a message that contains the details to a Knative channel. 
Multiple simple integrations can obtain messages from that same 
Knative channel. Each integration can perform different actions on 
the lead data. 

See the following topics for details: 

* xref:enabling-connections-to-knative-resources_{context}[]
* xref:subscribing-to-a-knative-channel-to-obtain-messages_{context}[]
* xref:sending-messages-to-a-knative-channel_{context}[]
* xref:exposing-a-simple-integration-as-a-knative-service_{context}[]
* xref:calling-a-knative-service-from-a-simple-integration_{context}[]

include::../../modules/connecting/proc-enabling-connections-to-knative-resources.adoc[leveloffset=+1]

include::../../modules/connecting/proc-subscribing-to-a-knative-channel-to-obtain-messages.adoc[leveloffset=+1]

include::../../modules/connecting/proc-sending-messages-to-a-knative-channel.adoc[leveloffset=+1]

include::../../modules/connecting/proc-exposing-a-simple-integration-as-a-knative-service.adoc[leveloffset=+1]

include::../../modules/connecting/proc-calling-a-knative-service-from-a-simple-integration.adoc[leveloffset=+1]


:context: connectors
