// Module included in the following assemblies:
// Upstream:
// tutorials/topics/t2sf_intro.adoc
// connecting/topics/connecting_to_twitter.adoc
// Downstream:
// fuse-online-sample-integration-tutorials/topics/t2sf_intro.adoc
// connecting-fuse-online-to-applications-and-services/topics/connecting_to_twitter.adoc


[id='create-twitter-connection_{context}']
= Create a Twitter connection

To create an integration that obtains data from Twitter, you 
must first create a Twitter connection.  
After you create a Twitter connection, you can use it in any number of  
integrations.

.Prerequisites
* You are logged in to {prodname}. The URL for accessing {prodname} is in the 
email message that welcomed you to the Red Hat Fuse Online Evaluation program. 
* {prodname} is open in a web browser. 
* You registered your {prodname} environment as an application
that can access Twitter.

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. A connector is a template that
you use to create one or more connections.
. Click the *Twitter* connector.
. Click *Connect Twitter* to display a Twitter authorization page.
You might need to log in to Twitter before you see the authorization page.
. Click *Authorize app* to return to {prodname}.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Twitter Connect 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Twitter connection
that uses my Twitter login credentials.*`
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *Twitter Connect 1* appears as a connection that you can 
choose to add to an integration.
