[id='register-with-twitter']
= Register {prodname} as a Twitter client

You must register your installation of {prodname} as an application
that can access Twitter.
This lets you create any number of integrations that connect
to Twitter. In other words, you need to register a particular
installation of {prodname} with Twitter only once.

In each {prodname} environment, there can be only one registration
of {prodname} as a Twitter client. Each Twitter connection uses the
same Twitter credentials. In other words, you cannot log into one Twitter
account, register {prodname} as a client that uses those credentials, and then
log into a second Twitter account to also register {prodname} as a client
that uses the credentials for the second Twitter account. 

Perform these steps:

. In {prodname}:
.. In the left panel, click *Settings*.
.. Near the top of the *OAuth Application Management* page, where you see
`*During registration, enter this callback URL:*`, copy the URL 
at the end of the sentence to the clipboard.
.. To the right of the *Twitter* entry,
click *Register* to display the *Client ID* and *Client Secret* fields.
. In another browser tab, go to the Twitter *Application Management* web
site at 
https://apps.twitter.com 
and do the following: 

.. Confirm that the URL is `apps.twitter.com` and not just `twitter.com`. 
.. If you are not already logged in to the Twitter *Application
Management* site, log in.
.. Click *Create New App*.
.. In the *Name* field, enter a name for your new app. This name
must be unique among all names of apps registered with Twitter.
.. In the *Description* field, enter helpful information.
Twitter requires some input in this field.
.. In the *Website* field, paste the URL that you copied at the beginning
of this procedure and remove `api/v1/credentials/callback` from the end
of the URL.
.. In the *Callback URL* field, paste the URL again. It should be
something like this:
`\https://app-proj9128.7b63.{prodnameinurl}.openshiftapps.com/api/v1/credentials/callback`.
.. Click *Yes* to agree to the Twitter developer agreement.
.. Click *Create your Twitter application*.
.. Click the *Keys and Access Tokens* tab.
.. Copy the *Consumer Key*.
. On your {prodname} installation *Settings* page, paste the Twitter
consumer key into the Twitter *Client ID* field.
. On the Twitter *Keys and Access Tokens* tab, copy the
*Consumer Secret* and paste it into the {prodname} Twitter
*Client Secret* field.
. Click *Save* and then click *Ok*.
