exclude: ui/\.yarn/releases/.*
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks.git
  sha: v1.2.3
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: git://github.com/dnephin/pre-commit-golang.git
  sha: v0.3.2
  hooks:
    - id: go-fmt
- repo: local
  hooks:
  - id: validate-generated-templates
    name: Validate generated templates
    entry: ./install/support/validate-generated-templates.sh
    language: script
    files: ^install/generator/.+\.mustache$
  - id: commit-msg-check
    name: Check commit message
    entry: node_modules/.bin/commitlint --edit
    language: node
    stages: [commit-msg]
  - id: format-license
    name: Format license
    entry: tools/misc/format-license.sh
    language: script
  - id: go-dep-check
    name: Run dep check to see if Gopkg.lock is up to date
    entry: ./install/operator/check-dep.sh
    language: script
    files: ^install/operator/Gopkg\..*
