// This module is included in the following assemblies:
// as_connecting-to-mqtt.adoc

[id='adding-mqtt-connection-finish-middle_{context}']
= Publishing a message to an MQTT broker

In an integration, you can publish a message to an MQTT broker 
in the middle of a flow or to finish a simple integration. 
To do this, add an MQTT connection to the middle of a flow or
as the integration's finish connection.  

.Prerequisites
* You created an MQTT connection.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose a finish connection.  

.Procedure

. On the *Add to Integration* page, click the plus sign where you 
want to add an MQTT connection. Skip this step if you are adding 
a simple integration's finish connection. 
. Click the MQTT connection that you want to use
to publish a message. 

. On the *Choose an action* page, select *Publish*. 
. In the *MQTT queue/topic name* field, specify the name of the queue or
topic to publish the message to. 
. Click *Next* to specify the action's input type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next*. 

.Result
The connection appears in the integration visualization
where you added it. 
