// This module is included in the following assemblies:
// as_connecting-to-irc.adoc

[id='adding-irc-connections-send_{context}']
= Adding an IRC connection to send a message 

In an integration, you can send a message to one or more IRC channels 
in the middle of a flow or to finish a simple integration. To do this, add 
an IRC connection to the middle of a flow or as a simple integration's 
finish connection.   

.Prerequisites
* You created an IRC connection. 
* You have an IRC nickname for receiving and sending messages. 
* You are creating or editing a flow and {prodname} is prompting you to 
add to the integration. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click the IRC connection that you want to add to the flow. 
. Select *IRC Send Message to Channel* to send a message to one or 
more channels. 
* In the *Channels* field, enter one or more IRC channels delimited
by commas. During execution, this connection sends messages from the 
IRC nickname that you specify to these channels.  
. In the *Nickname* field, specify the IRC nickname that sends 
messages to the specified channels. 
. In the *NickServ password* field, if the nickname that you specified 
has a password, specify it here. 
. Click *Next* to specify the action's input type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next* to add the connection to the flow. 

.Results
The connection appears in the flow visualization where you added it. 
