// This module is included in the following assemblies:
// as_connecting-to-odata.adoc

[id='adding-mongodb-connections-read_{context}']
= Triggering an integration when a MongoDB database is updated

To trigger execution of an integration upon obtaining an update from a 
MongoDB database, add a MongoDB connection to a simple integration as its start 
connection. When the integration is running, the MongoDB connection
monitors the database collection that you specified when you created the 
integration. The monitored collection must be a MongoDB capped collection. 
Insertion of a new document
into the collection that the connection is configured to monitor, 
triggers execution of the integration. The MongoDB connection 
returns the collection update to the integration and this data is available
to the next step in the integration. 

.Prerequisites
* You created a MongoDB connection. 
* You know the name of the MongoDB capped collection
that you want the connection to read.
* You know the name of the MongoDB collection field that tracks incoming documents. 
* You know whether persistent tracking is enabled for the database that
you want the connection to read from. 
* You know how to specify tail tracking information related to the data 
that you want the connection to read. MongoDB connections can use tail
tracking information to resume an action after an unexpected connection 
termination. Tail tracking ensures that when the connection resumes its
activity, it does not return duplicate data to the integration nor does it
drop any data that needs to be returned to the integration. 

.Procedure

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a connection* page, click the MongoDB connection that
is configured to access the database that you want the integration 
to obtain updates from. 
. On the *Choose an action* page, select the *Mongo consumer* action.
. Configure the action: 
.. In the *Collection name* field, enter the name of the MongoDB 
collection that you want the connection to read. 
.. In the *Collection field used to track incoming documents* field, 
enter the name of the relevant MongoDB collection field.
This field contains data that can be sorted, such as a date or an ID. 
.. Select the *Persistent tracking enabled* checkbox if persistent 
tracking is enabled for the database that you want the connection 
to read. 
.. In the *Field used to store the tracking progress* field, optionally
specify the name of a field that is in the specified collection.
A MongoDB administrator must have configured this field to track ... ?
.. In the *DB used to store tail tracking* field, optionally enter 
the name of the MongoDB database that contains tail tracking information. 
.. In the *Collection used to store tail tracking* field, optionally enter
the name of the collection that contains tail tracking information. 
.. In the *Field used to store tail tracking* field, optionally, enter the name of 
the field that stores tail tracking information for the collection that this
connection is reading.  

+
[NOTE]
To identify the tail tracking field, you can specify the tail tracking database
or tail tracking collection. With one of these pieces of information, the connection can
find the tail tracking field. 

. Click *Next*. 

.Result
The integration now has a start connection and {prodname} is prompting
you to choose the finish connection. 

During execution, the connection returns the inserted document in 
JSON format. 
