// This module is included in the following assemblies:
// as_connecting-to-box.adoc

[id='adding-box-connection-finish_{context}']
= Uploading files to Box to finish an integration

To finish an integration by uploading files to Box,
add a Box connection as the integration's finish connection.

.Prerequisites
* You created a Box connection. 
* You are creating or editing a simple integration and {prodname} is prompting
you to choose the finish connection. 

.Procedure

. On the *Choose a connection* page, click the Box connection that
you want to use to finish the integration. 
. On the *Choose an action* page, select the *Upload* 
action to upload a file to the
Box account that this connection accesses. 
. In the *Parent folder ID* field, enter the ID of the Box folder to 
upload the file to. 
+
Box folder IDs are at the end of the URL when you select a folder in Box.
In this example: `\https://app.box.com/folder/89490291417`, the folder 
ID is `89490291417`. In this release, you can upload only a single file. 
. Optional. In the *File name* field, enter the name for a new file or 
an existing file. If you specify the name of a file that is already
in the specified Box folder, the connection appends content to that file.
+
The input to the connection must be a file that you want to upload 
to Box. If you do not specify a file name, the connection uploads a file 
that has the same name as the input file to the connection. 

. Click *Next*.  

. In the *Select Type* field, 
accept *Type specification not required* 
and click *Next*. 

.Result
The connection appears at the end of the integration visualization. 
