// This module is included in the following assemblies:
// as_connecting-to-amq.adoc

[id='adding-amq-connection-finish_{context}']
= Publishing AMQ messages to finish an integration

To finish a simple integration by publishing messages to a Red Hat AMQ broker, 
add a Red Hat AMQ connection as the simple integration's finish connection.

.Prerequisites
* You created a connection to the Red Hat AMQ broker that you want to publish 
messages to.
* You are creating an integration and {prodname} is prompting you
to choose the 
finish connection, or you are editing an integration to change the finish
connection. 

.Procedure

. On the *Choose a connection* page, click the Red Hat AMQ connection that
you want to use to finish the integration. 
. On the *Choose an action* page, select the *Publish messages* action to
publish messages to the queue or topic that you specify. 
. In the *Destination name* field, enter the name of the queue or 
topic to send messages to. 
. For the *Destination type*, accept *Queue* or select *Topic*. 
. Select *Persistent* to guarantee message delivery even if
a connection fails. 

. Click *Next* to specify the action's input/output type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and 
select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next*. 

.Result
The connection appears at the end of the integration visualization. 
