// This module is included in the following assemblies:
// as_connecting-to-box.adoc

[id='adding-box-connection-middle_{context}']
= Downloading or uploading a Box file in the middle of an integration

To download a file from Box, or upload a file to Box in the middle of a flow,
add a Box connection to the middle of the flow. 

.Prerequisites
* You created a Box connection.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration.

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection.
. Click the Box connection that you 
want the integration to use. 

. On the *Choose an action* page, select one of the following:

* *Download* to obtain a file from the Box account that this connection accesses.
* *Upload* to upload a file to the Box account that this connection accesses. 

. Configure the action you selected. 
+
To *download* a file: 

.. In the *File encoding* field, accept `UTF-8` or specify the encoding for 
the file that you want the connection to obtain. 
.. Optional. In the *File ID* field, specify the Box ID for the file that you want 
to obtain. The file ID is at the end of the URL when you are viewing the 
file in Box. For example, in this URL: `\https://app.box.com/file/537364588548`, 
the file ID is `537364588548`.
+
Alternatively, you can add a data mapper step before this connection 
and map the file ID from a previous step to this connection. 
+
In this release, you can download only a single file. 
However, mapping the file ID from a previous step can make identification of 
the file dynamic, for example, the ID can come from a database table. 
This means each execution might download a different file. 

+
To *upload* a file: 

.. In the *Parent folder ID* field, enter the ID of the Box folder to 
upload the file to. 
+
Box folder IDs are at the end of the URL when you view the content of a folder in Box.
In this example: `\https://app.box.com/folder/89490291417`, the folder 
ID is `89490291417`. In this release, you can upload only a single file. 
.. Optional. In the *File name* field, enter the name for a new file.
If you specify the name of a file that is already
in the specified Box folder, it is a runtime error.
+
The input to the connection must be a file that you want to upload 
to Box. If you do not specify a file name, the connection uploads a file 
that has the same name as the input file to the connection as long as a 
file with that name is not already present. 
.. Click *Next* to specify the upload action's input type. 
.. In the *Select Type* field, 
accept *Type specification not required* 
and click *Next*.

.Result
The connection appears in the integration flow 
where you added it. 
