// This module is included in the following assemblies:
// as_connecting-to-amazon-dynamodb.adoc

[id='adding-dynamodb-connection-put_{context}']
= Adding or updating data in an Amazon DynamoDB table

In the middle of a flow, or to finish a simple integration, a
DynamoDB connection can add an element to a DynamoDB table or update
an element in a DynamoDB table. To do this, add a DynamoDB connection
to the middle of a flow or as a simple integration's finish connection. 

.Prerequisites
* You created an Amazon DynamoDB connection.
* You are creating or editing a simple integration and {prodname} is prompting you
to add to the integration or to choose the finish connection.  

.Procedure

. On the *Choose a connection* page, click the Amazon DynamoDB connection that
is configured to access the table that you want to add to or update. 

. On the *Choose an action* page, select *Put Item*. 

. In the *JSON definition of the element* field, enter JSON notation 
that defines the table element to be added or updated. You must specify 
the element key. Input parameter placeholders prefixed 
with `:#` are allowed. If you are adding a new element, be sure to specify 
all attributes/values that you want to store.
In the following example, `userID` is the key: 
+
----
{"userID":"aslan","attr1":"some-value","attr2":"another-value"}
----

. Click *Next*. 

.Result
The connection appears in the integration visualization at the location
you added it. During execution, the connection adds or updates the defined JSON
element in the DynamoDB table that the connection is configured to access. 

.Next step
If you specified placeholder parameters in the JSON definition of the element, add a data 
mapper step before this connection. In the data mapper step, map source fields 
to the target placeholder fields in the DynamoDB connection. 
