// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc

[id='calling-a-knative-service-from-a-simple-integration_{context}']
= Calling a Knative service from a simple integration

In a simple integration, a Knative connection can call a Knative service 
in the middle of the integration or to finish the integration.  
To do this, add a Knative connection to the middle of a flow or as 
a simple integration's finish connection.   

.Prerequisites

* Knative connections are enabled. 

* You know the name of the Knative service that you want the connection 
to call. The service is running in the same cluster as {prodname}. 

* You are creating or editing a flow and {prodname} is prompting you to 
add to the integration. Or, {prodname} is prompting you to choose a 
finish connection. 

.Procedure

. On the *Add to Integration* page, click the plus sign where you want 
to add the connection. Skip this step if {prodname} is prompting you 
to choose the finish connection. 

. On the *Choose a connection* page, click the Knative connection. 

. Select the *Call Service* action.

. Click in the *Service name* field to display a list of the Knative 
services that are available in the cluster that is running {prodname}. 

. Select the service that you want the integration to call. 
+
If you exposed an integration as a Knative service and that is the 
service that you want to call, the name of the service is similar, 
if not identical, to the name of the integration. 

. Click *Next* to specify the *Call Service* action’s input type. 
This is the type that the integration sends to the Knative service. 

.. In the *Select Type* field, if the data type does not need to be known, 
or if the output from the previous integration step is the expected type, 
accept *Type specification not required* and click *Next*. 
You do not need to follow this subset of instructions.
+
A structured data type is recommended. For example, if you want 
to map the connection input in a data mapper step then you must specify 
the data type. The data mapper cannot display fields for unstructured data.
+
To specify the data type, click in the *Select Type* field and select one of the following 
as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

.. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

.. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

.. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
.. Click *Next*. 

. Specify the *Call Service* action’s output type. 
+
This is the type that the Knative service returns to the integration 
when the Knative connection is a middle connection. 
+
Repeat the previous subset of instructions to specify the output type. 
Or, if the Knative service response is empty, accept *Type specification not required*.

. Click *Next* to add the connection. 

.Result
In the integration visualization, the connection appears where you added it. 

During execution, this connection calls the specified Knative service. 
The call includes the output from the previous integration step 
(the step before this Knative connection). If this Knative connection is a 
middle connection, the connection passes the service output to the next step 
in the integration. 

.Next steps
Add any other needed connections to the integration. If you specified 
input and/or output types, add data mapper steps before and/or after the 
Knative connection and map fields as needed.
