// This module is included in the following assemblies:
// as_connecting-to-kudu.adoc

[id='create-kudu-connections_{context}']
= Creating a connection to an Apache Kudu data store

In an integration, to obtain records from or insert records into
a Kudu table, create a connection to a Kudu master host
and then add that connection to an integration.

.Prerequisite

* You must know the IP address or the hostname for the Kudu master host that you want
to connect to. 
* You must know the port that Kudu is listening on. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
connectors.  
. Click the *Apache Kudu* connector.
. To configure the connection:
.. In the *Address of Kudu master host* field, enter the 
hostname or the IP address of the Kudu master host.
.. In the *Port to establish connection to* field, enter the
port that Kudu is listening on. The default is `7051`. 

. Click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, you might enter `Kudu North`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. 
. Click *Save* to see that the connection you 
created is now available. If you
entered the example name, you would 
see that *Kudu North* appears as a connection that you can 
choose to add to an integration. 
