// This module is included in the following assemblies:
// as_connecting-to-amazon-sns.adoc

[id='creating-amazon-sns-connections_{context}']
= Creating Amazon SNS connections

You must create an Amazon SNS connection before you can add an
Amazon SNS connection to an integration.

.Prerequisites

* AWS access key. See link:{LinkFuseOnlineConnectorGuide}#obtaining-aws-credentials_aws[Obtaining AWS credentials].

* You must know the region in which the SNS topic is located. 
This is the topic that you want the SNS connection that 
you are creating to send a message to.

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *Amazon SNS* connector.
. In the *Access Key* field, enter an Amazon access key ID that is 
part of a user access key in the AWS account that manages 
the topic that you want the connection to send a message to. 
+
If the topic that you want the connection to
access does not already exist then when {prodname} tries to start running the 
integration, it uses the AWS account associated with this access key to 
create the topic. However, if the topic already exists in some other 
AWS account, then the connection cannot create the topic and the 
integration cannot start. 

. In the *Secret Key* field, enter the Amazon secret access key for the 
Amazon access key ID that you specified.

. In the *Region* field, select the AWS region in which the topic resides.
If the connection creates the topic, then it creates it in the
selected region.
. Click *Validate*. {prodname} immediately tries to validate the
connection and displays a message that indicates whether or not
validation is successful. If validation fails, revise the configuration
details as needed and try again.
. When validation is successful, click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `SNS North`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample SNS connection
that sends messages to our north region topic.*`
. Click *Save* to see that the connection you
created is now available. If you entered the example name, you would
see that *SNS North* appears as a connection that you can 
choose to add to an integration.
