// This module is included in the following assemblies:
// as_connecting-to-dropbox.adoc

[id='create-dropbox-connection_{context}']
= Creating a Dropbox connection

In an integration, to download or upload Dropbox files, create a 
Dropbox connection, which you can add
to an integration. You can add the same connection to any number of
integrations. 

.Prerequisite
You registered your {prodname} environment as an application that can
access Dropbox. 

.Procedure

. In a new browser tab, go  to `https://www.dropbox.com` 
and do the following:
.. Sign in to the Dropbox account in which you created the app that
registers access from your {prodname} environment. 
.. Go to https://www.dropbox.com/developers/apps.
.. Click the {prodname} app to display its settings.

. In another browser tab, in {prodname}, do the following:
.. In the left panel, click *Connections* to
display any available connections.
.. In the upper right, click *Create Connection* to display
the available connectors. 
.. Click the *Dropbox* connector.

. Go back to the Dropbox settings display for your app and do the following:
.. Scroll down to see *Generated Access Token*. 
.. Click *Generate*. 
.. Copy the generated access token to the clipboard. 

. Back in {prodname}, in the *Configure Connection* page, in the 
*Access Token* field, paste the generated
access token. 
. In the *Client Identifier* field, enter the name that you specified
when you created the Dropbox app. 
. Click *Validate*. {prodname} displays a message that indicates whether
it can validate this connection. If validation fails, try again and 
be sure to enter the correct values. 
. When validation is successful, click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Dropbox Connect 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Dropbox connection
that can access all content in our company Dropbox account.*`
. Click *Save* to see that the connection you
created is now available. If you entered the example name, you would
see that *Dropbox Connect 1* appears as a connection that you can 
choose to add to an integration.
