// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc

[id='enabling-connections-to-knative-resources_{context}']
= Enabling connections to Knative resources

You must enable Knative connections before you can add them to simple integrations. 

.Prerequisites

* The `oc` client tool is installed in, and connected to, the OCP 
cluster in which {prodname} is running. 

* {prodname} is running on OpenShift Container Platform on-site in a 
customer-managed environment. 

* The {prodname} runtime is Camel K. 

* In the cluster in which {prodname} is installed, each Knative resource 
that you want an integration to connect to is also installed. 

* You have permission to install {prodname}. 

.Procedure

. Log in to OpenShift with an account that has permission to install {prodname}. 
For example:
+
----
$ oc login -u developer -p developer
----

. Ensure that the current project is the project in which {prodname} is running. 
To view the current project, invoke the following command:
+
----
$ oc project
----

. Edit the `syndesis` custom resource:
+
.. Invoke the following command, which typically opens the resource in an editor:
+
----
oc edit syndesis
----
.. Update the resource to specify the following:
+
----
spec:
  addons:
     camelk:
       enabled: true
     knative:
       enabled: true
----
.. Save the resource.
+
Saving this change to the `syndesis` custom resource triggers the 
`syndesis-operator`, which is responsible for installing {prodname}, 
to redeploy `syndesis-server`. 


.Result

In the {prodname} console, on the *Connections* page, a Knative connection 
is now available. You can add the same Knative connection to any number of 
simple integrations. Configuration of the connection action, 
specifies the Knative resource that the connection accesses.
