// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc
// There are cross-reference links to this module. 
// If you move this module to a new or different assembly or change the heading 
// in this file, update the cross-reference link in these files:
// modules/fuse-online-installing/c_configuration-changes-allowed-after-installation.adoc

[id='enabling-connections-to-knative-resources_{context}']
= Enabling connections to Knative resources

You must enable Knative connections before you can add them to 
simple integrations. 

Knative connections might have been enabled when {prodname} was 
installed. To check this, view the content of the `syndesis` custom resource.
If the `camelk` and `knative` add-ons specify `enabled: true` then Knative
connections are already enabled. 

.Prerequisites

* The `oc` client tool is installed in, and connected to, the OCP 
cluster in which {prodname} is running. 

* {prodname} is running on OpenShift Container Platform on-site in a 
customer-managed environment. 

* The {prodname} runtime is Camel K. 

* In the cluster in which {prodname} is installed, each Knative resource 
that you want an integration to connect to is also installed. 
Before you can install Knative resources, you must install the 
link:https://docs.openshift.com/container-platform/4.3/serverless/installing-openshift-serverless.html[OpenShift Serverless Operator]  
and the 
link:https://openshift-knative.github.io/docs/docs/proc_knative-eventing.html[Knative Eventing Operator]. 

* You have permission to install {prodname}. 

.Procedure

. Log in to OpenShift with an account that has permission to install {prodname}. 
For example:
+
----
$ oc login -u developer -p developer
----

. Switch to the project in which {prodname} is running, for example: 
+
----
$ oc project my-integration-project
----

. Edit the `syndesis` custom resource:
+
.. Invoke the following command, which typically opens the resource in an editor:
+
----
oc edit syndesis
----
.. Update the resource to specify the following:
+
----
spec:
  addons:
     camelk:
       enabled: true
     knative:
       enabled: true
----
.. Save the resource.
+
Saving this change to the `syndesis` custom resource triggers 
`syndesis-operator`, which is responsible for installing {prodname}, 
to redeploy `syndesis-server`. 
+
If `camelk` and `knative` are already enabled, you can close the file.
Connections to Knative resources are enabled. 


.Result

In the {prodname} console, on the *Connections* page, a Knative connection 
is now available. You can add the same Knative connection to any number of 
simple integrations. Configuration of the connection action, 
specifies the Knative resource that the connection accesses.
