// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc

[id='enabling-connections-to-knative-resources_{context}']
= Enabling connections to Knative resources

You must enable Knative connections before you can add them to simple integrations. 

.Prerequisites

* The `oc` client tool is installed in, and connected to, the OCP 
cluster in which {prodname} is running. 

* {prodname} is running on OpenShift Container Platform on-site in a 
customer-managed environment. 

* The {prodname} runtime is Camel K. 

* In the cluster in which {prodname} is installed, each Knative resource 
that you want an integration to connect to is also installed. 

* You have permission to install {prodname}. 

.Procedure

. Scale the {prodname} server to 0 by invoking the following command: 
+
----
oc scale dc/syndesis-operator --replicas 0
----

. Edit the `syndesis-server` *ConfigMap* file to set 
`features.knative.enabled` to `true`. To use the `oc` CLI, 
invoke `oc edit cm syndesis-server`.  

. Edit the Camel K *IntegrationPlatform* resource to set `spec.profile` to `Knative`. 
To use the `oc` CLI, invoke `oc edit integrationplatform`. 

. Restart the {prodname} server (`syndesis-server`) resource, by 
invoking the following command: 
+
----
oc delete pod -l syndesis.io/component=syndesis-server
----

.Result

In the {prodname} console, on the *Connections* page, a Knative connection 
is now available. You can add the same Knative connection to any number of 
simple integrations. Configuration of the connection action, 
specifies the Knative resource that the connection accesses.
