// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc

[id='exposing-a-simple-integration-as-a-knative-service_{context}']
= Exposing a simple integration as a Knative service

In a simple integration, the start connection can be a Knative connection 
that exposes the integration as a Knative service. An integration that 
starts this way automatically scales down to 0 pods when there have 
been no calls to the service for a specified number of minutes. 
The default is 1 minute. 

This automatic scaling saves resources, which is an advantage over simple 
integrations that start with other kinds of connections, such as a 
connection to an AMQ broker. 

.Prerequisites

* Connections to Knative resources are enabled. 

* Knative is installed in the same cluster that {prodname} is running in. 

.Procedure

. In {prodname}, in the left panel, click *Integrations*. 

. Click *Create Integration*. 

. On the *Choose a connection* page, click the Knative connection. 

. Select the *Expose as Service* action. 

.Result
{prodname} prompts you to add the simple integration’s finish connection. 

When {prodname} publishes the integration, the Camel K runtime creates a 
Knative `serving.knative.dev` service. This service: 

* Is an alternative to a Kubernetes deployment object
* Can automatically scale to 0 after a period of no activity
* Should not be confused with the Kubernetes Service 

Publication makes the integration available to be called at the root 
path ( / ). Clients can invoke execution of the integration by calling it 
as an HTTP endpoint and passing data as needed. Typically, the passed 
data is in JSON format. 

In this release, it is expected that the primary use for exposing an 
integration as a Knative service is that other {prodname} integrations 
call that service. In this scenario, the integration that calls the 
service selects the service name and does not need to specify a path. 
