// This module is included in the following assemblies:
// as_connecting-to-email-servers.adoc

[id='obtaining-email-to-trigger-integration-execution_{context}']
= Obtaining email to trigger integration execution

To trigger execution of an integration upon receiving email,
add a an IMAP or POP3 email server connection 
as a simple integration's start connection.

.Prerequisites
* You created an IMAP or POP3 email server connection that is configured to access 
the account that you want to obtain email from. 
* You know the name of the folder to retrieve messages from. 

.Procedure

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a connection* page, click the email server connection that
you want to use to start the integration.
. On the *Choose an action* page, select *Receive Email* 
to periodically retrieve messages from an email account. 
. Configure the action:
.. Leave the *Folder* field blank to obtain email from the inbox. Or, 
to obtain messages from a particular folder, enter the name of that folder.
+
If this connection accesses a POP3 email server, only standard folders,  
such as *Inbox* or *Sent* are supported. 
.. Select the *Unseen Only* checkbox to obtain only new messages, which 
arrived since the previous poll. When this checkbox is not selected, each 
poll returns all messsages that are in the specified folder. 
.. In the *Delay* field, accept the default of 5 seconds as the time
that elapses between polls for messages. Or, to specify a different polling interval,
enter a number and select its time unit. 
.. In the *Maximum Emails* field, enter the largest number 
of messages that one poll operation can obtain. The default is 5.
+
To always obtain all new messages or all messages in the specified folder, 
set *Maximum Emails* to *`-1`*.
. Click *Next*. 

.Result

The connection appears at the beginning of the integration flow. 
