// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc

[id='sending-messages-to-a-knative-channel_{context}']
= Sending messages to a Knative channel

In a simple integration, a Knative connection can send a message to a 
Knative channel in the middle of a flow or to finish a simple integration. 
To do this, add a Knative connection to the middle of a flow or as a 
simple integration's finish connection.   

.Prerequisites

* Knative connections are enabled. 

* The Knative resource that you want to send messages to is installed 
in the same cluster as {prodname}. 

* You know the name of the Knative channel that you want the connection 
to send messages to. 

* You are creating or editing a flow and {prodname} is prompting you to 
add to the integration. Or, {prodname} is prompting you to choose a 
finish connection. 

.Procedure

. On the *Add to Integration* page, click the plus sign where you want 
to add the connection. Skip this step if {prodname} is prompting you to 
choose the finish connection. 

. On the *Choose a connection* page, click the Knative connection. 

. Select the *Send to Channel* action.

. Click in the *Channel name* field to display a list of the Knative 
channels that are available in the cluster that is running {prodname}. 

. Select the channel that you want the integration to send messages to.

. Click *Next* to specify the *Send to Channel* action’s input type. 
This is the type that the integration sends to the Knative channel. 

.. In the *Select Type* field, if the data type does not need to be known, 
or if the output from the previous integration step is the expected type, 
accept *Type specification not required* and click *Next*. 
You do not need to follow the rest of these instructions.
+
However, a structured data type is recommended. For example, if you want 
to map the connection input in a data mapper step then you must specify 
the data type. The data mapper cannot display fields for unstructured data.
+
To specify the data type, click in the *Select Type* field and select one of the following 
as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

.. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

.. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

.. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
.. Click *Next*. 

.Result
In the integration visualization, the connection appears where you added it. 
During execution, this connection sends a message to the selected Knative channel. 

.Next steps
Add all needed connections to the integration. Then add a data mapper 
step just before the Knative connection that sends messages to a Knative channel. 
Map a source field to the Knative connection target `message` field.
