// This module is included in the following assemblies:
// as_connecting-to-email-servers.adoc

[id='sending-email-from-an-integration_{context}']
= Sending email from an integration

In the middle of a flow, or to finish a simple integration, 
you can add an email server connection that sends messages. 

.Prerequisites
* You created an SMTP email server connection that is configured to access 
the account that you want to send messages from. 
* {prodname} is prompting you to add to the integration, or to choose the finish 
connection for a simple integration. 

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click the email server connection that you want to use to send messages. 
. Select the *Send Email* action.

. On the configuration page for *Send Email*, do one of the following:
+
* Leave all fields blank if you plan to add a data mapper step
just before this connection and you plan to map integration data 
to the *Send Email* fields.

* Enter information in one or more of the following *Send Email* fields. 
Separate multiple email addresses with a comma. 

.. *Email to*
.. *Email from*
.. *Email subject* 
.. *Email text*
.. *Email cc*
.. *Email bcc* 

* Leave some fields blank and enter information in some fields. 
+
If you plan to add a data mapper step just before this email connection,
and you want to map integration data to some email fields, leave those fields
blank in the action configuration. Enter values in other action fields as needed. 

. In the *Parameter Priority* field, accept *Input Values* or select 
*Consumed Data*. This determines which of the following has precedence: 
+
* The input values in this action configuration. 
* The data values that are available to this connection during 
integration execution. 

. Click *Next* to add the connection to the flow. 

.Result
The connection appears in the integration flow where you added it. 

.Next step
If you plan to add a data mapper step
before this connection, first add any other connections that you plan to add
to this flow. Then add the data mapper step. 
