// This module is included in the following assemblies:
// as_connecting-to-concur.adoc

[id='create-concur-connection_{context}']
= Creating a SAP Concur connection

To connect to SAP Concur in an integration, you must first create a SAP
Concur connection, which you can then add to any number of integrations. 
When you create a SAP Concur connection, you authorize the connection to access 
SAP Concur with the login credentials that you enter when you create
the connection. 

.Prerequisites
* In the {prodname} environment in which you are creating the connection,
you must have configured the SAP Concur connector.  
* You should know whether the connector is configured for access to the
SAP Concur implementation site or the SAP Concur production site. 
* You must have a user name and password for logging in to the SAP 
Concur site for which the SAP Concur connector is configured. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. A connector is a template that
you use to create one or more connections.
. Click the *SAP Concur* connector.
. In the *Configure Connection* page, click *Connect SAP Concur*, 
which takes you to the SAP Concur site for which the connector is
configured. 
+
If *Connect SAP Concur* does not appear, then the SAP Concur
connector in your {prodname} environment
is not configured.  See
link:{LinkFuseOnlineConnectorGuide}#configure-concur-connector_concur[Configuring the SAP Concur connector]. 
+
If `redirect_uri is improper or not previously registered` appears, then 
the SAP Concur connector configuration is incorrect. 
Return to the {prodname} *Settings* page
to update and validate the connector configuration.  

. On the SAP Concur OAuth site: 
.. Enter the email address for the SAP Concur account that you want
this connection to use to access SAP Concur. 
.. Ensure that *Username* is selected. 
.. Click *Continue*. 
.. Enter the SAP Concur password associated with the email address.
.. Click *Sign In*, which returns you to {prodname}. 

. In the {prodname} *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*SAP Concur Test1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample SAP Concur connection to the implementation site.*`
. Click *Save* to see that the connection you
created is now available. If you entered the example name, you would
see that *SAP Concur Test1* appears as a connection that you can 
choose to add to an integration.
