// This module is included in the following assemblies:
// as_connecting-to-kafka.adoc

[id='creating-kafka-connections_{context}']
= Creating a connection to a Kafka broker

In an integration, to subscribe for data from a Kafka topic 
or publish data to a Kafka topic, 
create a connection to Kafka and then add that connection to an 
integration.

.Prerequisites

* You enabled auto-discovery of Kafka brokers in the cluster.
Or, you know the URI for the Kafka broker that you want to connect to. 
* If you want to use Transport Layer Security (TLS) to encrypt your data, you have the Kafka broker’s PEM certificate text. Typically, you obtain the broker certificate text from your Kafka server administrator.

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. Click *Create Connection* to display
connectors.  
. Click the *Kafka* connector.
. In the *Kafka broker URIs* field, select the broker that you want 
this connection to access, or enter a comma separated list
of Kafka broker URIs. Each URI should be in the form _host:port_.
. For the *Transport Protocol* field, select one of the following options:
* If you want to encrypt your data to protect it in transit, select *TLS* (Transport Layer Security).
* If you do not want to encrypt your data, select *Plain* and then skip to Step 7.
. If you selected *TLS* in Step 5, then in the *Broker certificate* field, paste the Kafka broker’s PEM certificate text.
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the input 
parameter and try again.
. If validation is successful, click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, you might enter `Kafka West`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. 
. Click *Save* to see that the connection you 
created is now available. If you
entered the example name, you would 
see that *Kafka West* appears as a connection that you can 
choose to add to an integration. 
