// This module is included in the following assemblies:
// as_connecting-to-knative-resources.adoc

[id='subscribing-to-a-knative-channel-to-obtain-messages_{context}']
= Subscribing to a Knative channel to obtain messages

To trigger integration execution upon receiving a message from a 
Knative channel, add a Knative connection as a simple integration’s 
start connection. An integration that starts this way automatically 
scales down to 0 pods when no messages have been received from the 
channel for a specified number of minutes. The default is 1 minute. 

This automatic scaling saves resources, which is an advantage over 
simple integrations that start with other kinds of connections, 
such as a connection to an AMQ broker. 

.Prerequisites

* Connections to Knative resources are enabled. 

* The Knative resource that you want to obtain messages from is 
 in the same cluster as {prodname}

* You know the name of the Knative channel that you want the connection 
to obtain messages from. 

.Procedure

. In {prodname}, in the left panel, click *Integrations*. 

. Click *Create Integration*. 

. On the *Choose a connection* page, click the Knative connection. 

. Select the *Receive from Channel* action. 

. Click in the *Channel name* field to display a list of available Knative channels. 

. Select the Knative channel name for the resource that you want to obtain 
messages from.

. Click *Next* to specify the *Receive from Channel* action’s output type. 
This is the type that the connection passes to the next step in the integration. 

.. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* and click *Next*. You do not need to 
follow the rest of these instructions.
+
However, a structured data type is recommended. For example, if you want 
to map the connection output in a data mapper step then you must specify 
the data type. The data mapper cannot display fields for unstructured data.
+
To specify the data type, click in the *Select Type* field and select one of the following 
as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

.. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

.. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

.. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
.. Click *Next*. 

.Result
{prodname} prompts you to add the simple integration’s finish connection. 

During execution, each time the selected Knative channel receives a new message, 
the Knative connection passes the message to the next step in the integration,

.Next steps
Add all needed connections to the integration. Then add a data mapper step 
after the Knative connection that starts the integration. Map the source 
`message` field to a target field in the next connection. 
