//Assembly: assembly-connecting-to-virtual-databases.adoc

[id="previewing-a-vdb-by-submitting-queries_{context}"]
= Previewing a virtual database in {prodname} by submitting SQL test queries

Before you publish a virtual database and make it available to applications, you 
can run test queries against its views to verify that it returns the information 
that you expect.

Although the default preview shows you the first 15 results returned when a SQL 
*SELECT * FROM* statement is submitted to a virtual database view, you can use the 
embedded SQL client in {prodname} to send modified test queries to your views. 
You can adjust the default results set by specifying the row limits and row offsets.  

If the view that you query originates from a non-SQL data source, the data 
virtualization engine converts the SQL query into a format that the 
data source can interpret. 

// You can run queries against existing views in the virtual database only.    

.Prerequisites

* You have a valid virtual database that was created in {prodname}.

.Procedure
. From the navigation sidebar in {prodname}, click *Data*.
. On the *Data Virtualizations* page, click *Edit* in the entry for the virtual database 
that contains the view that you want to test.
. Click the *SQL client* tab.
. From the *View* field, select the view that you want to test.
. In the *Row limit* field, specify the number of rows to display.
. In the *Row offset* field, specify the number of rows to skip. 
. Click *Submit*. The *Query results* table displays the result set.
