// This module is included in these assemblies:
// as_connecting-to-telegram.adoc

[id='creating-telegram-connections_{context}']
= Creating a Telegram connection

In an integration, a Telegram connection can receive messages that have been 
sent to a particular chat. A chat bot that you create forwards the messages 
to {prodname}. A Telegram connection can also send messages to chats that 
the connection has access to.  
You can use the same Telegram connection:

* In any number of integrations that use the connection to send messages 
to a chat.
* In addition, you can use it in one integration that uses the connection 
to receive messages from a Telegram chat.

In other words, you cannot use the same Telegram connection in more than one 
integration if you want that connection to receive Telegram chat messages 
in both integrations. This is a Telegram limitation.


.Prerequisites

* In Telegram, you created a bot for the chat that you want to obtain
messages from and send messages to. For help with this, see
link:https://core.telegram.org/bots[Bots, an introduction for developers]. 
* You obtained a bot authorization token from the Telegram BotFather.
 
.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *Telegram* connector.
. In the *Authorization Token* field, enter the Telegram authorization token 
for the bot that you want to get messages from and send messages to. 
. Click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Telegram for Product Mentions*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection.
. Click *Save* to see the updated list of available 
connections, including the connection that you just created. 
If you entered the example name, you would
see that *Telegram for Product Mentions* appears as a connection that you can 
choose to add to an integration. You can add this connection to 
any number of integrations. 
