// This module is included in the following assemblies:
// as_connecting-to-google-calendar.adoc

[id='add-google-calendar-connection-add-event_{context}']
= Adding an event to a Google Calendar 

In an integration, you can add an event to a Google Calendar 
in the middle of a flow or to finish a simple integration.  
To do this, add a Google Calendar connection to the middle of a flow 
or as a simple integration's finish connection. 

.Prerequisites
* You created a Google Calendar connection that is 
authorized to access the Google Calendar to which you want to add an 
event.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. 
Or, {prodname} is prompting you to choose a finish connection. 

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click a Google Calendar connection that is authorized to access
the calendar that you want to add an event to. 
. On the *Choose an action* page, select the *Create Event* action.

. Configure the *Create Event* action: 
+
.. Enter a title for the new event.
.. Enter the name of the Google Calendar to add the event to. 
.. For the other input parameters, you can enter data or you 
might want to map values from an event that you obtained in 
a previous Google Calendar connection. 

. Click *Next* to add the connection to the flow. 

.Result
The connection appears in the integration flow where you added it. 

.Next step
If you want to map any values to the fields in this Google Calendar 
connection, add a data mapper step to the flow. First, add all 
needed connections to the flow. Then add a data mapper step immediately 
before this Google Calendar connection.
