// This module is included in the following assemblies:
// as_connecting-to-google-sheets.adoc

[id='add-google-sheets-connection-update-properties_{context}']
= Updating spreadsheet properties

In an integration, you can update the properties of a spreadsheet 
in the middle of a flow or to finish a simple integration.
To do this, add a Google Sheets connection to the middle of a flow
or as a simple integration's finish connection.

Properties include the spreadsheet's title, locale, and time zone. 

When {prodname} prompts you to configure the *Update spreadsheet properties* 
action, you can leave some or all fields blank. If you leave a field blank, then 
in a data mapper step that 
is in the flow (you add it later) before this connection, you map 
fields from previous steps to 
blank *Update spreadsheet properties* action configuration fields. 

.Prerequisites

* You created a Google Sheets connection that is authorized to access the 
Google spreadsheet whose properties you want to update.
* You have access to the spreadsheet ID for the spreadsheet whose properties 
you want to update.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click a Google Sheets connection that is authorized to access
the spreadsheet whose properties you want to update.
. On the *Choose an action* page, select *Update spreadsheet properties*.
. To configure the *Update spreadsheet properties* action:
+
.. In the *SpreadsheetId* field, do one of the following: 
+
* Enter the ID of the spreadsheet whose properties you want to update. 
* Leave the field blank. In this case, after you add this connection 
to the flow, you must add a data mapper step that is 
before this connection. In the data mapper step, map the spreadsheet ID from 
a previous connection to this connection. The previous connection must 
access the spreadsheet that you want to update in this connection.

.. In the other fields, enter a value only if you want to change the property. 
Alternatively, you can leave the fields blank. If you do, then in a data mapper
step that you add later, just before this connection, you can map the fields that
you want to change. 

.. Click *Next* to add the connection to the flow.
The connection appears in the integration visualization where you added it.

. If you want to add any other connections to the flow, add 
them now and then return to these instructions. 
. After the flow has all desired connections, you might want to 
use a data mapper step to update spreadsheet properties:

.. In the integration visualization, click the plus sign that is
just before the Google Sheets connection that updates properties.
.. Click *Data Mapper* to add a data mapping step to 
the flow. 

.. In the data mapper, if you did not specify a spreadsheet ID when 
you configured the *Update spreadsheet properties* action, map a 
source `spreadsheetId` to the target `spreadsheetId`.

.. For each spreadsheet property that you want to change and for which 
you did not specify an updated value when you configured the 
*Update spreadsheet properties* action, map a field from a source step 
to the target spreadsheet property that you want to change. 

.. In the upper right, click *Done* to add the data mapper step.
