// This module is included in the following assemblies:
// as_connecting-to-google-sheets.adoc

[id='add-google-sheets-connection-create-spreadsheet_{context}']
= Creating a spreadsheet

To create a new spreadsheet in the middle of a flow, 
add a Google Sheets connection between the start and finish connections. 
While you can also finish a simple integration with a Google Sheets 
connection that creates a spreadsheet, you cannot add data to a 
new spreadsheet in the same connection. Therefore, when you want to 
create a spreadsheet and add data to the spreadsheet in the same
flow, the flow requires two Google Sheets connections.
One connection creates the spreadsheet and then a subsequent connection
adds data to the spreadsheet. 

.Prerequisites
* You created a Google Sheets connection that is authorized to
access the Google account in which you want to create the 
spreadsheet. 
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click a Google Sheets connection that is authorized to access
the Google account that you want to use to create the spreadsheet.
. On the *Choose an action* page, select *Create spreadsheet*.
. To configure the *Create spreadsheet* action:
+
.. In the *Title* field, enter the title of the new spreadsheet.
.. In the *Time Zone* field, enter the time zone that the 
new spreadsheet should use, for example, `India Standard Time`, or `Tokyo`.
.. In the *Locale* field, enter the locale of the 
new spreadsheet, for example, `Canada`, or `Hong Kong`.

. Click *Next* to add the connection to the flow.
The connection appears in the integration visualization where you added it.

.Result
A connection that creates a spreadsheet returns the spreadsheet ID for 
the new spreadsheet. In subsequent steps, you can map 
this spreadsheet ID to the spreadsheet ID in a connection 
that accesses the new spreadsheet, for example, to update it. 
