// This module is included in the following assemblies:
// as_connecting-to-jira.adoc

[id='adding-jira-connection-update-issue_{context}']
= Updating an issue on a Jira server

In the middle of a flow, or to finish a simple integration, 
you can connect to a Jira server to update an issue. 
The connection can update one or more issue fields. If the issue
being updated already has a value for a field, the connection
replaces that value with any value you specify for the connection 
or that you map to a connection field. For example, if the 
issue already has a description, and you specify text in the
*Description* field when you configure the *Update Issue* action, 
the connection replaces the description that was there with this
new description. 

.Prerequisites
* You created a Jira connection.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose
a simple integration's finish connection. 

.Procedure

. On the *Add to Integration* page, click the plus sign where you 
want to add a Jira connection. Skip this step if you are adding 
a simple integration's finish connection.  
. Click the Jira connection that you want the integration to use
to connect to the Jira server. 
. On the *Choose an action* page, select *Update Issue*.
. Configure the action. The only required field is 
*Issue Key*. For the optional fields, you can enter values now, or, 
after you add this connection 
to an integration, you can add a data mapper step before this connection.
In the data mapper step, map fields from previous steps to the optional 
fields in this connection. 
.. Optionally, in the *Assignee* field, enter the Jira user name 
for the person that you want to assign this issue to. 
.. Optionally, in the *Components* field, enter the name of one or 
more components. Separate multiple names with commas. A Jira 
administrator defines the components that you can specify. 
.. In the *Issue Key* field, enter the Jira identifier for the issue
that you want the connection to update. 
Examples of issue keys: `GATE-1234`, `Ent-239`. 
.. Optionally, in the *Priority ID or name* field, enter a priority
for the new issue. A Jira administrator defines the priority values
that you can enter. 
.. Optionally, in the *Summary* field, enter a brief statement about the issue. 
.. In the *Issue type ID or name* field, enter a value that describes 
the type of the issue. For example, this is often something like `Story`, `Epic`, 
`Chore`, or `Bug`.
.. Optionally, in the *Description* field, enter any information about this
issue that it is helpful to capture. 
. Click *Next*. 

.Result
The connection appears in the integration visualization
where you added it. 
