// This module is included in the following assemblies:
// as_connecting-to-google-sheets.adoc

[id='create-google-sheets-connection_{context}']
= Creating a Google Sheets connection

When you create a Google Sheets connection, you authorize the connection to access
the Google Sheets spreadsheets that are associated with one
particular Google account, which you choose. After you create a Google Sheets connection, you can
add it to multiple integrations.

.Prerequisites
* You 
link:{LinkFuseOnlineConnectorGuide}#register-with-google_google[registered {prodname} as a Google client application] 
and enabled the Google Sheets API. 
* The {prodname} *Settings* page entry for Google Sheets has values for the client ID and client secret, which
you obtained by registering {prodname} as a Google client application. 


.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. A connector is a template that
you use to create one or more connections.
. Click the *Google Sheets* connector.
. In the *Configure Connection* page, click *Connect Google Sheets*,
which takes you to a Google sign-in page.
+
If *Connect Google Sheets* does not display, then your {prodname} environment
is not registered as a Google client application with the Google Sheets API
enabled. See
link:{LinkFuseOnlineConnectorGuide}#register-with-google_google[Registering {prodname} as a Google client application].
When your environment is not registered with
Google, then when you try to create a Google Sheets connection, {prodname} displays
multiple fields that prompt for authorization information. While you can
create a Google Sheets connection by entering values in these fields,
it is not recommended. 

. In the Google sign-in page,
select the Google account that you want this connection to
access from {prodname} and click *Next*.
. In response to the *openshiftapps.com wants to access your Google Account*
prompt, click *Allow* to return to {prodname}.
. In the {prodname} *Name* field, enter your choice of a name that
helps you distinguish this connection from other connections.
For example, enter `*Google Sheets Work Connection*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Google Sheets connection
that uses my Google work account.*`
. Click *Save* to see that the connection that you
created is now available. If you entered the example name, you would
see that *Google Sheets Work Connection* appears as a connection that you can
choose to add to an integration.
