//Assembly: assembly-connecting-to-virtual-databases.adoc

[id="creating-a-vdbs_{context}"]
= Creating a virtual database in {prodname}

In {prodname}, you can create virtual databases that import views from applications or 
services that are available from the *Connections* page.
 
For each virtual database that you create, you must import data sources, and select the 
tables from each data source that you want to include. The views in the resulting virtual database 
map directly to the database tables that you import. After the initial creation, 
you can add views to a virtual database that join data from more than one table. 

NOTE: In this release, you can create virtual databases in {prodname} only 
from relational databases, MongoDB, and Salesforce.

.Prerequisites
* Your {prodname} environment has a connection to one or more of the following data sources:
** Relational database, such as postgreSQL or MySQL.
** MongoDB database
** Salesforce database


.Procedure

. From the navigation sidebar in {prodname}, click *Data*.
. Click *Create Data Virtualization*.
. On the *Create new Data Virtualization* page, type a name for the virtual database and then click *Create*. 
+
* Provide a name that informs people about the database contents or purpose, 
and that is short enough for application developers and SQL users to easily insert 
in their code. 
* Names can include only alphanumeric ([a-z]|[A-Z], [0-9]), and hyphen (-) characters. 

. On the *Create views* page, click *Import views*.
. On the *Select connection* page, click the tile for an active data source, and then click *Next*.  
. On the *Select views* page, select one or more tables to include in your virtual database and then click *Done*. 
+
A confirmation message reports when the import completes. The *Views* tab for the 
draft virtualization lists a view for each table that you imported. 
+
You can now edit the existing views, create another view, or publish the virtual 
database to make it available for use. 
//.Next steps
//* xref:previewing-a-vdb-by-submitting-queries[]
//* xref:adding-a-view-to-a-vdb[]
//* xref:editing-the-ddl-for-a-vdb-fuse-online[]
//* xref:publishing-a-vdb-fuse-online[]
