// This module is included in the following assemblies:
// as_connecting-to-servicenow.adoc

[id='create-servicenow-connection_{context}']
= Creating a ServiceNow connection

In an integration, to connect to your company's ServiceNow instance,
you must create a ServiceNow connection.

.Prerequisites

* A ServiceNow administrator at your site must have created a 
ServiceNow account for you. 
* You must know the URL for your ServiceNow instance and 
your ServiceNow user name and password. 
* If the ServiceNow administrator also created a ServiceNow
client ID and client secret for you, you must know these values.

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *ServiceNow* connector.
. Configure this ServiceNow connection:
.. In the *Instance Name* field, enter the name of the ServiceNow instance
that you want to obtain records from or copy records to. For example,
if the URL for your ServiceNow instance is 
`\https://abc12345.service-now.com`, the instance name is `abc12345`.
.. In the *User Name* field, enter your ServiceNow user name. 
.. In the *User Password* field, enter your ServiceNow password.
.. Optionally, in the *Client ID* field, enter your client ID if you
received one from your ServiceNow administrator.
.. Optionally, in the *Client Secret* field, enter your client secret if you
received one from your ServiceNow administrator. 

.. Click *Validate*. {prodname} immediately tries to validate the
connection and displays a message that indicates whether 
validation is successful. If validation fails, update the configuration
details as needed and try again.
.. When validation is successful, click *Next*.
. In the *Name* field, enter a name that
helps you distinguish this connection from other connections.
For example, enter `*ServiceNow Con 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*ServiceNow connection that uses administrative credentials.*`
. Click *Save* to see that the connection you
created is now available. If you entered the example name, you would
see that *ServiceNow Con 1* appears as a connection that you can 
choose to add to an integration.
