// This module is included in the following assemblies:
// as_connecting-to-irc.adoc

[id='creating-irc-connections_{context}']
= Creating an IRC connection

In an integration, an IRC connection can retrieve messages 
that are sent to an IRC nickname that you specify 
or send messages to a nickname on a channel. 
You can use the same IRC connection in any number of integrations. 

.Prerequisites

* You know the hostname and port of the IRC server that you want to
connect to.  
* If the IRC server requires a password, you know the password. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *IRC* connector.
. In the *Hostname* field, enter an IRC hostname. You can 
specify an IP address or a name, for example, `*chat.freenode.net*`.
. In the *Port* field, enter the port that the IRC server is listening on,
for example, `*6665*`.
. In the *Password* field, if the IRC server requires a password, 
enter it here. 
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the
connection configuration values and try again.
. If validation is successful, click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*IRC Freenode*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection.
. Click *Save* to see the updated list of available 
connections, including the connection that you just created. 
If you entered the example name, you would
see that *IRC Freenode* appears as a connection that you can 
choose to add to an integration. You can add this connection to 
any number of integrations. 
