//Assembly: assembly-connecting-to-virtual-databases.adoc
[id="editing-the-ddl-for-a-vdbs_{context}"]
= Using the View Editor in {prodname} to modify the DDL that defines a virtual database

The process of creating a virtual database in {prodname} is designed to automate 
many tasks and hide the complexities of the underlying SQL code. 

When you create a view for a virtual database, {prodname} automatically generates the data  definition language (DDL) that defines the view. The DDL is a set of SQL statements  that describe the view's schema, tables, columns, and other fields. 

{prodname} provides tools to add basic views for a virtual database, but if you 
know SQL and you want greater control in designing a view, you can directly edit 
the DDL for the view. In {prodname}, developers can use the embedded View Editor to 
modify these SQL statements. To assist you, this SQL editor includes a code-completion 
feature that provides a list of SQL keywords.

After you save your changes, a built-in validation tool runs to ensure that 
the SQL code does not contain syntax errors.

.Prerequisites
* You have experience using a data definition language (DDL) that is based on the 
SQL-MED specification to define database structures and to integrate externally stored data.  

.Procedure

. From the navigation sidebar in {prodname}, click *Data*.
. On the *Data Virtualizations* page, find the virtual database that you want 
to modify and click *Edit*.
. In the *Views* tab, find the view that you want to edit, and then click *Edit*. 
. Update the SQL as needed. As you edit, press *Ctrl+Space* to open the code completion tool.
. After you complete your changes, click *Save*.  
+
{prodname} validates the SQL and returns an error if the view contains invalid code.
+ 
After the SQL validates, the preview panel shows the result of the updates that you made 
to the view. The preview displays the first fifteen rows of the results set.  
. Click *Done* to close the *View Editor* and return to the list of views.
+
If the virtual database was previously published, you must republish it to put your changes into effect. 

.Additional resources
* link:{LinkFuseOnlineConnectorGuide}#publishing-a-vdbs_VDBS[Publishing virtual databases in {prodname} to make them available for access]
* For more information about using SQL in data virtualization DDL files, see the 
link:http://teiid.github.io/teiid-documents/master/content/reference/SQL_Support.html[Teiid Reference Guide]. 
* You can modify the results set by altering the default query to specify different row 
limits or row offsets. For more information, see
link:{LinkFuseOnlineConnectorGuide}#previewing-a-vdb-by-submitting-queries_VDBS[Previewing a virtual database in {prodname} by submitting SQL test queries]. 
