// This module is included in the following assemblies:
// as_connecting-to-jira.adoc

[id='adding-jira-connection-transition-issue_{context}']
= Transitioning a Jira issue to a new status

In the middle of a flow, or to finish a simple integration, 
you can connect to a Jira server to transition an issue to a new
status, or to a new workflow stage. A Jira administrator defines
what it means for an issue to transition as well as the values for 
transition IDs. 

.Prerequisites
* You created a Jira connection.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose
a simple integration's finish connection. 

.Procedure

. On the *Add to Integration* page, click the plus sign where you 
want to add a Jira connection. Skip this step if you are adding 
a simple integration's finish connection.  
. Click the Jira connection that you want the integration to use to 
connect to the Jira server. 
. On the *Choose an action* page, select *Transition Issue*.
+
You do not need to specify any values to configure the transition issue
action. Instead, you can map values from previous integration steps 
to the fields in the this connection. 

. Optionally, in the *Comment* field, enter a comment that you want to 
add to the issue. 
. Optionally, in the *Issue Key* field, enter the Jira identifier for the issue
that is transitioning.  
Examples of issue keys: `GATE-1234`, `Ent-239`. 
. Optionally, in the *ID of the transition* field, enter an integer that 
a Jira administrator has associated with a particular transition, 
such as when a Jira moves from being new to being worked on, or 
when it moves from being worked on to being tested. 
+
A Jira administrator can view transition IDs in a project’s workflow display. 
If you do not have administration permissions, obtain the allowed 
transition IDs from a Jira administrator.

. Click *Next*. 

.Result
The connection appears in the integration visualization
where you added it. 

.Next steps
If you did not specify a value in each *Transition Issue* field, 
ensure that the integration has a step that obtains the value for 
each field. After the integration has all required connections, add 
a data mapper step before the Jira connection that transitions an issue. 
In the data mapper step, map fields from previous steps to the 
fields in the Jira connection that transitions an issue. 
