// This module is included in the following assemblies:
// as_connecting-to-kafka.adoc

[id='enabling-auto-discovery-of-kafka-brokers_{context}']
= Enabling auto-discovery of Kafka brokers/AMQ Streams

In an integration, if you plan to connect to a Kafka broker that 
is an AMQ Streams instance, enable auto-discovery of such brokers 
before you create the Kafka connection. This makes creating the 
Kafka connection easier because {prodname} can provide Kafka 
broker details that are required to configure the connection. 

To enable auto-discovery, you give an OpenShift user account 
privileges that allow that account to see resources on the cluster. 
The particular privileges that you assign let the account discover 
different subsets of brokers. 

.Prerequisites

ifeval::["{location}" == "downstream"]
* You are running {prodname} on OCP on-site. 
endif::[]
* You installed the `oc` client tool and it is connected to the cluster 
in which you want to enable auto-discovery of Kafka brokers.
* You have cluster administration permissions. 
* Kafka broker(s) (AMQ Streams instances) that you want to connect to in 
an integration are installed in the same cluster as {prodname}.

 
.Procedure

. Log in to OpenShift with an account that has cluster administration 
permissions. For example:
+
----
$ oc login -u admin -p admin
----

. Ensure that the current project is the project in which {prodname} is running. 
To view the current project, invoke the following command:
+
----
$ oc project
----

ifeval::["{location}" == "upstream"]
. Ensure that the Kafka brokers that you want an integration to connect 
to are installed in the cluster. 
+
For example, to install Strimzi on minishift, follow the instructions at  
link:https://strimzi.io/quickstarts/okd/[]
 
. Invoke the following command to apply the Strimzi installation file. 
In the command line, replace `myproject` with the name of the project in 
which {prodname} is running. 
+
----
oc apply -f https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.15.0/strimzi-cluster-operator-0.15.0.yaml -n myproject
----

. Invoke the following command to provision the Apache Kafka cluster. 
Replace `myproject` with the name of the project in which {prodname} is running. 
+
----
oc apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.15.0/examples/kafka/kafka-persistent-single.yaml -n myproject
----

. Invoke the following command to deploy Kafka. Be sure to replace `mycluster` 
with the name of the cluster in which you are enabling auto-discovery, and 
replace `myproject` with the name of the project in which {prodname} is running. 
+
----
oc wait kafka/mycluster --for=condition=Ready --timeout=300s -n myproject
----

. Create a producer for the Kafka broker that you specify. For example, 
in the following command: 
+
** `myproject` is the name of the project in which {prodname} is running. 
** `my-cluster-kafka-bootstrap:9092` identifies a Kafka broker.
** `my-topic` is the name of the Kafka topic that a Kafka connection will be subscribed to.
+
[listing,options="nowrap"]
----
oc -n myproject run kafka-producer -ti --image=strimzi/kafka:0.15.0-kafka-2.3.1 --rm=true --restart=Never -- bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap:9092 --topic my-topic
----
endif::[]

. Give privileges that enable access to Kafka brokers in the cluster to an 
`oc` user account. How your cluster is configured determines the privileges 
that you need to grant. For example, for a Strimzi cluster on minishift, 
you can do the following: 
+
.. Create a cluster role that can access Kafka/Strimzi resources in the cluster. 
In the following example, `kafkas.kafka.strimzi.io-view` is the name of the new role: 
+
[listing,options="nowrap"]
----
oc create clusterrole kafkas.kafka.strimzi.io-view --verb=get,list --resource=kafkas --resource=crd
----

.. Add this cluster role to an `oc` user. In the following example, 
`syndesis-server` is the name of the `oc` user account: 
+
[listing,options="nowrap"]
----
oc adm policy add-cluster-role-to-user kafkas.kafka.strimzi.io-view -z syndesis-server
----

.Result

In {prodname}, when you create a Kafka connection, the connection configuration 
page displays the Kafka brokers that are available. You select the broker that 
you want the connection to access. 
