// This module is included in the following assembly:
// as_developing-extensions.adoc

[id='develop-library-extensions_{context}']
= How to develop library extensions

A library extension provides a resource that an 
integration requires at runtime. A library extension does not contribute steps or 
connectors to {prodname}. 

Support for library extensions is evolving. In this release, in the 
{prodname} web interface:

*  When you create an integration, 
you cannot select which library extension(s) an 
integration should include. 
+
ifeval::["{location}" == "upstream"]
For more information, see 
https://github.com/syndesisio/syndesis/issues/2808[this GitHub issue]. 
endif::[]

* When you add a database connection to an integration, 
{prodname} adds all extensions that 
have the `jdbc-driver` tag to the integration runtime. 
+
ifeval::["{location}" == "upstream"]
For more information, see 
https://github.com/syndesisio/syndesis/issues/2809[this GitHub issue]. 

endif::[]


A library extension does not define any actions. 
Here is a sample definition for a library extension:

[source,json]
----
{
  "schemaVersion" : "v1",
  "name" : "Example JDBC Driver Library",
  "description" : "Syndesis Extension for adding a custom JDBC Driver",
  "extensionId" : "io.syndesis.extensions:syndesis-library-jdbc-driver",
  "version" : "1.0.0",
  "tags" : [ "jdbc-driver" ],
  "extensionType" : "Libraries"
}
----

Other than the lack of actions, the structure of a library extension 
is the same as the structure of a step or connector extension. 

In a Maven project that creates a library extension, to add dependencies 
that are not available from a Maven repository, 
specify a `system` dependency, for example: 

[source,xml]
----
<dependency>
    <groupId>com.company</groupId>
    <artifactId>jdbc-driver</artifactId>
    <version>1.0</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/lib/jdbc-driver-1.0.jar</systemPath>
</dependency>
----
