apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    createdAt: DATE TIME TZ
    certified: "false"
    containerImage: registry.redhat.io/fuse7/fuse-online-operator:1.9
    description: Manages the installation of Fuse Online, a flexible and customizable open source platform that provides core integration capabilities as a service.
    operators.operatorframework.io/builder: operator-sdk-v1.0.5
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
    repository: https://github.com/syndesisio/syndesis/
    support: Syndesis
  name: syndesis.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Syndesis is the Schema for the Syndeses API
      displayName: Syndesis
      kind: Syndesis
      name: syndesises.syndesis.io
      resources:
      - kind: ClusterRole
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: Role
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: Secret
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
      - kind: Subscription
        name: ""
        version: operators.coreos.com/v1alpha1
      version: v1beta2
  description: |
    ### Fuse-Online operator
    Fuse Online is a flexible and customizable, open source platform that provides core integration capabilities as a service.

    This operator installs as well as configures the following Fuse Online components:
    - syndesis-server
    - syndesis-meta
    - syndesis-ui
    - syndesis-db
    - syndesis-prometheus
    - syndesis-proxy
    - syndesis-oauthproxy

    ### Before you begin
    You must configure authentication to Red Hat container registry before you can import and use the Red Hat Fuse OpenShift Image Streams. Follow instruction given below to configure the registration to container registry.

    1. Log in to the OpenShift Server as an administrator, as follow:
        ```
        oc login -u system:admin
        ```
    2. Log in to the OpenShift project where you will be installing the operator.
        ```
        oc project fuse-online
        ```
    3. Create a docker-registry secret using either Red Hat Customer Portal account or Red Hat Developer Program account credentials.
        ```
        oc create secret docker-registry syndesis-pull-secret \
          --docker-server=registry.redhat.io \
          --docker-username=CUSTOMER_PORTAL_USERNAME \
          --docker-password=CUSTOMER_PORTAL_PASSWORD \
          --docker-email=EMAIL_ADDRESS
        ```
        NOTE: You need to create a docker-registry secret in every new namespace where the image streams reside and which use registry.redhat.io.

        If you do not wish to use your Red Hat account username and password to create the secret, it is recommended to create an authentication token using a [registry service account](https://access.redhat.com/terms-based-registry/).

    ### How to install
    - When the operator is installed (you have created a subscription and the operator is running in the selected namespace) and before you create a new CR of Kind Syndesis, you have to link the secret created in the previous section to the operator service account.
    ```
    oc secrets link syndesis-operator syndesis-pull-secret --for=pull
    ```

    - Create a new CR of Kind Syndesis (click the Create New button). The CR spec contains all defaults (see below).

    ### CR Defaults
    The CR definition is pretty simple and an empy CR will trigger a base installation.

    Within the addons section, users are able to enable specific addons. The available addons at the moment are:
    - jaeger: enable jaeger
    - ops: enables monitoring, requires extra CRDs
    - todo: a simple todo application

    To enable addons, set "addon_name": {"enabled": true} in the CR.
    If you enable the todo addon, you should link the previously created syndesis-pull-secret to the builder serviceAccount.
    ```
    oc secrets link builder syndesis-pull-secret --for=pull,mount
    ```

    For a more detailed set of instructions and a complete reference of config options,
    please refer to the product documentation at https://access.redhat.com/documentation/en-us/red_hat_fuse
  displayName: Red Hat Integration - Fuse Online
  icon:
  - base64data: PHN2ZyBpZD0iYXJ0d29yayIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMTAyNCAxMDI0Ij48c2NyaXB0IHhtbG5zPSIiIGlkPSJfX2dhT3B0T3V0RXh0ZW5zaW9uIi8+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiM5YWRkZTg7fS5jbHMtMntmaWxsOiM0OWJhZGM7fTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5pY29uX2Z1bGxfMTAyNHB4PC90aXRsZT48cG9seWdvbiBjbGFzcz0iY2xzLTEiIHBvaW50cz0iNTI3Ljk1IDM3MC40MSAxMzEuODQgNTU4LjcxIDQ5Ni4wNSA2NTMuNTkgODkyLjE2IDQ2NS4yOSA1MjcuOTUgMzcwLjQxIi8+PHBvbHlnb24gY2xhc3M9ImNscy0yIiBwb2ludHM9Ijg5Mi4xNiA0NjUuMjkgODkyLjE2IDQ2NS4yOSA0OTYuMDUgNjUzLjU5IDk5MS4xNyA3ODIuNTYgODkyLjE2IDQ2NS4yOSIvPjxwb2x5Z29uIGNsYXNzPSJjbHMtMSIgcG9pbnRzPSI2MzEuMzEgMzIxLjI4IDUzMi4zIDQgMzIuODMgMjQxLjQ0IDUyNy45NSAzNzAuNDEgNjMxLjMxIDMyMS4yOCIvPjxwb2x5Z29uIGNsYXNzPSJjbHMtMiIgcG9pbnRzPSIxMzEuODQgNTU4LjcxIDUyNy45NSAzNzAuNDEgMzIuODMgMjQxLjQ0IDMyLjgzIDI0MS40NCAxMzEuODQgNTU4LjcxIi8+PHBvbHlnb24gY2xhc3M9ImNscy0yIiBwb2ludHM9Ijc3NC4zNCA2Ny4wNSA1MzIuMyA0IDYzMS4zMSAzMjEuMjggODczLjM2IDM4NC4zMyA3NzQuMzQgNjcuMDUiLz48cG9seWdvbiBjbGFzcz0iY2xzLTIiIHBvaW50cz0iMTUwLjY0IDYzOS42NyAyNDkuNjYgOTU2Ljk1IDQ5MS43IDEwMjAgNDkxLjcgMTAyMCAzOTIuNjkgNzAyLjcyIDM5Mi42OSA3MDIuNzIgMTUwLjY0IDYzOS42NyIvPjxwb2x5Z29uIGNsYXNzPSJjbHMtMSIgcG9pbnRzPSI5OTEuMTcgNzgyLjU2IDQ5Ni4wNSA2NTMuNTkgMzkyLjY5IDcwMi43MiA0OTEuNyAxMDIwIDk5MS4xNyA3ODIuNTYiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - camel
  - integration
  - syndesis
  - fuse
  - online
  labels:
    name: fuse-online-operator
  links:
  - name: Red Hat Fuse Online Documentation
    url: https://access.redhat.com/documentation/en-us/red-hat-fuse
  - name: Upstream project Syndesis
    url: https://github.com/syndesisio/syndesis
  - name: Upstream Syndesis Operator
    url: https://github.com/syndesisio/syndesis/tree/master/install/operator
  maintainers:
  - email: janstey@redhat.com
    name: Jon Anstey
  - email: parichar@redhat.com
    name: Paul Richardson
  maturity: beta
  provider:
    name: Red Hat
    url: https://access.redhat.com/products/red-hat-fuse
  selector:
    matchLabels:
      name: fuse-online-operator
  replaces: fuse-online-operator.v7.8.1
  version: 7.9.0
