#!/bin/sh
#
# Copyright (C) 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


# Run the original assemble script.
/usr/local/s2i/assemble
rc=$?

if [ $rc -eq 0 ]; then
    # Load global S2I variable setup
    source /usr/local/s2i/s2i-setup

    # Make PropertiesLoader sirectory structure
    mkdir -p $JAVA_DATA_DIR/syndesis/loader

    if [ -d $S2I_SOURCE_DIR/extensions ]; then
        echo "copy $S2I_SOURCE_DIR/extensions to $JAVA_DATA_DIR/syndesis/loader"
        cp -rv $S2I_SOURCE_DIR/extensions $JAVA_DATA_DIR/syndesis/loader
    fi
else
    echo "assemble failed with rc=$rc"
fi

exit $rc
