
[[syndesis-install]]
== syndesis install

With `syndesis install` you can install Syndesis to an arbitrary OpenShift cluster.
If you want to install to https://code-ready.github.io/crc/[CodeReady Containers] or
https://www.openshift.org/minishift/[Minishift] the <<syndesis-crc,syndesis crc>> or
<<syndesis-minishift,syndesis minishift>> command is recommended as it supports some additional
features specific to these local development environments.

[[syndesis-install-usage]]
=== Usage

[source,indent=0,subs="verbatim,quotes"]
----
Options for install:
-s  --setup                   Install CRDs clusterwide. Use --grant if you want a specific user to be
                              able to install Syndesis. You have to run this option once as cluster admin.
-u  --grant <user>            Add permissions for the given user so that user can install the operator
                              in her projects. Must be run as cluster admin.
    --cluster                 Add the permission for all projects in the cluster
                              (only when used together with --grant)
-p  --project                 Install into this project. Delete this project
                              if it already exists. By default, install into the current project (without deleting)
    --operator-only           Only install the operator but no resource
                              connected cluster.
    --tag <tag>               Syndesis version/tag to install. If not given, then the latest
                              version from master is installed
    --force                   Override an existing "Syndesis" if present
-w  --watch                   Wait until cluster is up
    --local                   install from local Git repo when using. By default the resource descriptor is
                              downloaded from GitHub remotely.
-f  --force-binary-download   By default if the binary cli is present in the expected path, it will
                              be used. With this option enabled, the binary will be removed and downloaded,
                              ensuring it is the latest version
-o  --open                    Open Syndesis in browser when installation is ready (implies --watch)
-y  --yes                     Assume 'yes' automatically when asking for deleting
                              a given project.
    --memory-server <mem>     Memory limit to set for syndesis-server. Specify as "800Mi"
    --memory-meta <mem>       Memory limit to set for syndesis-meta. Specify as "512Mi"
    --test-support            Allow test support endpoint for syndesis-server
    --datavirt                Install Data Virtualizations.
    --maven-mirror            Install Maven Mirror to be used with --maven-mirror when building.
    --man                     Open HTML documentation in the Syndesis Developer Handbook
----

You have to run `--setup --grant <user>` as a cluster-admin before you can install Fuse Online as a user.

The deployment happens to the currently connected OpenShift cluster.
So it's mandatory that you have logged into the cluster with `oc login` before.
You can check the status with `oc status`.

The installation process consists of two steps:

* An initial setup which has to be performed as _cluster admin_ which is a one-off action which needs to be done only once.
* Installation of Syndesis into a specific project by the _app admin_, a regular user of OpenShiftm which can be performed as many times as required.

=== Initial Setup

In the initial setup, you have to register the custom resource definition (CRD) to allow to deploy `Syndesis` resources.
This step has to be performed by the admin.

Also, if you want to allow an OpenShift user to install Syndesis on her own, then you have to grant specific permissions to her.

To perform this setup step, which needs to be performed only once per cluster, you have to run `syndesis` **while being connected as a cluster admin**.
For `minishift` use `oc login -u system:admin` if you have the `admin-user` addon enabled, for crc follow the login instructions you got when starting up crc.

[source,bash,indent=0,subs="verbatim,quotes"]
----
syndesis install --setup
----

This will install only the CRD. In addition, you can grant a user _user_ the proper permission to create a `Syndesis` resource, you should add `--grant <user>`:

[source,bash,indent=0,subs="verbatim,quotes"]
----
syndesis install --setup --grant <user>
----

This call adds permissions to read and write `Syndesis` resource objects for the current project.
If you would instead want to allow the user managing `Syndesis` resources in the whole cluster, you should add a
`--cluster`.
This cluster-wide access is especially required when you plan to use the `--project` option to use a new project or recreate the existing one, as in this case the role association to this project gets lost.

=== Installing Syndesis

After the CRD is registered, you can easily install Syndesis directly with

[source,bash,indent=0,subs="verbatim,quotes"]
----
syndesis install
----

Depending on whether you have granted the current user access this step has to be done either as admin or as a regular user.

.Example for CodeReady Containers
[source,bash,indent=0,subs="verbatim,quotes"]
----
# Create a crc instance
crc start

# Switch to admin
oc login -u system:admin

# Register CRD and grant permissions to "developer"
syndesis install --setup --grant developer --cluster

# Switch to account developer
oc login -u developer

# Install Syndesis
syndesis install
----

By default, this commands installs Syndesis in the currently connected project, but you can specify an alternative project with `--project <project>`.
If this project already exists, it gets deleted unconditionally before the deployment, so be careful when using this option.
By default, you are asked whether you want to delete the project for recreation.
You can switch off the security question with the option `--yes` (short: `-y`).

WARNING: Don't use `syndesis install --project $(oc project -q) --yes`. You'll shoot yourself into the foot. Ask the author if you want to know more details.

If you want to wait until everything is running (including fetching of the Docker images), you can specify `--watch` (short: `-w`) which blocks the script until everything is set up.

You can also automatically open Syndesis in the browser after the installation with `--open` (short: `-o`)

=== Development mode

As with <<syndesis-crc,syndesis crc>> or <<syndesis-minishift,syndesis minishift>> you can also use this command to set up a development platform for Syndesis.
_Development platform_ here means that you can create Docker images on your own with <<syndesis-build,syndesis build>> and can use them with an automatic redeployment after the build.

You can switch on this mode with the option `--dev`.
When the operator has deployed the application, the application imagestreams refer to Docker images pushed to Docker Hub.
To change the imagestream references to the images built with `syndesis build --all-images`, these imagestreams needs to be patched after the initial images have been fetched from Docker Hub.
If you use the `--dev` option, then this update is done automatically.

=== Selecting the version

With the option `--tag` you can select a specific version of Syndesis to install.
By default, the currently checked out checked out branch is used.

.Example
[source,bash,indent=0,subs="verbatim,quotes"]
----
syndesis install --tag 1.4
----

This example installs the latest Syndesis version of the 1.4 branch to the local cluster.

You can see a list of available tags with `git tag`.
Tags prefixed with `fuse-ignite` are suited for the Fuse Online cluster as those templates do not contain images streams themselves but refer to the image streams installed on this cluster.
