[[syndesis-dev]]
== syndesis dev

Dev commands are useful helpers for developing Syndesis

[[syndesis-dev-usage]]
=== Usage

[source,indent=0,subs="verbatim,quotes"]
----
Usage: syndesis dev [... options ...]

Options for dev:
    --debug <name>            Setup a port forwarding to <name> pod (default: server)
    --cookie                  Loads a local valid cookie to access Syndesis APIs when using Minishift
    --cleanup                 Removes 'Completed' pods
    --refresh                 Used in conjuction with --cookie, forces a refresh of the cookie.
                              Ex: curl -k --cookie $(syndesis dev --cookie --refresh)  "https://$(oc get route syndesis  --template={{.spec.host}})/api/v1/connections"
    --update-manifest <name>  Updates the json manifest for the given connector
    --install-maven-mirror    Install Maven Nexus app as mirror to current cluster.
    --version                 Show running version of cluster
----

=== Enable debug mode

This command enable port-forwarding of port 5005 from a specific pod (by default: "server") to port 5005 on the localhost.
You then can point your Java IDE to port 5005 on localhost for connecting for remote debugging.
As argument to `--debug` "server", "meta" and "atlasmap" can be used, which are our Java based services.

=== Install Maven Nexus as mirror

The Syndesis S2i builds are loading dependencies from Maven central respectively Red Hat repositories. In order to improve performance and
save some bits in transfer we recommend to use a Maven Nexus as mirror. This will decrease the amount of bits loaded from the internet every time
a Syndesis integration is created.

You can add the Maven Nexus application in a separate project namespace to the OpenShift cluster by using:

[source,bash,indent=0,subs="verbatim,quotes"]
----
syndesis dev --install-maven-mirror
----

This will create a new project on the cluster `nexus` and will install the latest Nexus Maven repository manager. You can use this Nexus instance
when building and pushing new images to the Syndesis image streams using S2i.

[source,bash,indent=0,subs="verbatim,quotes"]
----
syndesis -m s2i -i --maven-mirror http://nexus-nexus.apps-crc.testing/nexus/content/groups/public
----

This will build a new base S2i image and use the Maven Nexus as mirror so all previously loaded dependencies will be loaded from the local
Nexus instance instead of loading from the internet.
