[[syndesis-build]]
== syndesis build

The primary goal of `syndesis build` is to build Syndesis.

It is mainly a wrapper around Maven and Go but adds some convenience functionality for common developer workflows.

[[syndesis-build-usage]]
=== Usage
[source,indent=0,subs="verbatim,quotes"]
----
Build Syndesis builds

Usage: syndesis build [... options ...]

Options for build:
    -b  --backend                  Build only backend modules (core, extension, integration, connectors, server, meta)
        --all-images               Build all modules with images: ui, server, meta, s2i, operator, upgrade, camel-k
        --app-images               Build only application modules with Docker images (ui, server, meta, s2i)
                                   and create images
        --infra-images             Build only infrastructure modules with Docker images (operator, camel-k, upgrade) and create images
    -m  --module <m1>,<m2>, ..     Build modules
                                   Top level modules: ui, server, connector, s2i, meta, integration, extension, common, operator, camel-k, upgrade
                                   Submodules: defined with [groupId]:artifactId (e.g. :connector-sql)
    -d  --dependencies             Build also all project the specified module depends on
        --skip-tests               Skip unit and system test execution
        --skip-checks              Disable all checks
    -f  --flash                    Skip checks and tests execution (fastest mode)
    -i  --image                    Build Docker via s2i images, too (for those modules creating images)
        --docker                   Use a plain Docker build for creating images. Used by CI for pushing to Docker Hub
        --multi-stage              Multi-stage Dockerfile support for operator build (experimental)
    -p  --project <project>        Specifies the project / namespace to create images
    -g  --goals <g1>,<g2>, ..      Use custom Maven goals to execute for the build. Default goal is `install`
    -e  --ensure                   If building the operator , run 'dep ensure' before building. Otherwise ignored.
    -l  --local                    If building the operator, use a locally installed go
                                   Otherwise run the Go build from a container (either local or Minishift's Docker  daemon)
        --clean-cache              Used for the operator build to remove the local dependency cache.
    -c  --clean                    Run clean builds (mvn clean)

        --resume <m1>              Resume build from maven module (mvn -rf m1)
        --batch-mode               Run mvn in batch mode
        --camel-snapshot <version> Run a build with a specific Camel snapshot. If no argument is given the
                                   environment variable CAMEL_SNAPSHOT_VERSION is used or an error thrown.
        --maven-mirror <url>       Use the maven mirror for the build, e.g. a maven repo proxy in OpenShift. If no
                                   argument is given, the MAVEN_MIRROR_URL environment variable is used. If none is set
                                   and the mirror has been provisioned with --maven-mirror during installation,
                                   the url is automatically detected.
                                   See also https://docs.openshift.com/container-platform/3.5/dev_guide/app_tutorials/maven_tutorial.html
        --man                      Open HTML documentation in the Syndesis Developer Handbook
----

[[syndesis-build-modules]]
=== Modules
A plain `build` command without any options performs a plain `mvn install` for all Java and UI modules.
Plus it also builds the infrastructure operator via Go (see <<below,syndesis-build-operator>> for details).
The goal `install` is the default but you can customize the Maven goals with `--goals` (short: `-g`) option.

This compiles all Java and Javascript artifacts and also runs all tests and code checks for the application modules.

You restrict the build to certain modules, which are divided into two categories: _application modules_ which are the modules building up Syndesis.
And _infrastructure modules_ which help in managing the application itself.

You can individually select specific modules by using the `--module` (short: `-m`) option with a comma-separated list of modules. Modules are either top level
modules that combine a set of Maven submodules in a logical unit or individual submodules defined with `[groupId]:artifactId`.

The following top level modules are available:

[cols="5,10,2,2,2,2", options="header"]
|===
| Module | Description | `--all-images` | `--backend` | `--app-images` | `--infra-images`

| **server**
| Main backend providing a REST API for the user interface
| ✔︎
| ✔︎
| ✔︎
|

| **ui**
| The SPA user interface application
| ✔︎
|
| ✔︎
|

| **meta**
| Meta data and verifier used for verifying connections and providing connector metadata
| ✔︎
| ✔︎
| ✔︎
|

| **connector**
| All connectors used by Syndesis out of the box
|
| ✔︎
|
|

| **integration**
| Support libraries for running integrations
|
| ✔︎
|
|

| **extension**
| Tools for developing and running Syndesis custom extensions
|
| ✔︎
|
|

| **common**
| Common modules containing common code
|
| ✔︎
|
|

| **s2i**
| S2I base image used for building the runtime images
| ✔︎
|
| ✔︎
|

| **operator**
| Infrastructure operator for managing the application
| ✔︎
|
|
| ✔︎
|===

All option ending with `-images` will also build the corresponding Docker image.

In addition to using top level modules that combine to a set of submodules you can also specify a very specific submodule using
its groupId and/or artifactId. For instance the module name for the SQL connector module would be `io.syndesis.connector:connector-sql`
or simply `:connector-sql`. In case you skip the groupId the leading colon in the module name is very important because this identifies
the module to be a submodule rather that a top level module.

When you build individual modules you can provide the option `--image` (short: `-i`) to create also the Docker image in the build, when the module is associated with a Docker image.

By default images are build via S2I against a running Minishift.
This is the recommended way for developing as this automatically will trigger a redeployment after the build.
However, for certain scenarios like when used in a CI system or when doing the release, the image creation can be done against are Docker daemon when the `--docker` is given.
For this to work you must have access to Docker daemon, which you can verify with `docker ps`.

When the option `--dependencies` (short: `-d`) is given in addition to `--modules`, also all Maven modules which the specified modules depend on are build, too.

[[syndesis-build-tuning]]
=== Tuning
By default, all checks like license or code quality checks are performed.
Also, all unit and local integration tests are run.
A full build eats up quite some time, but you should always run at full blast before submitting a pull request.

However, to speed up the turnaround, several speed-up options are available.
The following table shows these options, and also how long a full clean build over all modules takes: (but without building images)

[cols="3,15,2",options="header"]
|===
|Option
|Description
|Time

| _none_
| Default mode with all checks and tests
|

| `--skip-tests`
| Skip all unit and local integration tests
|

| `--skip-checks`
| Skip sanity checks like for correct license headers and
|

| `--flash`
| Fastest mode with skipping all checks and tests and with even some other aggressive optimizations
|

|`--maven-mirror <url>`
| Use a maven mirror, e.g. a maven repo proxy in OpenShift with cached dependencies. See also [setting up a maven mirror](https://docs.openshift.com/container-platform/3.5/dev_guide/app_tutorials/maven_tutorial.html).
|


|`--goals <goal>`
| Use custom Maven goals to execute for the build. Default goal is `install`.
|

| `--camel-snapshot <version>`
| Sometimes it's needed to use a Camel snapshot version for building. This snapshot most be available in you local Maven repo (`~/.m2`) Use this option with the Camel version. Alternatively, you can also set the environment variable `CAMEL_SNAPSHOT` to the corresponding version.
|===

[[syndesis-build-operator]]
=== Infrastructure Operator

`syndesis build` can also build the infrastructure operator, which is a golang program.

You can build the operator by running `syndesis build -m operator` or
as part of a module collection like `--all-images` or `--infra-images`

There are three modes, how the operator can be created:

* Running your go compiler locally
* Compiling in a local Docker daemon which allows volume mounts with the localhost
* Compiling in Minishift Docker daemon, which was made accessible via `eval $(minishift docker-env)`

See below for the details.

.Load dependencies

In any case, before you compile first you should use the option `--ensure` (short: `-e`) to setup the dependency tree.
This will download all source dependency and cache them locally.
To get rid of this cache, use the option `--clean-cache`.
This might be necessary when `go dep` 's cache gets into a weird state.

If you compile for the first time, then `--ensure` will be added automatically.

.Compiling locally

This is the fastest way for compiling the operator.
Use the option `--local` (short: `-l`) for selecting the local compile mode.

It is also the recommended way when you are working on the operator.
You project setup needs to fit however: The main project directory must be reachable as `$GOPATH/src/github.com/syndesisio/syndesis`.
You can either move your project directory to this location or work with a symlink:

[source,shell,indent=0,subs="verbatim,quotes"]
----
cd ~/Development/syndesis
mkdir -p $GOPATH/src/github.com/syndesisio
cd ..
mv syndesis $GOPATH/src/github.com/syndesisio/
ln -s $GOPATH/src/github.com/syndesisio/ syndesis
----

By default this compiles into for your native architecture (amd64, darwin).
When you use this mode with `--image` (short: `-i`) on macOS then go will be used as cross compiler so that the generated bimary can be used in a Linux image.

.Compiling with a local Docker daemon

This is the default mode and is used also when doing the release.
It use a builder image `syndesis/godev` which is created from the `tools/image` directory and fetched from Docker Hub.

For this mode to work your Docker daemon must support volume mounts to the system from where you are calling `syndesis`.
This is the case on Linux for locally installed Docker daemon and for Mac with _Docker for Mac_.
It is *not* the case for Minishift which runs in a disconnected VM.
But see below how you still can use Minishift for building.

`dep ensure` and `go build` will be run from this `syndesis/godev` image, but with your local directory mounted into the container so that the fetched dependencies can be cached in the local directories `dep-cache` and `vendor` so that the can be reused for the next run.
Also the binary will be stored in your local directory, but this will alway be a Linux (`amd64`) binary.

.Compiling with Minishift

As Minishift is running in a remote VM you cannot bind a volume to your localhost. Therefor when running in Minishift mode the source code will be rsynced to a directory in the Minishift VM (`rsync` will be installed in the Minishift VM on the first run).

The build with `syndesis/godev` will then be started with a volume mount to the copied directory in the VM.
After the build the generated binary is copied back with `rsync` to your local directory.

The Minishift mode is automatically detected and selected if `DOCKER_CERTS` contains a path to `.minishift`.
You enable the Minishift Docker daemon for your local CLI with `eval $(minishift docker-env)`

Some simple benchmark reveals the following timings (in minutes) :

[cols="5,7,7,7",options="header"]
|===
| Context | Local | Local Docker (macOS) | Minishift Docker

| Cold (no build cache)
| 0:40
| 10:09
| 1:36

| Hot (with dep cache)
| 0:08
| 2:47
| 0:13
|===

The fastest mode is obviously the local mode, followed surprisingly by Minishift.
The local mode is probably slow because of how the macOS daemon mounts ts volumes (which can probably be optimized)

=== Examples

Some common usage examples for `syndesis build` are

[source,shell,indent=0,subs="verbatim,quotes"]
----
# Build all images (app and infrastructure) with S2I
syndesis build --all-images

# Create all application images and re-deploy Syndesis in the
# Openshift cluster, but do it as fast as possible. Don't build
# any golang code
syndesis build --app-images --flash

# Create the infrastructure operator by running go locally
# and calling `dep ensure before`
syndesis build -m operator --local --ensure

# Use a Camel snapshot for a clean build, build all modules
syndesis build --clean --camel-snapshot 2.21.0-SNAPSHOT
----
