[[syndesis-crc]]
== syndesis crc

With `syndesis crc` you can adequately manage a https://code-ready.github.io/crc/[CodeReady Containers] installation for hosting Syndesis.
This command is especially useful for a simple and self-contained development workflow.

`syndesis crc` requires that you have a current crc binary in your path.
You can download it directly from https://cloud.redhat.com/openshift/install/crc/installer-provisioned[https://cloud.redhat.com].

`syndesis crc` will attempt to download the latest syndesis cli from the https://github.com/syndesisio/syndesis/releases/latest[syndesis release page]. If this fails, you can try downloading the right binary for your distribution and placing it under `tools/bin/commands/binaries`.

[[syndesis-crc-usage]]
=== Usage

[source,indent=0,subs="verbatim,quotes"]
----
    --install                 Install templates to a running OCP4 CodeReady Containers cluster.
-p  --project                 Install into this project.
                              Delete this project if it already exists.
                              By default, install into the current project (without deleting)
    --reset                   Reset and initialize the CodeReady Containers installation by
                              'crc delete && crc start'.
    --full-reset              Full reset and initialie by
                              'crc stop && rm -rf ~/.crc/* && crc start'
    --operator-only           Only install the operator but no resource
                              connected cluster.
    --memory <mem>            How much memory to use when doing a reset. Default: 8192
    --cpus <nr cpus>          How many CPUs to use when doing a reset. Default: 4
    --pull-secret-file <file> File holding the OCP4 pull secret
    --vm-driver <driver>      Which virtual machine driver to use (depends on OS)
    --bundle <path-to-bundle> Path to system bundle (required when using virtualbox vm-driver)
    --local                   Use the local resource files instead of fetching them from GitHub
-f  --force-binary-download   By default if the binary cli is present in the expected path, it will
                              be used. With this option enabled, the binary will be removed and downloaded,
                              ensuring it is the latest version
-o  --open                    Open Syndesis in the browser
-y  --yes                     Assume 'yes' automatically when asking for deleting
                              a given project.
    --memory-server <mem>     Memory limit to set for syndesis-server. Specify as "800Mi"
    --memory-meta <mem>       Memory limit to set for syndesis-meta. Specify as "512Mi"
    --test-support            Allow test support endpoint for syndesis-server
    --datavirt                Install Data Virtualizations
    --maven-mirror            Install Maven Mirror to be used with --maven-mirror when building to speed up builds.
    --man                     Open HTML documentation in the Syndesis Developer Handbook
----

=== Installing Syndesis

You can easily install Syndesis with the option `--install`.
This option triggers the creation of all relevant OpenShift resources objects in the currently connected OpenShift project.

If you want to use a different project, then use `--project` (short: `-p`) to specify this project.

WARNING: Any existing project will be deleted first when specified with `--project`. This option is also an easy and quick way to recreate a Syndesis installation.

=== Resetting CodeReady Containers

The quickest way to get a fresh Syndesis setup is to use `--project` which will install Syndesis into a clean, new project.

However, you can also recreate the whole CodeReady Containers installation with `--reset`. This will delete the CodeReady Containers VM (`crc delete`) and create a new one (`crc start`).
It doesn't harm if the CodeReady Containers VM does not exist so that you can use `--reset` also on a fresh CodeReady Containers installation.

If you want to get a real clean installation use `--full-reset` which deletes the `~/.crc` directory which holds downloaded artifacts like the ISO image for the CodeReady Containers VM.
Using `--full-reset` forces CodeReady Containers to re-download all those files.

There are several options which influence the re-creation of the VM:

[cols="5,10,2",options="header"]
|===
| Option
| Description
| Default

|`--memory`
| Memory to use for the CodeReady Containers VM.
| 8 GB

|`--cpus`
| Number of CPUs used for the CodeReady Containers VM.
| 4

|`--pull-secret-file`
| File holding the OCP4 pull secret
| -

|`--vm-driver`
| Which virtual machine driver to use. For OS X this can be 'virtualbox'.
| -

|`--bundle`
| Path to system bundle (required when using virtualbox vm-driver)
| -

|===

=== Example

This short example performs the following actions:

* Stops and deletes a running CodeReady Containers VM (if existent)
* Removes `~/.crc` (if existent)
* Install Syndesis in OpenShift modes (S2I builds & image streams) in project `syndesis`
* Open Syndesis UI in the default browser

```
# Complete fresh installation in project "syndesis"
syndesis crc --full-reset --install --project syndesis

# Open Syndesis in default browser
syndesis crc -o
```
