apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: syndesis-infra
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/component: service-monitor
    syndesis.io/type: infrastructure
    monitoring-key: middleware
spec:
  endpoints:
  - targetPort: metrics
  selector:
    matchLabels:
      syndesis.io/app: syndesis
    matchExpressions:
      - key: syndesis.io/component
        operator: In
        values:
          - syndesis-db
          - syndesis-meta
          - syndesis-server
