{
 "title": "Syndesis - Integrations - Camel",
 "tags": [
  "syndesis",
  "integrations"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"syndesis-integrations\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{namespace=\"$namespace\",job=\"syndesis-integrations\"}, pod)"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# $pod" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - (io_syndesis_camel_StartTimestamp{namespace=\"$namespace\", pod=\"$pod\"} / 1000)"
    }
   ]
  },
  {
   "title": "Inflight messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesInflight{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Failures handled",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_FailuresHandled{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Redeliveries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_Redeliveries{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Threads blocked",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ThreadsBlocked{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Threads interrupted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "org_apache_camel_ThreadsInterrupted{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Messages per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(org_apache_camel_ExchangesFailed{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}[5m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Mean processing time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(org_apache_camel_TotalProcessingTime{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}[5m]) / rate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\", pod=\"$pod\", type=\"routes\"}[5m])",
     "legendFormat": "Mean processing time"
    }
   ]
  }
 ]
}