{
 "title": "Syndesis - Integrations - Home",
 "tags": [
  "syndesis",
  "integrations"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=\"syndesis-integrations\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 5 by CPU usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(topk(5, sum(rate(process_cpu_seconds_total{namespace=\"$namespace\", job=\"syndesis-integrations\"}[1m])) by (pod)))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 by message errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort(\n  topk(5,\n    sum(\n      rate(org_apache_camel_ExchangesFailed{namespace=\"$namespace\", job=\"syndesis-integrations\", type=\"routes\"}[5m])\n      /\n      rate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\", job=\"syndesis-integrations\", type=\"routes\"}[5m])\n    ) by (pod) * 100\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All integrations",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", job=\"syndesis-integrations\"}) by (pod)"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\", job=\"syndesis-integrations\"}[1m])) by (pod)"
    },
    {
     "expr": "sum(rate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\", job=\"syndesis-integrations\", type=\"routes\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(rate(org_apache_camel_ExchangesFailed{namespace=\"$namespace\", job=\"syndesis-integrations\", type=\"routes\"}[5m]) / rate(org_apache_camel_ExchangesTotal{namespace=\"$namespace\", job=\"syndesis-integrations\", type=\"routes\"}[5m])) by (pod)"
    }
   ]
  }
 ]
}