{
 "title": "Syndesis - Infra - Home",
 "tags": [
  "syndesis",
  "infra"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(up{job=~\"syndesis-.+\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Syndesis Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",job=\"syndesis-server\"}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",job=\"syndesis-server\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",job=\"syndesis-server\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",job=\"syndesis-server\",area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",job=\"syndesis-server\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"syndesis-server\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",job=\"syndesis-server\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",job=\"syndesis-server\",status!~\"2..\"}[5m]))"
    }
   ]
  },
  { "title": "Syndesis Meta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",job=\"syndesis-meta\"}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",job=\"syndesis-meta\",area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",job=\"syndesis-meta\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",job=\"syndesis-meta\",area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\",job=\"syndesis-meta\",area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"syndesis-meta\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",job=\"syndesis-meta\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",job=\"syndesis-meta\",status!~\"2..\"}[5m]))"
    }
   ]
  },
  { "title": "Syndesis DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",job=\"syndesis-db\"}"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_database_size{namespace=\"$namespace\", job=\"syndesis-db\", datname=\"syndesis\"}[5m]))"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_stat_database_numbackends{namespace=\"$namespace\", job=\"syndesis-db\", datname=\"syndesis\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(pg_settings_max_connections{namespace=\"$namespace\",job=\"syndesis-db\"}[5m]))"
    }
   ]
  },
  {
   "title": "Commits per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{namespace=\"$namespace\",job=\"syndesis-db\",datname=\"syndesis\"}[5m])"
    }
   ]
  },
  {
   "title": "Rollbacks per second",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{namespace=\"$namespace\",job=\"syndesis-db\",datname=\"syndesis\"}[5m])"
    }
   ]
  }
 ]
}