// This assembly is included in the following assemblies:
// as_developing-extensions.adoc

:context: extensions
[id='develop-step-extensions_{context}']
= Alternatives for developing step extensions 
:context: step-alternatives

A step extension implements one or more custom steps. 
Each custom step implements one action for processing integration data
between connections. 
The following examples demonstrate the alternatives for developing
step extensions: 

* <<example-route-xml-fragment_{context}>>
* <<example-route-builder_{context}>>
* <<example-camel-bean_{context}>>
* <<example-step-api_{context}>>

Syndesis provides custom Java annotations that you can use in 
conjunction with the `syndesis-extension-plugin`.  When you implement
a step extension or a connector extension in Java, you can specify annotations 
that enable Maven to add action definitions to the extension definition JSON file. 
To enable annotation processing,  add 
the following dependency to your Maven project:

[source,xml]
----
<dependency>
  <groupId>io.syndesis.extension</groupId>
  <artifactId>extension-annotation-processor</artifactId>
  <optional>true</optional>
</dependency>
----

include::r_example-route-xml-fragment.adoc[leveloffset=+1]

include::r_example-route-builder.adoc[leveloffset=+1]

include::r_example-camel-bean.adoc[leveloffset=+1]

include::r_example-step-api.adoc[leveloffset=+1]

:context: extensions
