// This assembly is included in the following assemblies:
// upstream: integrating-applications/master.adoc
// downstream: integrating-applications-with-fuse-online/master.adoc

:context: ug
[id='trigger-integrations-with-api-calls_{context}']
= Triggering integration execution with a REST API call

:context: api-provider

To trigger execution of an integration on demand, start the integration
with a REST API service that you provide. 
Integrations that start this way are referred to as _API provider 
integrations_. An API provider integration allows REST API clients to invoke 
commands that trigger execution of the integration. 

When {prodname} publishes an API provider integration, it annotates the API 
service definition for use with Red Hat 3scale. 3scale is Red Hat's API
management solution. 3scale enforces API access policies, centralizes 
API control, provides high availability for your API, and integrates with 
Red Hat Fuse. Without 3scale, there is no access control. Anyone with 
network access to the integration endpoint can trigger execution of 
the integration.For more information, see the API Gateway 
documentation that is available from 
https://access.redhat.com/documentation/en-us/red_hat_3scale/2.3/[the Red Hat 3scale documentation page.]

If you are running {prodname} on OCP on premise, the default 
behavior is that APIs are not exposed for automatic discovery in 
3scale. To expose APIs for automatic discovery in 3scale, see 
link:{LinkFuseOnlineIntegrationGuide}#expose-apis_ocp[Expose APIs in 3scale for API provider integrations].

The following topics provide information and 
instructions for creating API provider integrations: 

* xref:overview-benefit-api-provider-integrations_{context}[]
* xref:about-api-provider-flows_{context}[]
* xref:about-api-provider-urls_{context}[]
* xref:requirements-for-api-provider-integrations_{context}[]
* xref:workflow-api-providers_{context}[]
* xref:create-api-provider-integration_{context}[]
* xref:create-integration-operation-flows_{context}[]
* xref:configure-publish-api-provider-quickstart_{context}[]
* xref:try-api-provider-quickstart_{context}[]

include::c_overview-benefit-api-provider-integrations.adoc[leveloffset=+1]

include::c_about-api-provider-flows.adoc[leveloffset=+1]

include::c_about-api-provider-urls.adoc[leveloffset=+1]

include::r_requirements-for-api-provider-integrations.adoc[leveloffset=+1]

include::c_workflow-api-providers.adoc[leveloffset=+1]

include::p_create-api-provider-integration.adoc[leveloffset=+1]

include::p_create-integration-operation-flows.adoc[leveloffset=+1]

include::p_configure-publish-api-provider-quickstart.adoc[leveloffset=+1]

include::p_try-api-provider-quickstart.adoc[leveloffset=+1]

:context: ug
