// Module included in the following assemblies:
// as_trigger-integrations-with-api-calls.adoc

[id='about-api-provider-flows_{context}']
= About API provider flows

A {prodname} integration that does not start with a REST API service has one 
flow. That is, each time {prodname} executes the integration, {prodname} 
connects to the same applications, applies the same steps between connections, 
and finishes integration execution in the same way. In other words, 
the integration has one execution path.
 
An API provider integration has multiple flows. Each operation that the 
OpenAPI document defines has its own flow, which {prodname} automatically 
creates. For each operation, you can edit its flow by:
   
* Adding connections to the applications that need to process the data.
* Adding steps between connections, including data mapping steps.
* Altering the return code for the finish connection, which sends a 
response to the application that invoked the call that triggered
execution of the integration. 
