// This module is included in these assemblies:
// as_high-level-overview.adoc

[id='how-it-works_{context}']
= How {prodname} works

{prodname} provides a web browser interface that lets you integrate two or
more different applications or services without writing code. It also provides
features that allow you to introduce code if it is needed for complex
use cases.

{prodname} lets you enable data transfer between different applications. 
For example, a business analyst can use {prodname} to capture 
tweets that mention customers and then leverage the data obtained from 
Twitter to update Salesforce accounts. Another example is a service
that makes stock trade recommendations. You can use {prodname} to 
capture recommendations for buying or selling stocks of interest
and forward those recommendations to a service that automates stock transfers.

To create and run a simple integration, the main steps are:

. Create a connection to each application that you want to integrate.
. Select the start connection. This connection is to the application that
contains the data that you want to share with another application.
+
Alternatively, you can start the integration with a timer or a webhook
that accepts an HTTP request.

. Select the finish connection. This connection is to the application
that receives data from the start connection and that completes the
integration.
. Map data fields from the start connection to data fields in the
finish connection.
. Give the integration a name.
. Click *Publish* to start running the integration.

Another kind of integration is an API provider integration. 
An API provider integration allows REST API clients to invoke 
commands that trigger execution of the integration. To create 
and run an API provider integration, you upload an OpenAPI 2.0
document to {prodname}. This document specifies the operations
that clients can call. For each operation, you specify and 
configure the flow of connections and steps, such as data mapper
or filter steps, that executes
that operation. A simple integration has one primary flow while an 
API provider integration has a primary flow for each operation. 

The {prodname} dashboard lets you monitor and manage integrations. You can
see which integrations are running, and you can start, stop, and edit integrations.
