// Module included in the following assemblies:
// as_trigger-integrations-with-api-calls.adoc

[id='overview-benefit-api-provider-integrations_{context}']
= Overview and benefit of API provider integrations

API provider integrations start with a REST API service that {prodname} 
makes available. This REST API service is defined by an OpenAPI 2.0
document that you provide. 

The benefit of API provider integrations
is that calls from REST API clients trigger execution of the integration. 
This is different from other {prodname} integrations. A traditional
{prodname} integration periodically monitors an application or 
service and triggers execution of the integration when it finds a new
event or message. For example, an integration might start with a Twitter
connection that watches for tweets that contain `Red Hat Fuse`. {prodname}
executes the integration only when the connection to Twitter finds such tweets.

An API provider integration makes it possible to call a REST API when a 
particular event occurs. This call
triggers execution of the integration. To set this up, you upload an OpenAPI 2.0
document to {prodname}. {prodname} publishes the API and provides the URL 
where the service is available. In {prodname}, for each operation that the OpenAPI 
document defines, you add connections and steps that process data
as required for the particular operation. For example, consider a human 
resources application that calls a REST API service that {prodname} has 
made available. Suppose the call invokes the operation that adds a new
employee. The integration flow that handles this call could:

* Connect to an application that creates an expense report for new employee 
equipment.
* Connect to a SQL database to add an internal ticket for setting up new 
equipment.
* Connect to Google mail to send a message to the new employee that provides 
orientation information. 

There are many ways to call the REST APIs that trigger integration execution, 
including: 

* A web browser page that takes data input and generates the call.
* An application that explicitly calls the REST APIs. 
* Other APIs that call the REST API, for example a webhook. 
