// Module included in the following assemblies:
// as_trigger-integrations-with-api-calls.adoc

[id='overview-benefit-api-provider-integrations_{context}']
= Overview and benefit of API provider integrations

API provider integrations start with a REST API service that {prodname} 
makes available. This REST API service is defined by an OpenAPI 2.0
document that you provide. When you publish an API provider integration,
{prodname} deploys the REST API service on OpenShift. 

The benefit of API provider integrations
is that calls from REST API clients trigger execution of the integration. 
This is different from {prodname} simple integrations. A 
{prodname} simple integration periodically monitors an application or 
service and triggers execution of the integration according to how
you configure the connection to that application or service. 
For example, an integration might start with a Salesforce
connection that watches for the creation of new leads. {prodname}
executes the integration only when the connection to Salesforce finds 
a new lead.

An API provider integration makes it possible to call a REST API when a 
particular event occurs. This call
triggers execution of the integration. To set this up, you upload an OpenAPI 2.0
document to {prodname}. {prodname} publishes the API and provides the URL 
where the service is available. In {prodname}, for each operation that the OpenAPI 
document defines, you add connections and other steps to the flow for that
operation. These steps process the data
as required for the particular operation. For example, consider a human 
resources application that calls a REST API service that {prodname} has 
made available. Suppose the call invokes the operation that adds a new
employee. The operation flow that handles this call could:

* Connect to an application that creates an expense report for new employee 
equipment.
* Connect to a SQL database to add an internal ticket for setting up new 
equipment.
* Connect to Google mail to send a message to the new employee that provides 
orientation information. 

There are many ways to call the REST APIs that trigger integration execution, 
including: 

* A web browser page that takes data input and generates the call.
* An application that explicitly calls the REST APIs. 
* Other APIs that call the REST API, for example a webhook. 
