// Module included in the following assemblies:
// as_trigger-integrations-with-api-calls.adoc

[id='workflow-api-providers_{context}']
= General workflow for creating integrations that are triggered by API calls

In {prodname}, after you click *Create Integration*, the workflow for 
creating an API provider integration is as follows.

. On the *Choose a Start Connection* page, click the *API Provider* card.
. On the *Start integration with an API call* page, upload a document that
contains an OpenAPI 2.0 schema or indicate that you want to 
create the schema now. If you upload a document, you can review and
edit it. If you select *Create from scratch*, {prodname} opens an editor
that supports creation of OpenAPI schemas. 
+
[CAUTION]
After you save or publish an API provider integration, you cannot update 
the OpenAPI definition for the REST API service. If you need to edit the OpenAPI 
definition then you must start over and create a new API provider integration. 

. Give the integration a name and save it. 
. On the *Choose operation* page, for each operation that the OpenAPI 
schema defines, create the integration flow for that operation:
.. Click an operation to display the *Add to Integration* page. 
.. Add the connections that are required to implement the selected operation. 
.. Add additional steps that process data between connections. For example, 
in the visual representation of this integration flow, check for data type
mismatch indications. For each data type mismatch, add a step that maps 
data fields. 
.. In the visual representation of this integration flow, click the flow's 
finish connection and specify a return code. When
{prodname} executes this integration flow and reaches this connection, 
{prodname} sends the return code to your API service, which in turn sends
a response to the caller that invoked the API that triggered the integration. 
+
In this release, because an API provider integration is a 
Technology Preview feature, the integration flow always returns the
code that you select. Error handling is not yet supported. 

. Publish the integration. 
+
{prodname} provides the URL where your REST API service is available.

. Optionally, use the `curl` utility to test the integration flows. 
+
For example, suppose that the following `curl` command triggers execution of an integration
flow for the *Get Task by ID* operation. The HTTP `GET` command is the
default request so there is no requirement to specify `GET`. 
The last part of the URL specifies the ID of the task to get:
+
----
curl -k https://i-task-api-proj319352.6a63.fuse-ignite.openshiftapps.com/api/todo/1 
----
