// Module included in the following assemblies:
// as_connecting-to-log.adoc

[id='add-log-connection_{context}']
= Adding a log connection to an integration

To log information about the messages that an integration processes, 
add one or more log connections to the integration. A log connection takes
each input message from the previous step in the flow, sends 
the details that you specify to the integration's log, and passes the message
to the next step in the flow. 

{prodname} provides a log connection that you can add to any number
of flows, and that you can add any number of times to the same
flow. You do not need to create a log connection unless you
inadvertently delete the provided log connection. 

.Prerequisites
* You have chosen to add a log connection rather than a log step to an
integration. 
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure

. Click the *Log* connection. 
+
{prodname} comes with the *Log* connection; you do not need to have
created a log connection yourself. However, if you inadvertently deleted
the provided connection and created a new log connection, then you might 
have given it another name. 

. On the *Choose an Action* page, click *Simple Logger*. 
. Accept the *INFO* log level, or click in the log level input box to
select a different level for sending information to the log. 
+
Each message that an integration handles has a log level field whose value is
`ERROR`, `WARN`, `INFO`, `DEBUG`, or `TRACE`. The table below indicates
the behavior for each log level. 
+
[options="header"]
[cols="1,2"]
|====

|Select this level
|To log information for messages with this log level

|*ERROR*
|`ERROR`

|*WARN*
|`ERROR`, `WARN`

|*INFO*
|`ERROR`, `WARN`, `INFO`

|*DEBUG*
|`ERROR`, `WARN`, `INFO`, `DEBUG`

|*TRACE*
|`ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`

|*OFF*
| No logging. After creating and testing an integration, you might no 
longer need the logging provided by the log connection. To turn it off, 
edit the integration, edit its log connection configuration to select *OFF*, 
and re-publish the integration. 

|====

. Select one or more checkboxes to indicate what information to send
to the log for each message. Choices include: 
+
* *Message ID*
* *Message headers*
* *Message body*

+
If you do not select any checkboxes, then for each logged message, 
{prodname} logs several internal IDs, how long it took to process 
the message, whether there was an error, and an error message if 
there was one. This is comparable to the information that {prodname} 
provides for each integration step, which you can view in the 
*Activity* tab of the integration summary. 

. Click *Done* to add the log connection to the flow. 

.Additional resource

See also xref:viewing-integration-activity-information_monitor[View integration activity].
