// Module included in the following assemblies:
// as_trigger-integrations-with-api-calls.adoc

[id='configure-publish-api-provider-quickstart_{context}']
= Configuring and publishing an example API provider quickstart integration

{prodname} provides an API provider quickstart integration that you can 
import into your {prodname} environment. This quickstart includes 
an OpenAPI document for a task management API. After importing
the quickstart integration, you configure return codes, and then publish
the integration. After you complete the procedure described below,
the Task API integration is running and ready
to be executed. 

The API provider quickstart helps you quickly learn how to configure, publish, and
test an API provider integration. But it is not a real-world example of 
how useful an API provider integration can be. For a real-world
example, suppose that you already
used {prodname} to publish several simple integrations. You could define an OpenAPI
document for triggering execution of those integrations. To do this, you
would edit the flow for each OpenAPI operation to be almost the
same as the simple integrations that you already published. 

.Prerequisites

* {prodname} is open in a browser.

.Procedure

. Import the Task API quickstart integration:
.. Go to 
https://github.com/syndesisio/syndesis-quickstarts/tree/master/api-provider 
and download `TaskAPI-export.zip`. 
.. In {prodname}, in the left navigation panel, click *Integrations*. 
.. In the upper right, click *Import*. 
.. Drag and drop the `TaskAPI-export.zip` file that you downloaded. {prodname} indicates
that it has successfully imported the file. 
.. In the left navigation panel, click *Integrations* to see
an entry for the *Task API* integration that you just imported. The entry
indicates that configuration is required. 

. Configure the Task API integration:
.. Click the *Task API* entry to display the integration summary. 
.. In the upper right, click *Edit Integration* to display a list
of the operations that this API provides. 
.. Update one step in the flow for the *Create Task* operation: 
... In the *POST* entry for the *Create Task* operation, click *Create flow* to display 
the visualization for that flow. 
+
Connections and steps have already been
added to this flow. In the operation flow visualization, 
to view the configuration for a step, click its *Configure* button. 
Click *Cancel* or *Next* to go back to the flow visualization.
When you are done
examining the configuration for one step, click *Configure* for another one to examine it. When you click 
a database connection, you can see the SQL statement that it executes. 
... In the operation flow visualization, on the 
*Provided API Return Path* step, which is the last step in the flow,
click *Configure*. 
You might have to scroll down to see it. 
... Click in the *Return Code* input field and scroll to select 
*201 Created*. 
... Click *Next*.
... In the upper right, click *Save*.

.. Update one step in the flow for the *Delete Task for ID* operation:
... In the *DELETE* entry for the *Delete Task for ID* operation, 
click *Create flow* 
to display the visualization for that flow.  
+
This operation flow has a data mapper step and a connection to the
sample database that is provided with {prodname}. 
In the operation flow visualization, 
click *Configure* on the database connection to view the SQL statement that it executes. 
... Click *Next* or *Cancel*. 
... In the operation flow visualization, on the 
*Provided API Return Path* step, which is the last step in the flow, 
click *Configure*. 
... Click in the *Return Code* input field and scroll to select 
*200 OK*. 
... Click *Next*.
... In the upper right, click *Save*.

.. Update one step in the flow for the *Get Task by ID* operation:

... In the *GET* entry for the *Get Task by ID* operation, 
click *Create flow* 
to display the visualization for that flow. 
+
This operation flow has two data mapper steps, a connection to the
sample database that is provided with {prodname}, and a log step. 

... In the operation flow visualization, click *Configure* on a step
to view its configuration. When you are done examining the configuration, 
click *Next* or *Cancel*. Do this for as many steps as you want. 

... In the operation flow visualization, on the 
*Provided API Return Path* step, which is the last step in the flow, 
click *Configure*. 
... Click in the *Return Code* input field and scroll to select 
*200 OK*. 
... Click *Next*.

. In the upper right, click *Publish*, and then *Save and publish*. 
+
{prodname} displays the summary page for this integration and shows 
publication progress as it assembles, builds, deploys, and 
starts the integration. 

. When the *Task API* integration summary page displays *Running*, 
{prodname} displays the external URL for the Task API service. 
It looks something like this: 
+
`\https://i-task-api-proj319352.6a63.fuse-ignite.openshiftapps.com/api/`
+
This is where {prodname} makes the Task API service available. REST 
API calls specify URLs that start with this base URL.
+
If you are using {prodname} on OpenShift Container 
Platform, if the external URL is not on the integration’s summary page, 
then an administrator has set the `CONTROLLERS_EXPOSE_VIA3SCALE` environment 
variable to true. To test this API provider integration, ask a 3scale 
administrator for guidance. 
