// This module is included in these assemblies:
// as_monitoring-integrations.adoc

[id='viewing-integration-activity-information_{context}']
= Viewing information about an integration's activity

{prodname} provides activity information for each execution of an integration.
This information is part of the integration's log. 
For each step in a flow, {prodname} provides:

* The date and time that the step was executed
* How long it took to execute the step
* Whether execution was successful
* The error message if execution was not successful
 
At any time, you can view this information.

.Prerequisites
* There is or was a running integration for which you want to view activity
information. 
* This integration has been executed at least once. 

.Procedure

. In the left panel, click *Integrations*.
. At the right of the entry for the integration for which you want to view activity
information, click *View*.
. In the integration's summary page, click the *Activity* tab.
. Optionally, enter date and/or keyword filters to limit the executions
listed.
. Click the integration execution for which you want to view activity information.

.Additional resources
* To obtain additional information between any two steps, you can
add a log step to the
integration. A log step provides information about each message it
receives and can provide custom text that you specify.
If you add a log step, then it appears as one of the integration's
steps when you expand the integration execution that you want to view activity
information for. You view {prodname} information for a log step in the 
same way that you view {prodname} information for any other step. See
link:{LinkFuseOnlineIntegrationGuide}#add-log-step_create[Logging information about integration execution].
