// This assembly is included in the following assemblies:
// as_customizing.adoc

:context: custom
[id='adding-api-connectors_{context}']
= Adding and managing API client connectors
:context: add-client-connector

{prodname} can create these API client connectors:

* A REST API client connector from an OpenAPI
document. For information about the content of the OpenAPI document, see
link:{LinkSyndesisIntegrationGuide}#developing-rest-api-client-connectors_custom[Developing REST API client connectors]. 

* A SOAP API client connector from a WSDL file.
+
IMPORTANT: The SOAP API client connector is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production.These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.For more information about the support scope of Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/

The following topics provide information and instructions for adding
and managing REST API client connectors:

* xref:creating-rest-api-connectors_{context}[]
* xref:creating-soap-api-connectors_{context}[]
* xref:updating-api-connectors_{context}[]
* xref:deleting-api-connectors_{context}[]

After you create an API client connector, for details about using that connector, see link:{LinkSyndesisConnectorGuide}#connecting-to-api-clients_connectors[{NameOfSyndesisConnectorGuide}, Connecting to API clients]. 

include::../../modules/integrating-applications/proc-creating-rest-api-connectors.adoc[leveloffset=+1]

include::../../modules/integrating-applications/proc-creating-soap-api-connectors.adoc[leveloffset=+1]

include::../../modules/integrating-applications/proc-updating-api-connectors.adoc[leveloffset=+1]

include::../../modules/integrating-applications/proc-deleting-api-connectors.adoc[leveloffset=+1]

:context: custom
