@startuml
' tag::uml[]

component [rest] #lightgreen
component [meta] #lightgreen
component [integration] #lightblue

[common]
[connector] --> [common]
[connector] --> [integration]

[extension] --> [common]

[integration] --> [common]
[integration] --> [extension]

[rest] --> [common]
[rest] --> [extension]
[rest] --> [integration]

[meta] --> [common]
[meta] -up-> [connector]

' end::uml[]
@enduml
