@startuml
' tag::uml[]

package "Design" {
  [Rest]
  [Meta]
}

package "Runtime" {
  [Integration]
}

[Common]
[Connector] --> [Common]
[Extension] --> [Common]

[Integration] --> [Common]
[Integration] --> [Extension]
[Integration] --> [Connector]

[Rest] --> [Common]
[Rest] --> [Extension]
[Rest] --> [Integration]

[Meta] --> [Common]
[Meta] --> [Connector]

' end::uml[]
@enduml
