[[dev-local]]
== Local Development

If you'd like to get a local development environment up and running, for both the UI and REST API, this is how you'd do it.

*Tips*

- Build on branch, not master.
- Callback URL Example: https://syndesis.192.168.64.29.nip.io/api/v1/credentials/callback

---

=== Requirements

You can follow these steps if it's your first time setting up Syndesis, or if you want a fresh local installation to replace an existing one. Some environment-specific instructions may be available below as well.

1. Make sure you have installed https://nodejs.org/en/download/[node] version >= 6.x.x and https://yarnpkg.com/en/docs/install[Yarn] version >= 0.18.1.

2. Get a developer deployment of Syndesis running in a Minishift environment as described in the https://syndesis.io/quickstart/[Syndesis Quickstart].  Most are specific to your environment, so follow the sections below for a quick setup. The general instructions are:
- Install a hypervisor for Minishift.
- Install Minishift.
- Install the OpenShift CLI.
- Make sure it's in your `$PATH`



*macOS*

If you'll be using the Homebrew method, you'll obviously need to have Homebrew installed. Then, to install the hypervisor for Minishift and Minishift itself:

```
$ brew install docker-machine-driver-xhyve
$ brew cask install minishift
```

Finally, to install the OpenShift CLI, we recommend using Homebrew: `brew install openshift-cli`

*Linux & Windows*

- https://docs.openshift.org/latest/minishift/getting-started/installing.html#install-prerequisites[Install a hypervisor for Minishift]. For macOS, we recommend using the Docker xhyve plugin https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html#xhyve-driver-install[here], which can be installed using Homebrew.
- https://docs.openshift.org/latest/minishift/getting-started/installing.html#installing-instructions[Install Minishift]. For macOS, we recommend you use the Homebrew method.

Please note that you need to have the `oc` binary available in your `PATH`. To do that, see here: https://docs.openshift.org/latest/cli_reference/get_started_cli.html


---

=== First-Time Setup

The goal here is to download the project to your laptop/PC, and to install Minishift, the VM that contains OpenShift.

```
$ git clone https://github.com/syndesisio/syndesis.git # or own fork
$ cd syndesis
$ syndesis minishift --full-reset
```


---

=== Running without Kubernetes/OpenShift

For some development tasks you can run Syndesis without running on a Kubernetes/OpenShift cluster. You won't be able to publish integrations, see activities or gather metrics, or any other functionality that requires a running cluster. This is best suited for quick turnaround development of backend APIs together with UI features. You'll need three components running the Syndesis backend, the PostgreSQL database it uses and the UI.

Start by running a PostgreSQL database in a Docker container:

```
$ docker run -d --rm -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=syndesis postgres
```

NOTE: the `--rm` option will remove the container once done and all the stored data in the database with it, if you wish to keep the data omit that option

Next run the Syndesis backend, this step requires that you have downloaded all the dependencies and built the backend:

```
$ syndesis build -f -c --backend # to download dependencies and build the backend
$ (cd app && ./mvnw -f server/runtime spring-boot:run)
```

The backend is started once you see the a line containing this in the output:
```
Started Application in 28.9 seconds (JVM running for 29.615)
```

After that UI can be started by running (in two separate terminal sessions):

```
$ (cd app/ui-react && watch:packages)
$ (cd app/ui-react && BACKEND=http://localhost:8080 yarn watch:app:proxy)
```

You can now access a running instance at https://localhost:3000[https://localhost:3000].

=== Day-to-Day

This uses an existing Minishift instance.

*NOTE:* If you already followed the First-Time Setup above, you do not need to follow this. The Minishift VM will already have been started. Simply skip to the

*Get the Latest Changes*

```
$ git checkout master
$ git pull upstream master
$ git checkout <branch>
$ git rebase master
```

*Start of the Day*
Make sure Minishift is running.

```
$ minishift status
```

Which should look like:

```
Minishift:  Running
Profile:    minishift
OpenShift:  Running (openshift v3.6.0+c4dd4cf)
DiskUsage:  11% of 17.9G
```

If it isn't, start it with:

```
$ minishift start
```

*Login into and Set up OpenShift*

This step is required regardless of whether it's a first-time install or not. It logs you in and points OpenShift to use Minishift resources.

```
$ oc login -u developer
$ eval $(minishift oc-env)
$ eval $(minishift docker-env)
```

The eval's set a number of environment variables, like change the `$PATH` and `$DOCKER_HOST`, so each time you do a Syndesis build it's good to make sure those are invoked.

*End of the Day*

```
$ minishift stop
```

*Start the UI App & Open in the Browser*

```
$ yarn start:minishift
$ open https://$(oc get routes syndesis --template "{{.spec.host}}")
```

*Resetting the Database*

This step is optional. This command expects Minishift to be running already. It's the `-i docker` that determines the workflow, for Roland it seems to work without that though.

It would clean the database if we increase the schema version, if we don't it remains the same.

```
$ syndesis build -m rest -f -i docker -k
```

Alternatively, you can use the REST API Endpoint: /api/v1/test-support/reset-db

*Connecting to the Database*

You can also port forward the DB's port using `oc port-forward` and then connect to the database using a tool like https://www.pgadmin.org/download/[pgadmin] to view the data.  First get the DB pod's name either from `oc get pods` or from the OpenShift console.  Then use the following command:

```
$ oc port-forward <db pod name> 5432:5432
```

Now start pgadmin and add a new DB server, use `localhost` for the `host` setting.  For the username and password look on the DB pod's `Environment` page in the OpenShift console.

In pgadmin you can see the table by navigating into the tree under `Server Groups > Servers > syndesis > Databases > syndesis > Schemas > public > Tables > jsondb`.  Right click, and then go to `View Data > View All Rows`.
