// Module included in the following assemblies:
// as_amq2api-intro.adoc

[id='amq2api-confirm-works_{context}']
= Confirming that the AMQ to REST API integration works

After you create and publish the AMQ to REST API sample integration, 
you can confirm that it works as defined. 

.Prerequisite
In {prodname}, in the list of integrations, 
*Running* appears next to the AMQ to REST API 
integration that you created and deployed. 

.Procedure

. In a new browser window, go to the To Do app display by
inserting `*todo-*` in front of the URL
for your {prodname} environment. For example: 
`\https://todo-app-proj761432.6a63.fuse-ignite.openshiftapps.com/`.
. In the To Do app display, click *Show JMS Form* to display an
input box that contains an XML message.
. Click *Send JMS Message* to send that message
to the Red Hat AMQ broker in your OpenShift project.
+
Successful execution returns a task from the To Do app client API. The task
identifies the ID of the damaged item and the contact information for its
vendor. If the task does not appear in a moment or two, try reloading the
page. 
. Edit the XML message to specify two damaged items:
.. Click *Show JMS Form* to display the message input box again.
.. In the XML message, change the entry for the undamaged item to
specify `damaged="true"`.
.. Click *Send JMS Message*. The To Do app client API returns a new
task that contains IDs for two damaged items and contact information for
the two vendors.
. Edit the XML message to specify an ID that you make up:
.. Click *Show JMS Form*.
.. In the XML message, for the item that has `damaged="true"`, change the item
ID, for example, to `1234`.
.. Click *Send JMS Message*. The To Do app client API returns a new
task with the item ID that you just entered.

. Optionally, view the integration log to troubleshoot an
unexpected result or to learn more about integration execution: 

.. In {prodname}, in the left panel, click *Integrations*.
.. View the entry for your AMQ to REST API integration.
.. In the integration's summary page, click the *Activity* tab.
.. Click the integration execution for which you want to view activity information.
