// Module included in the following assemblies:
// as_amq2api-intro.adoc

[id='amq2api-create-rest-api-connector_{context}']
= Creating a REST API connector

{prodname} can create connectors for REST APIs
that support Hypertext Transfer Protocol (HTTP)/1.0 or HTTP/1.1.
To do this, {prodname} requires a valid
OpenAPI 2.0 document that describes a REST API that you want to connect to.

Your {prodname} environment provides the To Do app, which has a REST API
for accessing a database that contains tasks. Your environment also provides
an OpenAPI (Swagger) document for this API.

.Procedure

. Identify the URL for your {prodname} environment's copy of the
OpenAPI document:
.. In the {prodname} navigation panel, click *Home*.
.. Copy the URL into a text editor.
.. At the beginning of the URL, insert `*todo-*`.
.. At the end of the URL, add `*swagger.json*`.
.. Use the `http` scheme instead of `https`.

+
The result is something like this:
`\http://todo-app-proj217402.6a63.fuse-ignite.openshiftapps.com/swagger.json`

+
[NOTE]
Specification of `http` rather than `https` avoids a runtime error 
if TLS certificates are not valid.  In production 
environments, ensure that valid certificates are in place, 
and always specify secure URLs (`https`) to obtain an OpenAPI document. 


. In the {prodname} navigation panel, click *Customizations* > *API Client Connectors*.
. Click *Create API Connector*.
. Select *Use a URL*.
. In the input box, paste the URL for your OpenAPI document and
click *Next*.
. On the *Review Actions* page, click *Next*. If you see
a warning, you can ignore it.
. Click *Next* again to accept *HTTP Basic Authentication*.
. On the *Review/Edit Connector Details* page: 
.. If you want to, you can
change the values in the *Name* and *Description* fields.
.. In the *Host* field, enter the name of the service host, 
which is something like this: 
`\https://todo-app-proj217402.6a63.fuse-ignite.openshiftapps.com`.
.. In the *Base URL* field, enter the part of the URL that follows the 
host name in service requests: `/api`.
 
. Click *Save*.
+
{prodname} displays the *API Client Connectors*. There is a new entry for
the *Todo App API* that you just created.
