// Module included in the following assemblies:
// as_amq2api-intro.adoc

[id='amq2api-create-rest-api-connection_{context}']
= Creating a REST API connection

In an integration, before you can connect to a REST API, you create a REST API 
client connector and then use that connector to create a connection. 
You already created a REST API connector for the To Do app. Follow the 
instructions here to use that connector to create a connection to the 
To Do app REST API. 

.Prerequisite
* You created the Todo App REST API connector. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
available connectors.
. Click the *Todo App API* connector that you just created.
+
{prodname} populates the *Host* and *Base Path* fields from the
OpenAPI document that you provided when you created the connector.
. In the *Username* field, enter any value. For this sample integration,
user name and password values are required but they are not used.
. In the *Password* field, enter any value. 
. Click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Todo App API Client*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example, enter
`*Connection to the provided Todo app REST API.*`
. Click *Save* to see that the connection you
created is now available.
