// Module included in the following assemblies:
// as_sf2db-intro.adoc

[id='sf2db-confirm-working_{context}']
= Confirming that the Salesforce to database integration works

To confirm that the Salesforce to database integration is working, 
create a new lead in Salesforce and then open the web app that 
{prodname} provides for viewing updates to the sample database. 

.Prerequisites

* In {prodname}, *Running* appears next to the name that you specified
for the Salesforce to database sample integration when you published it.
* You can access your Salesforce account. 

.Procedure

. In the left panel, click *Integrations*.
. If necessary, wait until your sample integration is a *Running* integration.
 If you used the example name, you would see that 
*Salesforce to Database Sample Integration* is *Running*.

. In your Salesforce installation, create a new lead. Be
sure to enter data
in the fields that you mapped: *Company*, *Email*, *FirstName*,
*LastName*, *LeadSource*, *Status*, *Phone*, and *Rating*.
. In a new browser window, insert `*todo-*` in front of the URL
for your {prodname} environment. For example: 
`\https://todo-app-proj761432.6a63.fuse-ignite.openshiftapps.com/`.
+
Your {prodname} environment provides the To Do app, which has a 
REST API for accessing a database that contains tasks. In the AMQ to REST 
API sample integration tutorial, there are instructions for uploading an
OpenAPI (Swagger) document for the To Do app to create an API client connector. 

. In the *To Do App* display, you should see a notification that a new 
lead was created in the database. 

. Optionally, view the integration log to troubleshoot an
unexpected result or to learn more about integration execution: 

.. In {prodname}, in the left panel, click *Integrations*.
.. View your Salesforce to database integration.
.. In the integration's summary page, click the *Activity* tab.
.. Click the integration execution for which you want to view activity information.
