// Module included in the following assemblies:
// as_t2sf-create-integration.adoc

[id='t2sf-choose-start-connection_{context}']
= Choosing the start connection

In {prodname}, to create the sample Twitter to Salesforce integration, 
the first task is to choose the start connection. 

.Prerequisites

* You created a Twitter connection. 

.Procedure

. On the left, click *Integrations*.
. In the upper right, click *Create Integration*.
. On the *Choose a connection* page, click the Twitter connection
that you created. If you gave it the example name, you would
click *Twitter Connect 1*.
When the integration starts, it uses the credentials defined in
this connection to connect to Twitter.
. On the *Choose an action* page, to the right of the *Mention*
action entry, click *Select*. 
. On the *Configure the action* page, click *Next*. No configuration is required. 

.Next step
When the integration is running, after 
connecting to Twitter, the integration monitors Twitter for mentions
that include your Twitter screen name. A match triggers the
next step in the integration. However, before you add steps that operate
on data between connections,
you choose the connection that the integration uses to finish its work.
