// Module included in the following assemblies:
// as_amq2api-create-integration.adoc

[id='amq2api-choose-start-connection_{context}']
= Choosing the start connection

In {prodname}, to create the sample AMQ to REST API sample integration,
the first task is to choose the start connection. 

.Prerequisites
* You started the provided Red Hat AMQ broker. 
* You created a connection to that message broker. 

.Procedure

. In {prodname}, on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a connection* page, click your
AMQ connection. If you specified the example name,
you would click *Red Hat AMQ Broker 1*.
. On the *Choose an action* page, select the *Subscribe for messages* action
to receive messages from the queue you specify.
. In the *Destination name* field, enter `*inventoryReceived*` for
the name of the queue to obtain data from.
. Click in the *Destination type* field and select *Queue*.
. Leave the other fields blank.
. Click *Next*. {prodname} prompts you to specify the output data type. 
This is not needed for this sample integration. 
. Click *Next* to add the start connection to the integration.

.Next step
When the integration is running, after connecting to Red Hat AMQ, the integration watches for
messages on the `inventoryReceived` queue. When a message is available,
the integration passes it to the *Damage Reporter* step.
However, before you can add that step to the integration, you must choose the
integration's finish connection.
