apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndeses.syndesis.io
spec:
  group: syndesis.io
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndeses
    singular: syndesis
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Syndesis is the Schema for the syndeses API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SyndesisSpec defines the desired state of Syndesis
          properties:
            addons:
              description: Optional add on features that can be enabled.
              properties:
                camelk:
                  properties:
                    enabled:
                      type: boolean
                  type: object
                dv:
                  properties:
                    enabled:
                      type: boolean
                    resources:
                      type: string
                  type: object
                jaeger:
                  properties:
                    enabled:
                      type: boolean
                    samplerParam:
                      type: string
                    samplerType:
                      type: string
                  type: object
                knative:
                  properties:
                    enabled:
                      type: boolean
                  type: object
                ops:
                  properties:
                    enabled:
                      type: boolean
                  type: object
                publicApi:
                  properties:
                    disable-sar-check:
                      description: if set to true, then any authenticated user can
                        access the API. otherwise the user needs access to get pods
                        against the SarNamespace
                      type: boolean
                    enabled:
                      type: boolean
                    routeHostname:
                      description: Set RouteHostname to the hostname of the exposed
                        syndesis Public API.
                      type: string
                  type: object
                todo:
                  properties:
                    enabled:
                      type: boolean
                  type: object
              type: object
            backup:
              description: Schedule backup
              properties:
                schedule:
                  description: Set schedule for backup cronjob
                  enum:
                  - hourly
                  - daily
                  - midnight
                  - weekly
                  - monthly
                  - yearly
                  - every 3m
                  type: string
              type: object
            components:
              description: Components is used to configure all the core components
                of Syndesis
              properties:
                database:
                  properties:
                    externalDbURL:
                      description: If specified, use an external database instead
                        of the installed by syndesis
                      type: string
                    name:
                      description: Name of the PostgreSQL database accessed
                      type: string
                    resources:
                      description: Resource provision requirements of the database
                      properties:
                        volumeAccessMode:
                          enum:
                          - ReadWriteOnce
                          - ReadOnlyMany
                          - ReadWriteMany
                          type: string
                        volumeCapacity:
                          type: string
                        volumeLabels:
                          additionalProperties:
                            type: string
                          type: object
                        volumeName:
                          type: string
                        volumeStorageClass:
                          type: string
                      type: string
                    user:
                      description: Username for PostgreSQL user that will be used
                        for accessing the database
                      type: string
                  type: object
                grafana:
                  properties:
                    resources:
                      type: string
                  type: object
                meta:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: string
                  type: object
                oauth:
                  properties:
                    disableSarCheck:
                      description: Enable or disable SAR checks all together
                      type: boolean
                    sarNamespace:
                      description: The user needs to have permissions to at least
                        get a list of pods in the given project in order to be granted
                        access to the Syndesis installation
                      type: string
                  type: object
                prometheus:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: string
                    rules:
                      type: string
                  type: object
                server:
                  properties:
                    features:
                      properties:
                        deployIntegrations:
                          description: Whether we deploy integrations
                          type: boolean
                        integrationLimit:
                          description: Maximum number of integrations single user
                            can create
                          type: integer
                        integrationStateCheckInterval:
                          description: Interval for checking the state of the integrations
                          type: integer
                        managementUrlFor3scale:
                          description: 3scale management URL
                          type: string
                        mavenRepositories:
                          additionalProperties:
                            type: string
                          description: Set repositories for maven
                          type: object
                      type: object
                    resources:
                      type: string
                  type: object
                upgrade:
                  properties:
                    resources:
                      properties:
                        volumeCapacity:
                          type: string
                      type: object
                  type: object
              type: object
            demoData:
              description: Enable SampleDB and demo data for Syndesis
              type: boolean
            imageStreamNamespace:
              description: Namespace where syndesis docker images are located and
                the operator should look after them
              type: string
            routeHostname:
              description: The external hostname to access Syndesis
              type: string
          type: object
        status:
          description: SyndesisStatus defines the observed state of Syndesis
          properties:
            backup:
              properties:
                next:
                  description: When is the next backup planned
                  type: string
                previous:
                  description: When was the previous backup executed
                  type: string
              type: object
            description:
              type: string
            forceUpgrade:
              type: boolean
            lastUpgradeFailure:
              format: date-time
              type: string
            phase:
              type: string
            reason:
              type: string
            targetVersion:
              type: string
            upgradeAttempts:
              type: integer
            version:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
