package io.syndesis.connector.sql.stored.springboot;

import javax.annotation.Generated;
import javax.sql.DataSource;

/**
 * SQL Stored Procedure Connector to invoke a SQL Stored Procedure
 * 
 * Generated by camel-package-maven-plugin - do not edit this file!
 */
@Generated("org.apache.camel.maven.connector.SpringBootAutoConfigurationMojo")
public class SqlStoredConnectorConnectorConfigurationCommon {

    /**
     * Sets the DataSource to use to communicate with the database.
     */
    private DataSource dataSource;
    /**
     * Sets the StoredProcedure template to perform
     */
    private String template;
    /**
     * DB User Name
     */
    private String user;
    /**
     * DB User Password
     */
    private String password;
    /**
     * DB URL
     */
    private String url;
    /**
     * DB Schema
     */
    private String schema;
    /**
     * DB Catalog
     */
    private String catalog;
    /**
     * Stored Procedure Name
     */
    private String procedureName;

    public DataSource getDataSource() {
        return dataSource;
    }

    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSchema() {
        return schema;
    }

    public void setSchema(String schema) {
        this.schema = schema;
    }

    public String getCatalog() {
        return catalog;
    }

    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    public String getProcedureName() {
        return procedureName;
    }

    public void setProcedureName(String procedureName) {
        this.procedureName = procedureName;
    }
}