[id='developing-extensions']
= Developing extensions

If Syndesis does not provide a feature that you need, an expert developer can code an extension that lets you integrate data the way you need.

== Packaging

An extension is a collections of classes, dependencies and resources packaged as a jar file structured as follow:

[source]
----
extension.jar
|
+- META-INF
|  |
|  +- syndesis
|     |
|     +- syndesis-extension-definition.json <1>
|
+- mycompany
|  |
|  +-project
|    |
|    +-YourClasses.class <2>
|
+- lib <3>
  |
  +-dependency1.jar
  |
  +-dependency2.jar
----
<1> extension definition.P
<2> extension classes.
<3> additional dependencies.

[WARNING]
====
As the extension is loaded using spring-boot facilities, the extension should be packages according to spring-boot's executable jar format so the ZipEntry for a nested jar must be saved by using the ZipEntry.STORED method.
====

=== Definition

The _syndesis-extension-definition.json_ file contains the definition of the extension like name, description well as a list of actions it supports and the dependencies it needs.

A definition file has the following general layout:

[source,json]
----
{
  "schemaVersion": "v1",
  "name": "",
  "description": "",
  "version": "",
  "extensionId": "",
  "extensionType": "",
  "properties": {
  },
  "actions": [
  ],
  "dependencies": [
  ],
}
----

- **schemaVersion** defines the version of the extension definition scheme, this is used by Syndesis back-end to determine how to map the definition to the internal model and allows extensions developed against an old version of Syndesis to be deployed on newer versions.
- **extensionId** defines an unique id for the extension, this should be unique at least across a Syndesis instance
- **extensionType** defines what Syndesis should expect the extension to provide, as of version 1.3 the following types are supported:
* Steps
* Connectors
* Libraries
- **properties** defines the global configuration options supported by the extension
+
[source,json]
----
"propertyName": {
  "deprecated": true|false,
  "description": "",
  "displayName": "",
  "group": "",
  "kind": "",
  "label": "",
  "required": true|false,
  "secret": true|false,
  "javaType": "",
  "type": "",
  "defaultValue": "",
  "enum": {
  }
}
----
+
IMPORTANT: properties are taken into account only for extensions with type _Connectors_
- **actions** defines the steps the extension contributes to Syndesis
+
[source,json]
----
{
    "id": "", <1>
    "name": "", <2>
    "description": "", <3>
    "actionType": "step|connector", <4>
    "descriptor": { <5>
    }
}
----
<1> An unique id for the action.
<2> The action name shown on syndesis.
<3> The action descriptor shown on syndesis
<4> The action type (step,connector)
<5> The action descriptor
+
[IMPORTANT]
====
Actions are taken into account only for extension with type _Connectors_ and _Steps_.
====

- **dependencies** defines the dependencies this extension requires Syndesis to provide.
+
A dependency is defined as follow:
+
[source,json]
----
{
  "type": "MAVEN", <1>
  "id"   : "org.apache.camel:camel-telegram:jar:2.21.0" <2>
}
----
<1> the type of dependency (MAVEN,EXTENSION,EXTENSION_TAG)
<2> the dependency id, for maven dependencies it is a maven gav


=== Maven Support

The _extension-maven-plugin_ provides Syndesis Extension support to maven letting you generate the extension definition and package it as proper spring-boot module.

[source,xml]
----
<plugin>
    <groupId>io.syndesis.extension</groupId>
    <artifactId>extension-maven-plugin</artifactId>
    <version>${syndesis.version}</version>
    <executions>
        <execution>
        <goals>
            <goal>generate-metadata</goal> <!--1-->
            <goal>repackage-extension</goal> <!--2-->
        </goals>
        </execution>
    </executions>
</plugin>
----
<1> generate extension definition.
<2> package extension.

The _extension-maven-plugin_ define the following goals:

* **generate-metadata** that generates the Syndesis extension definition according to the following rules:

  - includes info from `META-INF/syndesis/syndesis-extension-definition.json` to generate the final descriptor.
  - information such as _id_, _name_, _description_ and _version_ are computed from the project if not explicit configured through plugin configuration or using `META-INF/syndesis/syndesis-extension-definition.json`
  - the dependencies list is built including dependencies provided with scope _provided_ and that are managed through the _extension-bom_

-
* **repackage-extesion** that packages the Syndesis extension definition according ot the following rules:

  - dependencies and related transitive ones not managed through the _extension-bom_ are included in the _lib_ folder of the repackaged jar
  - dependencies with scope _system_ are added to the _lib_ folder of the repackaged jar for extension of type _Libaries_

Assuming we have the following pom:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.company</groupId>
  <artifactId>my-extension</artifactId>
  <version>1.0.0</version>
  <name>MyExtension</name>
  <description>A Sample Extension</description>
  <packaging>jar</packaging>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.syndesis.extension</groupId>
        <artifactId>extension-bom</artifactId>
        <version>1.3.10</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.syndesis.extension</groupId>
      <artifactId>extension-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.github.lalyos</groupId>
      <artifactId>jfiglet</artifactId>
      <version>0.0.8</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>io.syndesis.extension</groupId>
        <artifactId>extension-maven-plugin</artifactId>
        <version>1.3.10</version>
        <executions>
          <execution>
            <goals>
              <goal>generate-metadata</goal>
              <goal>repackage-extension</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
----

Then the generated extension descriptor would be:

[source,json]
----
{
  "name": "MyExtension",
  "description": "A Sample Extension",
  "extensionId": "com.company:my-extension",
  "version": "1.0.0",
  "dependencies": [ {
    "type": "MAVEN",
    "id": "io.syndesis.extension:extension-api:jar:1.3.10"
  } ],
  "extensionType": "Libraries",
  "schemaVersion": "v1"
}
----

And then generated archive would be:

[source]
----
my-extension-1.0.0.jar
|
+- lib
|  |
|  + jfiglet-0.0.8.jar
|
+- META-INF
  |
  +- MANIFEST.MF
     |
     +- syndesis
        |
        +- syndesis-extension-definition.json
----

== Developing Step extensions

Syndesis supports different ways to provide custom steps:

- Using Camel routes created with xml fragments
- Using Camel routes created with RouteBuilder
- Using Camel beans
- Using Syndesis Step API


[NOTE]
====
Syndesis provide a set of custom java annotation that used in conjunction with the syndesis-extension-pluing can automatically add actions definitions in the extension descriptor for extension coded using Java. To enable annotation processing it is required to add the following dependency to your maven project:

[source,xml]
----
<dependency>
  <groupId>io.syndesis.extension</groupId>
  <artifactId>extension-annotation-processor</artifactId>
  <optional>true</optional>
</dependency>
----
====

=== Using xml route fragments

An action developed as xml fragment is just a Caml route with an input such as `direct` which is invoked by the Syndesis runtime like any other route.

As example, you may want to create a step that logs the body of a message with an optional prefix, this can be done with a route fragment like:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns="http://camel.apache.org/schema/spring"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="
      http://camel.apache.org/schema/spring
      http://camel.apache.org/schema/spring/camel-spring.xsd">

  <route id="log-body-with-prefix">
    <from uri="direct:log"/>
    <choice>
      <when>
        <simple>${header.prefix} != ''</simple>
        <log message="${header.prefix} ${body}"/>
      </when>
      <otherwise>
        <log message="Output ${body}"/>
      </otherwise>
    </choice>
  </route>

</routes>
----

As we do not _yet_ have a way to automatically generate the related action defintion, you'd need to create a descriptor template `src/main/resources/META-INF/syndesis/syndesis-extension-definition.json` with the following content:

[source,json]
----
{
  "actionType": "step",
  "id": "log-body-with-prefix",
  "name": "Log body with prefix",
  "description": "A simple body log with a prefix",
  "descriptor": {
    "kind": "ENDPOINT", <1>
    "entrypoint": "direct:log", <2>
    "resource": "classpath:log-body-action.xml", <3>
    "inputDataShape": {
      "kind": "none"
    },
    "outputDataShape": {
      "kind": "none"
    },
  "propertyDefinitionSteps": [ {
    "description": "extension-properties",
    "name": "extension-properties",
    "properties": { <4>
      "prefix": {
        "componentProperty": false,
        "deprecated": false,
        "description": "The Log body prefix message",
        "displayName": "Log Prefix",
        "javaType": "String",
        "kind": "parameter",
        "required": false,
        "secret": false,
        "type": "string"
      }
    }
  } ]
  }
}
----
<1> the type of action is set to `ENDPOINT` as the runtime should invoke a Camel endpoint to execute this action/step
<2> the Camel endpoint to invoke which is the `from` of our route
<3> the location of the xml fragment
<4> the propertis this step/action exposes to the user, each value set by the user is set to a message header with the same name as the property

[WARNING]
====
Syndesis does not support full Camel XML configuration but only the <routes> tag.
====

=== Using RouteBuilder

An action developed as route with the support of RouteBuilder is just a Camel route with an input such as `direct` which is invoked by the Syndesis runtime like any other route.

To implement the same example as the one used to show how to use xml fragments, you can write something like:

[source,java]
----
import org.apache.camel.builder.RouteBuilder;

import io.syndesis.extension.api.annotations.Action;
import io.syndesis.extension.api.annotations.ConfigurationProperty;

@Action( // <1>
    id = "log-body-with-prefix",
    name = "Log body with prefix",
    description = "A simple body log with a prefix",
    entrypoint = "direct:log")
public class LogAction extends RouteBuilder {
    @ConfigurationProperty( // <2>
        name = "prefix",
        description = "The Log body prefix message",
        displayName = "Log Prefix",
        type = "string")
    private String prefix;

    @Override
    public void configure() throws Exception {
        from("direct::start") // <3>
            .choice()
                .when(simple("${header.prefix} != ''"))
                    .log("${header.prefix} ${body}")
                .otherwise()
                    .log("Output ${body}")
            .endChoice();
    }
}
----
<1> the action definition
<2> the property definition
<3> the action implementation

As we are using java and Syndesis annotations we can leverage the extension-maven-plugin to automatically generate the action definition which will look like:

[source,json]
----
{
  "id": "log-body-with-prefix",
  "name": "Log body with prefix",
  "description": "A simple body log with a prefix",
  "descriptor": {
    "kind": "ENDPOINT", <1>
    "entrypoint": "direct:log", <2>
    "resource": "class:io.syndesis.extension.log.LogAction", <3>
    "inputDataShape": {
      "kind": "none"
    },
    "outputDataShape": {
      "kind": "none"
    },
    "propertyDefinitionSteps": [ {
      "description": "extension-properties",
      "name": "extension-properties",
      "properties": { <4>
        "prefix": {
          "componentProperty": false,
          "deprecated": false,
          "description": "The Log body prefix message",
          "displayName": "Log Prefix",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": false,
          "secret": false,
          "type": "string",
          "raw": false
        }
      }
    } ]
  },
  "actionType": "step"
}
----
<1> the type of action is set to `ENDPOINT` as the runtime should invoke a Camel endpoint to execute this action/step
<2> the Camel endpoint to invoke which is the `from` of our route
<3> the class that implements `RoutesBuilder`
<4> the properties this step/action exposes to the user, each value set by the user is set to a message header with the same name as the property

=== Using beans

An action developed as bean is just a Camel bean processor.

To implement the same example as the one used to show how to use xml fragments, you can write something like:

[source,java]
----
import org.apache.camel.Body;
import org.apache.camel.Handler;
import org.apache.camel.Header;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.syndesis.extension.api.annotations.Action;
import io.syndesis.extension.api.annotations.ConfigurationProperty;

@Action(
    id = "log-body-with-prefix",
    name = "Log body with prefix",
    description = "A simple body log with a prefix")
public class LogAction  {
    private static final Logger LOGGER = LoggerFactory.getLogger(LogAction.class);

    @ConfigurationProperty(
        name = "prefix",
        description = "The Log body prefix message",
        displayName = "Log Prefix",
        type = "string")
    private String prefix;

    @Handler // <1>
    public void process(@Header("prefix") String prefix, @Body Object body) {
        if (prefix == null) {
            LOGGER.info("Output {}", body);
        } else {
            LOGGER.info("{} {}", prefix, body);
        }
    }
}
----
<1> the function that implement the action.

As we are using java and Syndesis annotations we can leverage the extension-maven-plugin to automatically generate the action definition which will look like:

[source,json]
----
{
  "id": "log-body-with-prefix",
  "name": "Log body with prefix",
  "description": "A simple body log with a prefix",
  "descriptor": {
    "kind": "BEAN", <1>
    "entrypoint": "io.syndesis.extension.log.LogAction::process", <2>
    "inputDataShape": {
      "kind": "none"
    },
    "outputDataShape": {
      "kind": "none"
    },
    "propertyDefinitionSteps": [ {
      "description": "extension-properties",
      "name": "extension-properties",
      "properties": {
        "prefix": { <3>
          "componentProperty": false,
          "deprecated": false,
          "description": "The Log body prefix message",
          "displayName": "Log Prefix",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": false,
          "secret": false,
          "type": "string",
          "raw": false
        }
      }
    } ]
  },
  "actionType": "step"
}
----
<1> the type of action is set to `BEAN` as the runtime should invoke a Camel bean processor to execute this action/step
<2> the Camel bean to invoke
<3> the properties this step/action exposes to the user, each value set by the user is set to a message header with the same name as the property

As we are using beans we can also decide to inject user properties to the bean instead of retrieving it from the exchange header by implementing getters and setters for the properties we want to get injected. Our action implementation would look like:

[source,java]
----
import org.apache.camel.Body;
import org.apache.camel.Handler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.syndesis.extension.api.annotations.Action;
import io.syndesis.extension.api.annotations.ConfigurationProperty;

@Action(
    id = "log-body-with-prefix",
    name = "Log body with prefix",
    description = "A simple body log with a prefix")
public class LogAction  {
    private static final Logger LOGGER = LoggerFactory.getLogger(LogAction.class);

    @ConfigurationProperty(
        name = "prefix",
        description = "The Log body prefix message",
        displayName = "Log Prefix",
        type = "string")
    private String prefix;

    public void setPrefix(String prefix) { // <1>
        this.prefix = prefix;
    }

    public String getPrefix() { // <2>
        return prefix;
    }

    @Handler
    public void process(@Body Object body) {
        if (this.prefix == null) {
            LOGGER.info("Output {}", body);
        } else {
            LOGGER.info("{} {}", this.prefix, body);
        }
    }
}
----
<1> property setter
<2> property getter


=== Using Spring Boot

Action can be developed using Spring Boot in a way very similar to what shown in the section above about developing step extension using the RouteBuilder as Spring Boot is used as facility to register a RouteBuilder to the camle contexts.

To implement the same example as the one used to show how to use xml fragments, you can write something like:

[source,java]
----
import io.syndesis.extension.api.annotations.Action;
import io.syndesis.extension.api.annotations.ConfigurationProperty;
import org.apache.camel.builder.RouteBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class ActionsConfiguration {

    @Action( // <1>
        id = "log-body-with-prefix",
        name = "Log body with prefix",
        description = "A simple body log with a prefix",
        entrypoint = "direct:log")
    @ConfigurationProperty( // <2>
        name = "prefix",
        description = "The Log body prefix message",
        displayName = "Log Prefix",
        type = "string")
    @Bean // <4>
    public RouteBuilder logBodyWithprefix() {
        return new RouteBuilder() {
            @Override
            public void configure() throws Exception {
                from("direct::start") // <3>
                    .choice()
                        .when(simple("${header.prefix} != ''"))
                            .log("${header.prefix} ${body}")
                        .otherwise()
                            .log("Output ${body}")
                    .endChoice();
            }
        };
    }
}
----
<1> the action definition
<2> the property definition
<3> the action implementation
<4> register the RouteBuilder as a bean

As we are using java and Syndesis annotations we can leverage the extension-maven-plugin to automatically generate the action definition which will look like:

[source,json]
----
{
  "id": "log-body-with-prefix",
  "name": "Log body with prefix",
  "description": "A simple body log with a prefix",
  "descriptor": {
    "kind": "ENDPOINT", <1>
    "entrypoint": "direct:log", <2>
    "inputDataShape": {
      "kind": "none"
    },
    "outputDataShape": {
      "kind": "none"
    },
    "propertyDefinitionSteps": [ {
      "description": "extension-properties",
      "name": "extension-properties",
      "properties": { <43
        "prefix": {
          "componentProperty": false,
          "deprecated": false,
          "description": "The Log body prefix message",
          "displayName": "Log Prefix",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": false,
          "secret": false,
          "type": "string",
          "raw": false
        }
      }
    } ]
  },
  "actionType": "step"
}
----
<1> the type of action is set to `ENDPOINT` as the runtime should invoke a Camel endpoint to execute this action/step
<2> the Camel endpoint to invoke which is the `from` of our route
<3> the properties this step/action exposes to the user, each value set by the user is set to a message header with the same name as the property

[IMPORTANT]
====
To make your configuration class discoverable by Spring Boot you need to list them in a file named `META-INF/spring.factories` like:

[source]
----
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
    com.company.ActionsConfiguration
----

[NOTE]
====
As we are using Spring Boot, every bean you eventually register in your configuration classes will be available to the Camel context.

====

For additional info see https://docs.spring.io/spring-boot/docs/1.5.11.RELEASE/reference/html/boot-features-developing-auto-configuration.html[Spring Boot Reference]

====

=== Using Step API

An action developed using Step API give developers a way to interact with the runtime route creation so developers can use any method provided by a `ProcessorDefinition` and can create more complex routes such as a slit step:

[source,java]
----
import java.util.Map;
import java.util.Optional;

import io.syndesis.extension.api.Step;
import io.syndesis.extension.api.annotations.Action;
import io.syndesis.extension.api.annotations.ConfigurationProperty;
import org.apache.camel.CamelContext;
import org.apache.camel.model.ProcessorDefinition;
import org.apache.camel.util.ObjectHelper;
import org.apache.camel.Expression;
import org.apache.camel.builder.Builder;
import org.apache.camel.processor.aggregate.AggregationStrategy;
import org.apache.camel.processor.aggregate.UseOriginalAggregationStrategy;
import org.apache.camel.spi.Language;

@Action(id = "split", name = "Split", description = "Split your exchange")
public class SplitAction implements Step {

    @ConfigurationProperty(
        name = "language",
        displayName = "Language",
        description = "The language used for the expression")
    private String language;

    @ConfigurationProperty(
        name = "expression",
        displayName = "Expression",
        description = "The expression used to split the exchange")
    private String expression;

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getExpression() {
        return expression;
    }

    public void setExpression(String expression) {
        this.expression = expression;
    }

    @Override
    public Optional<ProcessorDefinition> configure(
            CamelContext context,
            ProcessorDefinition route,
            Map<String, Object> parameters) { // <1>

        String languageName = language;
        String expressionDefinition = expression;

        if (ObjectHelper.isEmpty(languageName) && ObjectHelper.isEmpty(expressionDefinition)) {
            route = route.split(Builder.body());
        } else if (ObjectHelper.isNotEmpty(expressionDefinition)) {

            if (ObjectHelper.isEmpty(languageName)) {
                languageName = "simple";
            }

            final Language splitLanguage = context.resolveLanguage(languageName);
            final Expression splitExpression = splitLanguage.createExpression(expressionDefinition);
            final AggregationStrategy aggreationStrategy = new UseOriginalAggregationStrategy(null, false);

            route = route.split(splitExpression).aggregationStrategy(aggreationStrategy);
        }

        return Optional.of(route);
    }
}
----
<1> the step/action implementation

As we are using java and Syndesis annotations we can leverage the extension-maven-plugin to automatically generate the action definition which will look like:

[source,json]
----
{
  "id": "split",
  "name": "Split",
  "description": "Split your exchange",
  "descriptor": {
    "kind": "STEP", <1>
    "entrypoint": "io.syndesis.extension.split.SplitAction", <2>
    "inputDataShape": {
      "kind": "none"
    },
    "outputDataShape": {
      "kind": "none"
    },
    "propertyDefinitionSteps": [ {
      "description": "extension-properties",
      "name": "extension-properties",
      "properties": {
        "language": {
          "componentProperty": false,
          "deprecated": false,
          "description": "The language used for the expression",
          "displayName": "Language",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": false,
          "secret": false,
          "type": "string",
          "raw": false
        },
        "expression": {
          "componentProperty": false,
          "deprecated": false,
          "description": "The expression used to split the exchange",
          "displayName": "Expression",
          "javaType": "java.lang.String",
          "kind": "parameter",
          "required": false,
          "secret": false,
          "type": "string",
          "raw": false
        }
      }
    } ]
  },
  "tags": [],
  "actionType": "step"
}
----
<1> the type of action is set to `STEP`
<2> the class implementing the `Step` interface


== Developing Connector extensions

If Syndesis does not provide a connector for the system you want to integrate with, an experienced developer can code an extension that contribute a new connector to Syndesis.

[IMPORTANT]
====
Syndesis does not **yet** provide a way to automatically generate the extension definition from java code for this extension type.
====

A connector in its essence, is a proxy for a real camel component that configure the underlying component and create endpoints according to pre-defined options defined in the extension definition and user supplied options collected by Syndesis UI.
The definition extends the one used for step extension with the following additional items:

- **componentScheme**
+
Defines the camel component to use. It can be set on _action_ or global level with the _action_ one having precedence.
- **connectorCustomizers**
+
A list of classes implementing https://github.com/syndesisio/syndesis/blob/master/app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyCustomizer.java[ComponentProxyCustomizer] used to customize the behavior of a connector such as manipulating properties before they are applied to the underlying component/endpoint, add pre/post endpoint logic and so on.
+
[TIP]
====
Customizer sets at _action_ level are applied after those configured at global level.
====
+
Below an example of acustomizer used to set-up a DataSource from individual options:
+
[source,java]
----
public class DataSourceCustomizer implements ComponentProxyCustomizer, CamelContextAware {
    private final static Logger LOGGER = LoggerFactory.getLogger(DataSourceCustomizer.class);

    private CamelContext camelContext;

    @Override
    public void setCamelContext(CamelContext camelContext) { // <1>
        this.camelContext = camelContext;
    }

    @Override
    public CamelContext getCamelContext() { // <1>
        return this.camelContext;
    }

    @Override
    public void customize(ComponentProxyComponent component, Map<String, Object> options) {
        if (!options.containsKey("dataSource")) {
            if (options.containsKey("user") && options.containsKey("password") && options.containsKey("url")) {
                try {
                    BasicDataSource ds = new BasicDataSource();

                    consumeOption(camelContext, options, "user", String.class, ds::setUsername); // <2>
                    consumeOption(camelContext, options, "password", String.class, ds::setPassword); // <2>
                    consumeOption(camelContext, options, "url", String.class, ds::setUrl); // <2>

                    options.put("dataSource", ds);
                } catch (@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception e) {
                    throw new IllegalArgumentException(e);
                }
            } else {
                LOGGER.debug("Not enough information provided to set-up the DataSource");
            }
        }
    }
}
----
<1> By implementing CamelContextAware, the camel context is injected before invoking the customize method
<2> Process options and remove them from the options map
+
If the customizer respect java beans conventions, you can also inject the properties and the example above can be rewritten as:
+
[source,java]
----
public class DataSourceCustomizer implements ComponentProxyCustomizer, CamelContextAware {
    private final static Logger LOGGER = LoggerFactory.getLogger(DataSourceCustomizer.class);

    private CamelContext camelContext;
    private String userName;
    private String password;
    private String url;

    @Override
    public void setCamelContext(CamelContext camelContext) { // <1>
        this.camelContext = camelContext;
    }

    @Override
    public CamelContext getCamelContext() { // <1>
        return this.camelContext;
    }

    public void setUserName(String userName) { // <2>
      this.userName = userName;
    }

    public String getUserName() { // <2>
      return this.userName;
    }

    public void setPassword(String password) { // <2>
      this.password = password;
    }

    public String getPassword() { // <2>
      return this.password;
    }

    public void setUrl(String url) { // <2>
      this.url = url;
    }

    public String getUrl() { // <2>
      return this.url;
    }

    @Override
    public void customize(ComponentProxyComponent component, Map<String, Object> options) {
        if (!options.containsKey("dataSource")) {
            if (userName != null && password != null && url != null) {
                try {
                    BasicDataSource ds = new BasicDataSource();
                    ds.setUserName(userName);
                    ds.setPassword(password);
                    ds.setUrl(url);

                    options.put("dataSource", ds);
                } catch (@SuppressWarnings("PMD.AvoidCatchingGenericException") Exception e) {
                    throw new IllegalArgumentException(e);
                }
            } else {
                LOGGER.debug("Not enough information provided to set-up the DataSource");
            }
        }
    }
}
----
<1> By implementing CamelContextAware, the camel context is injected before invoking the customize method
<2> Process injected options (automatically removed them from the options map)
+
A customizer can also be used to configure before/after logic such as:
+
[source,java]
----
public class AWSS3DeleteObjectCustomizer implements ComponentProxyCustomizer {
  	private String filenameKey;

    public void setFilenameKey(String filenameKey) {
      this.filenameKey = filenameKey;
    }

    public String getFilenameKey() {
        return this.filenameKey;
    }

    @Override
    public void customize(ComponentProxyComponent component, Map<String, Object> options) {
      	component.setBeforeProducer(this::beforeProducer);
    }

    public void beforeProducer(final Exchange exchange) throws IOException {
      	exchange.getIn().setHeader(S3Constants.S3_OPERATION, S3Operations.deleteObject);

    	  if (filenameKey != null) {
    		    exchange.getIn().setHeader(S3Constants.KEY, filenameKey);
    	  }
    }
}
----

- **connectorFactory**
+
Defines the class implementing https://github.com/syndesisio/syndesis/blob/master/app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyFactory.java[ComponentProxyFactory] used to create and/or configure the underling component/endpoint.  It can be set on _action_ or global level with the _action_ one having precedence.
+
To customize the behavior of the https://github.com/syndesisio/syndesis/blob/master/app/integration/component-proxy/src/main/java/io/syndesis/integration/component/proxy/ComponentProxyComponent.java[ComponentProxyComponent] you can override the following methods:
+
** **createDelegateComponent**
+
This method is invoked when a the proxy starts and it is used to eventually create a dedicated instance of the component with scheme defined by the options _componentScheme_.
+
[TIP]
====
The default behavior of this method is to determine if any of the connector/action options applies at component level and if the same option cannot be applied at endpoint level and only in this case, it creates a custom component instance configured according to the applicable options.
====
+
** **configureDelegateComponent**
+
This method is invoked only if a custom component instance has been created to configure additional behavior of the delegated component instance.
+
** **createDelegateEndpoint**
+
This method is invoked when the proxy creates the endpoint and by default creates the endpoint using camel catalog facilities.
+
** **configureDelegateEndpoint**
+
This method is invoked after the delegated endpoint has been created to configure additional behavior of the delegated endpoint instance, as example:
+
[source,java]
----
public class IrcComponentProxyFactory implements ComponentProxyFactory {

    @Override
    public ComponentProxyComponent newInstance(String componentId, String componentScheme) {
        return new ComponentProxyComponent(componentId, componentScheme) {
            @Override
            protected void configureDelegateEndpoint(ComponentDefinition definition, Endpoint endpoint, Map<String, Object> options) throws Exception {
                if (!(endpoint instanceof IrcEndpoint)) {
                    throw new IllegalStateException("Endpoint should be of type IrcEndpoint");
                }

                final IrcEndpoint ircEndpoint = (IrcEndpoint)endpoint;
                final String channels = (String)options.remove("channels");

                if (ObjectHelper.isNotEmpty(channels)) {
                    ircEndpoint.getConfiguration().setChannel(
                        Arrays.asList(channels.split(","))
                    );
                }
            }
        };
    }
}
----


The items above can be set on _action_ level or at global level and behave as follow:

- **componentScheme** and **connectorFactory** set on _action_ level have precedence over the same items defined at global level.
- **connectorCustomizers** set on _action_ are applied as well as those set at global level.



== Developing Library extensions

A library extension is an extension that does not contribute steps or connectors to Syndesis but provide additional classpath elements to integrations runtime. The structure of a library extension is the same of any other extension type with the exception that it does not define any action i.e.:

[source,json]
----
{
  "schemaVersion" : "v1",
  "name" : "Example JDBC Driver Library",
  "description" : "Syndesis Extension for adding a custom JDBC Driver",
  "extensionId" : "io.syndesis.extensions:syndesis-library-jdbc-driver",
  "version" : "1.0.0",
  "tags" : [ "jdbc-driver" ],
  "extensionType" : "Libraries"
}
----

[WARNING]
====
The library support is in its infancy and there are some known limitations:

- Syndesis does not yet offer a way to select which library extension an integration should include, for more info see https://github.com/syndesisio/syndesis/issues/2808[this] issue
- When using the SQL connector, Syndesis add all the extension that have a tag "jdbc-driver" to integration runtime, for more info see https://github.com/syndesisio/syndesis/issues/2809[this] issue
====

[TIP]
====
To add dependencies not on available on maven repository, you can use `system` dependencies:

[source,xml]
----
<dependency>
    <groupId>com.company</groupId>
    <artifactId>jdbc-driver</artifactId>
    <version>1.0</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/lib/jdbc-driver-1.0.jar</systemPath>
</dependency>
----
====
