apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: syndesis
    syndesis.io/app: todo
    syndesis.io/addon: todo
  name: todo
spec:
  lookupPolicy:
    local: false
status:
  tags:
    - items:
      tag: latest
