apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/component: syndesis-meta
    syndesis.io/type: infrastructure
    syndesis.io/addon: meta-service-monitor
    monitoring-key: middleware
    application-monitoring: "true"
  name: syndesis-meta
spec:
  endpoints:
  - targetPort: metrics
  selector:
    matchLabels:
      syndesis.io/component: syndesis-meta
