package io.syndesis.connector.daytrade.springboot;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * The rest connector is used for either hosting REST services (consumer) or
 * calling external REST services (producer).
 * 
 * Generated by camel-connector-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "day-trade-place")
public class DayTradePlaceConnectorConfiguration {

    /**
     * Host and port of HTTP service to use (override host in swagger schema)
     */
    private String host;

    public String getHost() {
        return host;
    }

    public void setHost(String host) {
        this.host = host;
    }
}