package io.syndesis.connector.tradeinsight.springboot;

import java.util.HashMap;
import java.util.Map;
import io.syndesis.connector.tradeinsight.TradeInsightSellComponent;
import org.apache.camel.CamelContext;
import org.apache.camel.util.IntrospectionSupport;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;

/**
 * Generated by camel-connector-maven-plugin - do not edit this file!
 */
@Configuration
@ConditionalOnBean(type = "org.apache.camel.spring.boot.CamelAutoConfiguration")
@AutoConfigureAfter(name = "org.apache.camel.spring.boot.CamelAutoConfiguration")
@EnableConfigurationProperties(TradeInsightSellConnectorConfiguration.class)
public class TradeInsightSellConnectorAutoConfiguration {

    @Lazy
    @Bean(name = "trade-insight-sell-component")
    @ConditionalOnClass(CamelContext.class)
    @ConditionalOnMissingBean(io.syndesis.connector.tradeinsight.TradeInsightSellComponent.class)
    public TradeInsightSellComponent configureTradeInsightSellComponent(
            CamelContext camelContext,
            TradeInsightSellConnectorConfiguration configuration)
            throws Exception {
        TradeInsightSellComponent connector = new TradeInsightSellComponent();
        connector.setCamelContext(camelContext);
        Map<String, Object> parameters = new HashMap<>();
        IntrospectionSupport.getProperties(configuration, parameters, null,
                false);
        IntrospectionSupport.setProperties(camelContext,
                camelContext.getTypeConverter(), connector, parameters);
        connector.setComponentOptions(parameters);
        return connector;
    }
}