- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_TODO
    value: registry.redhat.io/rhel8/php-72
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_OAUTH
    value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.7
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_UI
    value: registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-ignite-ui:1.9
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_S2I
    value: registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-ignite-s2i:1.9
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_PROMETHEUS
    value: registry.redhat.io/openshift4/ose-prometheus:v4.7
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_UPGRADE
    value: registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-ignite-upgrade:1.9
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_META
    value: registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-ignite-meta:1.9
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_DATABASE
    value: registry.redhat.io/rhscl/postgresql-12-rhel7
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_PSQL_EXPORTER
    value: registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-postgres-exporter-rhel7:1.9
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_SERVER
    value: registry-proxy.engineering.redhat.com/rh-osbs/fuse7-fuse-ignite-server:1.9
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: RELATED_IMAGE_AMQ
    value: registry.redhat.io/amq7/amq-broker-rhel8:7.8
