/*
 * Copyright (C) 2016 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Camel ApiName Enumeration generated by camel-api-component-maven-plugin
 * Generated on: Thu Oct 11 18:45:59 UTC 2018
 */
package org.apache.camel.component.olingo4.internal;

import org.apache.camel.util.component.ApiName;

/**
 * Camel {@link ApiName} Enumeration for Component Olingo4
 */
@SuppressWarnings("PMD")
public enum Olingo4ApiName implements ApiName {

    DEFAULT("");

    private static final Olingo4ApiName[] VALUES = values();

    private final String name;

    private Olingo4ApiName(String name) {
        this.name = name;
    }

    @Override
    public String getName() {
        return name;
    }

    public static Olingo4ApiName fromValue(String value) throws IllegalArgumentException {
        for (int i = 0; i < VALUES.length; i++) {
            if (VALUES[i].name.equals(value)) {
                return VALUES[i];
            }
        }
        throw new IllegalArgumentException("Invalid value " + value);
    }
}
