/*
 * Copyright (C) 2016 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Camel ApiCollection generated by camel-api-component-maven-plugin
 * Generated on: Thu Oct 11 18:45:59 UTC 2018
 */
package org.apache.camel.component.olingo4.internal;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.camel.component.olingo4.Olingo4AppEndpointConfiguration;
import org.apache.camel.component.olingo4.Olingo4Configuration;
import org.apache.camel.util.component.ApiCollection;
import org.apache.camel.util.component.ApiMethod;
import org.apache.camel.util.component.ApiMethodHelper;

/**
 * Camel {@link ApiCollection} for Olingo4
 */
@SuppressWarnings("PMD")
public final class Olingo4ApiCollection extends ApiCollection<Olingo4ApiName, Olingo4Configuration> {

    private static Olingo4ApiCollection collection;

    private Olingo4ApiCollection() {
        final Map<String, String> aliases = new HashMap<String, String>();
        final Map<Olingo4ApiName, ApiMethodHelper<? extends ApiMethod>> apiHelpers = new HashMap<>();
        final Map<Class<? extends ApiMethod>, Olingo4ApiName> apiMethods = new HashMap<>();

        List<String> nullableArgs;

        aliases.clear();
        nullableArgs = Arrays.asList("queryParams", "endpointHttpHeaders", "edm", "responseHandler");
        apiHelpers.put(Olingo4ApiName.DEFAULT, new ApiMethodHelper<Olingo4AppApiMethod>(Olingo4AppApiMethod.class, aliases, nullableArgs));
        apiMethods.put(Olingo4AppApiMethod.class, Olingo4ApiName.DEFAULT);

        setApiHelpers(apiHelpers);
        setApiMethods(apiMethods);
    }

    @Override
    public Olingo4Configuration getEndpointConfiguration(Olingo4ApiName apiName) {
        Olingo4Configuration result = null;
        switch (apiName) {
        case DEFAULT:
            result = new Olingo4AppEndpointConfiguration();
            break;
        }
        return result;
    }

    public static synchronized Olingo4ApiCollection getCollection() {
        if (collection == null) {
            collection = new Olingo4ApiCollection();
        }
        return collection;
    }
}
