// This module is included in the following assemblies:
// as_creating-integrations.adoc

[id='add-log-step_{context}']
= Logging information about integration execution

For each execution of an integration, 
for each step in a flow, {prodname} provides the following activity 
information:

* The date and time that the step was executed
* How long it took to execute the step
* Whether execution was successful
* The error message if execution was not successful

To view this information in {prodname}, display the integration's summary
and then click the *Activity* tab. 

To obtain further details about integration execution, you can 
log information about the messages that an integration processes by 
adding a log step to an integration flow. 
For each message that an integration receives, a log step can provide
one or more of the following:

* The message's context, which provides metadata about the message, 
including the message's header.
* The message's body, which provides the content of the message.
* Text that you specify either explicitly or through evaluation of an 
http://camel.apache.org/simple.html[Apache Camel Simple language] expression. 

[NOTE]
====
The Log connection that was available in previous releases is no longer
available to be added to integrations. Add a log step instead of a log 
connection. 
====

.Prerequisites
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure

. In the flow visualization, click the plus sign where you want to add a log step.
Skip this step if {prodname} is prompting you to choose a finish connection. 
. Click *Log*.
. On the *Configure Log Step* page, select the content that you want
to log. If you select *Custom Text*, then in the text input field, 
enter one of the following:
* The text that you want to log
* A Camel Simple language expression

+
If you enter an expression, {prodname} resolves the 
expression and logs the resulting text. 
. When log step configuration is complete, click *Next* to add the step
to the flow. 

.Next step
When the flow is complete, publish the integration to start seeing output
from the new log step.

.Additional resources
After a flow that has a log step has been executed, output from
the log step appears in the integration's *Activity* tab. See
xref:viewing-integration-activity-information_monitor[Viewing integration activity information].
