// This module is included in the following assemblies:
// as_mapping-data.adoc

[id='transform-target-data_{context}']
= Transforming source or target data

In the data mapper, after you define a mapping, you can transform
any field in the mapping. 
Transforming a data field defines how you want to store the data. 
For example, you could specify the *Capitalize* transformation to ensure that the first
letter of a data value is uppercase.

.Procedure

. Map the fields. This can be a one-to-one mapping, a combination mapping,
or a separation mapping.
. In the *Mapping Details* panel, under *Sources* or under *Targets*, 
in the box for the field that you want to transform, click the arrow that points to the
trash can. This displays a field where you can select the transformation
that you want the data mapper to perform.
. Click in this field to display the list of transformations.
. Click the transformation that you want to perform.
. If the transformation requires any input parameters, specify them
in the appropriate input fields.
. To add another transformation, click the arrow that points to the
trash can again. 

.Additional resource

* link:{LinkFuseOnlineIntegrationGuide}#available-transformations_map[Available transformations].
