// This module is used in the following assemblies:
// as_adding-api-connectors.adoc

[id='updating-api-connectors_{context}']
= Updating API client connectors by creating new ones

When there is an update to an OpenAPI document from which you created an
API client connector, and you want your API client connector to use those
updates, you must create a new API client connector.
You cannot directly update an API client connector. After you create
the new API client connector, you use it to create a new connection and
then you edit each integration that uses a connection that was created
from the out-of-date connector. 

.Prerequisites

Be prepared to do one of the following:

* Upload the updated OpenAPI document.
* Upload the out-of-date schema again and update it in API Designer.

.Procedure

. Create a new API client connector based on the updated OpenAPI document.
To easily distinguish between the old connector and the new connector, 
you  might want to specify a version number in the connector name or 
the connector description. 
+
See link:{LinkFuseOnlineIntegrationGuide}#creating-api-connectors_add-client-connector[Creating REST API client connectors].

. Create a new connection from the new connector. Again, you want to be
able to easily distinguish between connections created from the old
connector and connections created from the new connector. A version number
in the connection name or connection description is helpful.
. Edit each integration that uses a connection that was created from the
old connector by removing the old connection and adding the new connection.
. Publish each updated integration.
. Recommended, but not required: delete the old connector and the old
connections. 
