// This assembly is included in the following assemblies:
// as_adding-extensions.adoc

[id='updating-extensions_{context}']
= Updating extensions

When a developer updates an extension, you can upload the updated `.jar`
file to implement the updates in your integrations. 

.Prerequisite
A developer has provided you with an updated `.jar` file for an extension
that you previously uploaded. 

.Procedure

. In {prodname}, in the left panel, click *Customizations* > *Extensions*. 
. At the right of the entry for the extension that you want to update, 
click *Update*. 
. Click in the dotted-line box to navigate to and select the 
updated `.jar` file, and click *Open*.
. Confirm that the extension details are correct and click *Import Extension*. 
. In the details page for the updated extension, determine which integrations
use the connector or custom step(s) defined in the extension. 

It is up to you to 
know exactly what is required to update each integration that uses a 
custom connector or a 
custom step from the updated extension.  At the very least, you must
republish each 
integration that uses a customization defined in the updated extension.

In some cases, you might need to edit the integration to change
or add configuration details for a customization. You must communicate
with the extension developer to understand how to update integrations. 
