// This module is included in these assemblies:
// as_monitoring-integrations.adoc

[id='viewing-integration-metrics_{context}']
= Viewing metrics for a particular integration

{prodname} provides the following metrics for each integration:

* *Total Errors* indicates the number of runtime errors that all
executions of this integration
encountered during the past 30 days. 

* *Last Processed* displays the most recent date and time that this 
integration processed a message. The message might have been successfully
processed or there might have been an error.  

* *Total Messages* is the number of messages that all executions
of this integration processed in the last 30 days. This includes 
message failures. 

* *Uptime* indicates when this integration started running and how long
it has been running without an error.  

.Prerequisite
The integration that you want to view metrics for is running or has been
running.

.Procedure

. In the left panel, click *Integrations*. 
. At the right of the entry for the integration for which you want to view metrics, 
click *View*. 
. In the integration's summary page, click *Metrics*.
