// This module is included in these assemblies:
// as_managing-integrations.adoc

[id='troubleshooting-integration-execution_{context}']
= Tips for troubleshooting integration execution

If an integration stops working, check its activity and history details.
See link:{LinkFuseOnlineIntegrationGuide}#viewing-integration-activity-information_monitor[Viewing integration activity information]
and link:{LinkFuseOnlineIntegrationGuide}#viewing-integration-history_monitor[Viewing integration history]. 

For a connection to an application that uses OAuth, 
you might see an error message that indicates
that the access token for the application has expired. Sometimes,
you might get a less explicit  `403 - Access denied` message. 
The information in the message depends on the application that the
integration is connecting to.
In this situation, try reconnecting to the application and 
then republishing the integration:

. In the left panel, click *Integrations*. 
. In the list of integrations, at the right of the entry for the integration
that stopped running, click *View*. 
. In the integration's summary page, in the flow visualization, 
click the icon for the application that you want to reconnect to. 
+
If this is an API provider integration, then in the integration's 
summary page, click its flow icon to display the operations list.
Then click the operation whose path contains the connection 
that is failing and then click the failing connection in the 
operation's path visualization. 
. In the connection's details page, click *Reconnect*. 
. Respond to that application's OAuth workflow prompts. 
+
{prodname} displays a message to indicate that its access to that
application has been authorized. 
For some applications, this takes a few seconds but it can take longer
for other applications. 

. After reconnecting to the application, start the integration. 

If reconnection is not successful, try this:

. Re-register {prodname} as a client of the application. See 
link:{LinkFuseOnlineIntegrationGuide}#general-procedure-for-obtaining-authorization_connections[General procedure for obtaining authorization]. 
. Create a new connection. 
. Edit each integration that was using the old connection:
.. Remove the old connection. 
.. Replace it with the new connection.
. Publish each updated integration. 
