package com.redhat.ipaas.connector.daytrade.springboot;

import java.util.HashMap;
import java.util.Map;
import com.redhat.ipaas.connector.daytrade.DayTradePlaceComponent;
import org.apache.camel.CamelContext;
import org.apache.camel.util.IntrospectionSupport;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;

/**
 * Generated by camel-connector-maven-plugin - do not edit this file!
 */
@Configuration
@ConditionalOnBean(type = "org.apache.camel.spring.boot.CamelAutoConfiguration")
@AutoConfigureAfter(name = "org.apache.camel.spring.boot.CamelAutoConfiguration")
@EnableConfigurationProperties(DayTradePlaceConnectorConfiguration.class)
public class DayTradePlaceConnectorAutoConfiguration {

    @Lazy
    @Bean(name = "day-trade-place-component")
    @ConditionalOnClass(CamelContext.class)
    @ConditionalOnMissingBean(com.redhat.ipaas.connector.daytrade.DayTradePlaceComponent.class)
    public DayTradePlaceComponent configureDayTradePlaceComponent(
            CamelContext camelContext,
            DayTradePlaceConnectorConfiguration configuration) throws Exception {
        DayTradePlaceComponent connector = new DayTradePlaceComponent();
        connector.setCamelContext(camelContext);
        Map<String, Object> parameters = new HashMap<>();
        IntrospectionSupport.getProperties(configuration, parameters, null,
                false);
        IntrospectionSupport.setProperties(camelContext,
                camelContext.getTypeConverter(), connector, parameters);
        connector.setComponentOptions(parameters);
        return connector;
    }
}