package io.syndesis.connector.salesforce.springboot;

import java.util.HashMap;
import java.util.Map;
import io.syndesis.connector.salesforce.SalesforceDeleteSObjectWithIdComponent;
import org.apache.camel.CamelContext;
import org.apache.camel.util.IntrospectionSupport;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;

/**
 * Generated by camel-connector-maven-plugin - do not edit this file!
 */
@Configuration
@ConditionalOnBean(type = "org.apache.camel.spring.boot.CamelAutoConfiguration")
@AutoConfigureAfter(name = "org.apache.camel.spring.boot.CamelAutoConfiguration")
@EnableConfigurationProperties(SalesforceDeleteSObjectWithIdConnectorConfiguration.class)
public class SalesforceDeleteSObjectWithIdConnectorAutoConfiguration {

    @Lazy
    @Bean(name = "salesforce-delete-sobject-with-id-component")
    @ConditionalOnClass(CamelContext.class)
    @ConditionalOnMissingBean(io.syndesis.connector.salesforce.SalesforceDeleteSObjectWithIdComponent.class)
    public SalesforceDeleteSObjectWithIdComponent configureSalesforceDeleteSObjectWithIdComponent(
            CamelContext camelContext,
            SalesforceDeleteSObjectWithIdConnectorConfiguration configuration)
            throws Exception {
        SalesforceDeleteSObjectWithIdComponent connector = new SalesforceDeleteSObjectWithIdComponent();
        connector.setCamelContext(camelContext);
        Map<String, Object> parameters = new HashMap<>();
        IntrospectionSupport.getProperties(configuration, parameters, null,
                false);
        IntrospectionSupport.setProperties(camelContext,
                camelContext.getTypeConverter(), connector, parameters);
        connector.setComponentOptions(parameters);
        return connector;
    }
}