[id='add-concur-connection']
= Add a SAP Concur connection to an integration

In an integration, you can connect to SAP Concur to obtain all lists, 
obtain a list that you specify, update a list, or create a list.  
In this release, these are the supported SAP Concur connection actions. 

ifeval::["{location}" == "downstream"]

[IMPORTANT]
====
Other SAP Concur actions are 
https://access.redhat.com/support/offerings/techpreview/[Technology Preview features].

====
endif::[]

In an integration, a connection to SAP Concur is usually a middle or finish
connection and not a start connection. 

.Prerequisites
* You must create a SAP Concur connection before you can add a SAP Concur
connection to an integration. If you did not already create a SAP Concur
connection, see <<create-salesforce-connection_{context}>>.

* You must be creating an integration or updating an integration to
add a connection to that integration. If you need to, see the 
{LinkFuseOnlineIntegrationGuide}#procedure-for-creating-an-integration[general procedure
for creating an integration]. 
or see {LinkFuseOnlineIntegrationGuide}#updating-integrations[updating integrations].

.Procedure
The instructions below
assume that {prodname} is prompting you to select a
finish connection or a middle connection.

. On the page that displays available connections, click the SAP Concur
connection that you want to add to the integration. When the integration
uses the connection you select to connect to SAP Concur, {prodname}
uses the credentials defined in that connection.

. Click the action that you want the selected connection to perform.  Each
SAP Concur connection that you add to an integration performs only the action 
you choose. The available actions are: 
+
* Get all lists
* Get a single list, which you identify by its ID
* Create a new list
* Update a list

+
For details about these actions, visit the 
https://developer.concur.com/api-explorer/v3-0/Lists.html[SAP Concur developer center].

. Click *Done* to add the connection to the integration.

The connection appears in the integration flow 
in the location where you added it. 
