[id='adding-dropbox-connection-finish']
= Finish an integration by adding files to Dropbox

To finish an integration by uploading files to Dropbox,
add a Dropbox connection as the finish connection:

. Start creating the integration, add and configure the start connection.
. On the *Choose a Finish Connection* page, click the Dropbox connection that
you want to use to finish the integration. 
. On the *Choose an Action* page, click the *Upload* 
action to add the current integration data to the
Dropbox account that this connection accesses. 
. In the *Remote Path* field, enter the 
local filename path for file that you want to upload. Dropbox stores the file with the 
same path and name. In this release, you can upload only a single file. 
. For the *Upload mode*, 
+
* Select *Add* to upload a file only when a file with the same name is not already
in the same Dropbox folder. If a file with the same name is already
in the same Dropbox folder, then the file is not uploaded and the integration continues.
This is the behavior regardless of whether the content in the file you are trying to
upload has been updated. 
* Select *Force* to ensure that the file is uploaded even if a file with the
same name is present in the same Dropbox folder. Dropbox overwrites the file
that it already has with the file that you are uploading. 
. Click *Next* to specify the action's input type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
