[id='adding-db-connection-finish-middle']
= Access a database in the middle or to complete an integration

To finish an integration by accessing a database, add a database
connection as the finish connection. To access 
a database in the middle of an integration, add a database connection
between the start and finish connections.
The instructions below assume that you are
on the {prodname} *Choose a Finish Connection* page or the
*Choose a Connection* page.

To add a database connection:

. Click the database connection for the database you want to access.
. On the *Choose an Action* page, click one of the following:
+
* *Invoke SQL* operates on data by executing the
SQL statement you specify.
* *Invoke stored procedure* operates on data by invoking
the stored procedure you specify or select.
. If you selected *Invoke SQL*, in the *SQL Statement* field:
** For a middle connection, enter a SQL `SELECT` statement that obtains
one record or enter a SQL `INSERT`, `UPDATE`, or
`DELETE` statement that
operates on one or more records.
The database table that contains the data must already exist.
+
In this release, when a database connection is a middle connection,
a `SELECT` statement can obtain only one record. You should define
the `SELECT` statement so that it obtains one record.

** For a finish connection, enter a SQL `INSERT`, `UPDATE` or
`DELETE` statement to
operate on one or more records.

+
If you selected *Invoke stored procedure*, in the
*Procedure name* field, select or enter the name of the stored procedure to
invoke to operate on the data of interest. The stored procedure you specify must
already exist. The database administrator should have created any stored
procedures you need to use in an integration.

* See the information below about specifying placeholder parameters 
in queries.  

. Click *Done*.

{prodname} tries to validate the connection, which includes
checking that a specified SQL query is syntactically correct and
confirming that the query or stored procedure target data exists. If
verification is successful then {prodname} adds the connection to
the integration. If verification fails then {prodname} displays a message
about the problem. Update your input as needed and try again.

.Specifying parameters in queries

When you access a database in the middle of an integration or to complete
an integration, you can specify placeholder parameters in the SQL query 
or there can be placeholders in the stored procedure. For example: 

[source]
----
INSERT INTO TODO(task, completed) VALUES(:#param_1, :#param_2)
DELETE FROM TODO WHERE task LIKE :#param_3
----

To specify the values of these placeholders, add a data mapping step
to your integration before the database connection. In the data mapping
step, map the appropriate source data fields to the target data
fields, for example, map source data to the `:#param_1`, `:#param_2`, and
`:#param_3` target fields. See
{LinkFuseOnlineIntegrationGuide}#add-data-mapping-step[Add a data mapping step].
