[id='adding-twitter-connections']
= Add a Twitter connection to an integration

You must create a Twitter connection before you can add a Twitter
connection to an integration. If you did not already create a Twitter connection,
see <<create-twitter-connection>>.

A connection to Twitter must be the start connection in an integration. 
You must be creating an integration and being prompted to choose
its start connection or you can be updating an integration to
change its start connection. 
If you need to, see the 
{LinkFuseOnlineIntegrationGuide}#procedure-for-creating-an-integration[general procedure
for creating an integration]. 
or see {LinkFuseOnlineIntegrationGuide}#updating-integrations[updating integrations].

To add a Twitter connection to an integration:

. On the page that displays available connections, click the Twitter
connection that you want to add to the integration. When the integration
uses the selected connection to connect to Twitter, {prodname} uses the
credentials defined in that connection.

. Click the action that you want the selected connection to perform.
A Twitter connection that you add to an integration performs only
the action you choose.

*  *Mention* triggers execution of the integration when a tweet contains
your handle.
* *Search* triggers execution of the integration when a tweet contains
text that you specify. 

. Optionally, enter the configuration information that {prodname}
prompts for. For example, the *Search* action prompts you to specify
how often to search and keywords to search for.

. Click *Done* to add the connection to the integration.

The connection appears in the integration flow 
as the start connection. 
