[id='adding-s3-connection-finish']
= Finish an integration by adding data to Amazon S3

:context: finish
To finish an integration by copying data to Amazon S3, 
add an Amazon S3 connection as the finish connection:

. Start creating the integration.
. Add and configure the start connection.
. On the *Choose a Finish Connection* page, click the Amazon S3 connection that
you want to use to finish the integration. 

. Click the action that you want the connection to perform:
.. *Copy Object* adds one or more objects to the bucket. 
+
To add one file to the bucket, you can enter its name in the *File Name* field.
+
To add multiple files to the bucket, do not specify a file name.
In this case, the action adds all objects that it 
obtains from the previous integration step(s). 
+
If you used the poll action
to obtain multiple files and you specify a file name then the *Copy Object*
action adds only the last file that was received from the poll action. 

.. *Delete Object* deletes an object from the bucket. In the
*File Name* field, specify the name of the object that you want to delete.
If the specified file is not in the bucket, the integration continues 
with no error. 

. After you configure the chosen action, click *Next* to specify 
the action's input type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
