[id='adding-slack-connections']
= Add a Slack connection to an integration

In an integration, to send a message to a Slack channel or user, first create
a Slack connection. You can then add that connection to any number
of integrations as a finish connection or as a middle connection. It 
does not make sense to add a Slack connection that starts an integration
because you must map the message content from a previous 
step to a Slack connection field. In other words, a data mapping
step must be in the integration just before the Slack connection. 

To add a Slack connection to an integration, you must be creating or
editing an integration. If you are creating an integration, then
{prodname} might be prompting you to choose a finish connection. 
To add a middle connection, hover over the plus
sign in the left panel in the location where you want to add the
connection and select *Add a connection*. 

To add a Slack connection:

. Click the Slack connection that you want to add to the integration. 
. Select the action that you want the connection to perform.
+
* Click *Username* to send a message to one user. To configure this action,
in the *User name* field, specify the name of the user to send the message
to. 
* Click *Channel* to publish a message on a channel. To configure
this action, in the *Channel* field, specify the channel to publish 
the message to. The integration sends the integration data in 
a message to that channel. 

. Click *Done* to add the connection to the integration. 
. After you add all connections to the integration, add a data mapping step just 
before the Slack connection. In the mapping step, map a string
from a previous step to the Slack *message* field. This string 
should contain the message that you want to send to the Slack
user or channel. See
{LinkFuseOnlineIntegrationGuide}#add-data-mapping-step[Add data mapping step].
