[id='adding-s3-connection-start']
= Start an integration by obtaining data from Amazon S3

:context: start
To start an integration by obtaining data from an Amazon S3 bucket, 
add an Amazon S3 connection as the start connection:

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the Amazon S3 connection that
you want to use to start the integration.
. On the *Choose an Action* page, click the action that you
want the connection to perform:
* *Get Object* obtains a file from the bucket that the connection
accesses. In the *File Name* field, enter the name of the file that you want
to obtain. If the specified file is not in the bucket, it is a runtime error.

* *Poll an Amazon S3 Bucket* periodically obtains files from the bucket that the
connection accesses. To configure this action:
.. In the *Delay* field, accept the default of 500 milliseconds as the time
that elapses between polls. Or, to specify a different polling interval,
enter a number and select its time unit. 
.. In the *Maximum Objects to Retrieve* field, enter the largest number of files
that one poll operation can obtain. The default is 10.
+
To have no limit on the number of files that can be obtained, specify
`0` or a negative integer. When *Maximum Objects to Retrieve* is unlimited,
the poll action obtains all files in the bucket.
+
If the bucket contains more than the specified maximum number of files
then the action obtains the files that were most recently
modified or created. 
.. In the *Prefix* field, optionally specify a regular expression
that evaluates to a string. If you specify a
prefix then this action retrieves a file
only when its name starts with that string.

.. Indicate whether you want to  
*Obtain files and then delete them from the bucket*.

. After you configure the action, click *Done* to specify the action's output type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
