[id='adding-ftp-start-connection']
= Obtain files from an FTP or SFTP server

To trigger integration execution when
an FTP or SFTP connection finds the file(s) you are interested in,
you must add an FTP or SFTP connection as an integration's start 
connection.

To add an FTP or SFTP connection as a start connection: 

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the 
FTP or SFTP connection that
you want to use to poll an FTP or SFTP server. 
. On the *Choose an Action* page, click *Download*.
. In the *File name expression* field, if you are interested in a single file, 
then enter an 
http://camel.apache.org/simple.html[Apache Camel Simple language]
expression that resolves to a file name. You cannot specify a regular
expression. The connection
polls (periodically checks) the server for this file and downloads it 
when it is found. Leave this field blank if you want to download more
than one file.
. In the *FTP directory* field, enter the absolute or relative path of 
the server directory to
poll. The connection watches this directory for any content and downloads
all files when it finds any content.
. In the *Milliseconds before polling starts* field, accept the default 
of *1000* milliseconds or change the number of milliseconds.
. In the *Milliseconds before the next poll* field, accept the default
of *500* milliseconds or change the number of milliseconds. This is the
interval between polls. 
. In the *Delete after download* field, accept the default of *No*
or select *Yes* to download the file(s) and then delete it(them) from the server.
. Click *Next* to specify the action's output type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
