[id='adding-kafka-connection-finish-middle']
= Publish data to a Kafka broker

In an integration, you can publish data to a Kafka broker to finish
an integration. To do this, add a Kafka connection as the integration's 
finish connection. To publish data to a Kafka broker in the
middle of integration, add a Kafka connection to an integration after
the start connection and before the finish connection. 

To add a Kafka connection that publishes data:

. Start creating the integration.
. Add and configure the start connection.
. On the *Choose a Finish Connection* page, do one of the following:
+
* To finish an integration by publishing data, click the Kafka connection 
that you want to use. 
* To publish data in the middle of an integration, click the connection that you
want to use to finish the integration. Configure that connection. When the
finish connection is part of the integration, in the left panel, hover over
the plus sign where you want to add a Kafka connection and click
*Add a connection*. Click the Kafka connection that you want to use
to publish a message in the middle of an integration. 

. On the *Choose an Action* page, click *Publish*. 
. In the *Topic Name* field, click the down carat to display a list
of topics and click the topic that you want to publish to. 
.  Click *Next* to specify the action's input type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
