[id='adding-kafka-connection-start']
= Obtain data from a Kafka broker

To trigger execution of an integration based on receiving data
from a Kafka broker, add a Kafka connection as the start connection. When 
the integration is running, the Kafka connection continuously watches for data
in the Kafka topic that you specify. When the connection finds new data,
it passes that data to the next step in the integration. 

To start an integration when data is available from a Kafka topic:

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the Kafka connection that
you want to use to start the integration. 
. On the *Choose an Action* page, click the *Subscribe* action
to receive data from the topic that you specify. 
. In the *Topic Name* field, enter the name of the Kafka topic 
to subscribe to in order to receive data. 
. Click *Next* to specify the action's output type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
