[id='adding-http-connections']
= Add an HTTP or HTTPS connection to an integration

After you create an HTTP or HTTPS connection, you can use it 
in any number of integrations as follows:

* To start an integration by periodically invoking an HTTP or HTTPS endpoint, 
add an HTTP or HTTPS connection as the integration's start connection. 

* To finish an integration by invoking an HTTP or HTTPS endpoint once, 
add an HTTP or HTTPS connection as the integration's finish connection. 

* In the middle of an integration, to invoke an HTTP or HTTPS endpoint
once, add an HTTP or HTTPS connection
after the start connection and before the finish connection. 

If you are creating an integration, {prodname} prompts you to choose
and configure the start connection, and then choose and configure the
finish connection. To add a middle connection, hover over the plus sign
in the left panel at the location where you want to add the connection, 
and select *Add a connection*. 

In all of these situations, {prodname} displays the available
connections. To add an HTTP or HTTPS connection:

. Click the HTTP or HTTPS connection that you want to add to the
integration. 
. Select the action that you want the connection to perform:
+ 
* If you are adding a start connection, then *Periodic invoke URL*
is the only available action. This action invokes the endpoint at intervals
that you specify and triggers the integration if the endpoint returns
any data. 

* If you are adding a finish or middle connection, then *Invoke URL* 
is the only available action. This action invokes the endpoint once. 

. In the *URL Path* field, specify the location of the endpoint that you 
want to invoke. 

. In the *HTTP Method* field, select the method that you want the 
connection to perform. The default method is `GET`. 
+
* `GET` obtains the content at the URL path. 
* `PUT` replaces the content at the URL path with the integration data. 
* `POST` stores the integration data at the URL path to create new 
content.
* `DELETE` removes content at the URL path.
* `HEAD` obtains metadata about the content at the URL path. 
* `OPTIONS` obtains communication option settings at the URL path.
* `TRACE` obtains information for testing and diagnostic purposes. 
* `PATCH` partially updates the content at the URL path according to
the integration data. 

. If you are adding a start connection, which periodically invokes the 
URL, then in the  *Period* field, accept the default interval of *1* second 
or specify a number and its unit (milliseconds, seconds, minutes, or hours)
to indicate how long to wait between invocations. 

. Click *Done* to specify the action's input or output type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
