[id='adding-amqp-connection-finish']
= Finish an integration by publishing AMQP messages

:context: finish
To finish an integration by publishing messages to an AMQP broker,
add an AMQP connection as the finish connection. You must be creating or
editing an integration. You must have already added the start connection.
Follow these instructions:

. On the *Choose a Finish Connection* page, click the AMQP connection that
you want to use to finish the integration. 
. On the *Choose an Action* page, click *Publish messages* to
publish messages to the queue or topic you specify. 
. In the *Destination Name* field, enter the name of the queue or 
topic to send messages to. 
. For the *Destination Type*, accept *Queue* or select *Topic*. 
. Select *Persistent* to guarantee message delivery even if
a connection fails. 

. Click *Next* to specify the action's input and output type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
