[id='adding-db-connection-start']
= Start an integration by accessing a database

To start an integration by accessing a database:

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the
database connection that you want to use to start an integration.
. On the *Choose an Action* page, click one of the following:
+
* *Periodic SQL invocation* obtains data by periodically invoking the
SQL query you specify.
* *Periodic stored procedure invocation* obtains data by periodically invoking
the stored procedure you specify or select.
. If you selected *Periodic SQL invocation*, in the *Query* field,
enter a SQL `SELECT` statement to obtain one or more records. For 
example: `*SELECT * from my_db_table*`.
The database table that contains the data you want must already exist.
+
If you selected *Periodic stored procedure invocation*, in the
*Procedure name* field, select or enter the stored procedure to
invoke to obtain the data of interest. The stored procedure you specify must
already exist. The database administrator should have created any stored
procedures you need to use in an integration.
. In the *Period* field, enter an integer and indicate whether the unit is 
milliseconds, seconds, 
minutes, hours, or days. For example, if you specify `5 minutes` then
the connection invokes the specified query or stored procedure every
five minutes.
. Click *Done*.

{prodname} tries to validate the connection, which includes
checking that a specified SQL query is syntactically correct and
confirming that the query or stored procedure target data exists. If
verification is successful then {prodname} adds the start connection to
the integration. If verification fails then {prodname} displays a message
about the problem. Update your input as needed and try again.
