[id='adding-mqtt-connection-start']
= Obtain a message from an MQTT broker

To trigger execution of an integration based on receiving a message
from an MQTT broker, add an MQTT connection as the start connection. When 
the integration is running, the MQTT connection continuously watches for messages
on the MQTT queue or topic that you specify. When the connection finds a 
message, it passes it to the next step in the integration. An MQTT 
connection handles one message at a time. 

To start an integration when a message from an MQTT broker is found:

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the MQTT connection that
you want to use to start the integration. 
. On the *Choose an Action* page, click the *Subscribe* action
to receive messages from the queue or topic that you specify. 
. In the *MQTT queue/topic name* field, enter the name of the queue or topic 
to subscribe to in order to receive data. 
. Click *Next* to specify the action's input type. See 
{LinkFuseOnlineIntegrationGuide}#specifying-connection-input-output-types[Specifying connection action input and output types]. 
