[id='alternatives-for-populating-email-to-send']
= Alternatives for populating email to send

A Gmail connection that finishes an integration or that is
in the middle of an integration sends an email from the Gmail
account that the connection is authorized to access. There are 
several ways to populate the content of the email that the connection
sends. Before you add a Gmail connection that sends an email, consider 
how you want to populate that email.

The alternatives for populating an email to send are as follows:

* Add a data mapper step just before the Gmail connection that sends
an email. In this data mapper step, map one or more data values that were output 
from previous integration steps to Gmail connection *Send Email* action fields. 
The *Send Email* action fields are: 
+ 
** *Email to*
** *Email subject*
** *Email text*
** *Email cc*
** *Email bcc*

* Configure the Gmail connection *Send Email* action to have static
values in one or more *Send Email* action fields. 

* Use both a data mapper step and *Send Email* action configuration to
populate the fields. In other words, you can map content to some fields
and specify static content for other fields. 
