// This assembly is included in the following assemblies:
// Upstream: connecting/master.adoc  
// Downstream: connecting-fuse-online-to-applications-and-services/master.adoc

[id='connecting-to-jira_{context}']
= Connecting to Jira
:context: jira

In an integration, you can connect to a Jira server to 
obtain, create, or update issues. Jira is a tool for 
planning, tracking, and managing software development projects. 
Each Jira environment allows customization of the workflow, which 
has an effect on the details for connecting to Jira in an integration. 
Consulting with your Jira administrator should clarify the details. 

ifeval::["{location}" == "downstream"]
[IMPORTANT]
====
Connecting to Jira is a Technology Preview feature only. Technology Preview features are 
not supported with Red Hat production service level agreements (SLAs) and might not be 
functionally complete. Red Hat does not recommend using them in production. 
These features provide early access to upcoming product features, enabling 
customers to test functionality and provide feedback during the development process. 
For more information about the support scope of Red Hat Technology Preview features, 
see link:https://access.redhat.com/support/offerings/techpreview/[]. 
====
endif::[]

The following topics provide information and procedures for creating integrations 
that connect to a Jira server:

* xref:registering-with-jira_{context}[]
* xref:creating-jira-connections_{context}[]
* xref:adding-jira-connection-start_{context}[]
* xref:adding-jira-connection-add-issue_{context}[]
* xref:adding-jira-connection-add-comment_{context}[]
* xref:adding-jira-connection-attach-file_{context}[]
* xref:adding-jira-connection-watchers_{context}[]
* xref:adding-jira-connection-update-issue_{context}[]
* xref:adding-jira-connection-transition-issue_{context}[]

include::p_registering-with-jira.adoc[leveloffset=+1]

include::p_creating-jira-connections.adoc[leveloffset=+1]

include::p_adding-jira-connection-start.adoc[leveloffset=+1]

include::p_adding-jira-connection-add-issue.adoc[leveloffset=+1]

include::p_adding-jira-connection-add-comment.adoc[leveloffset=+1]

include::p_adding-jira-connection-attach-file.adoc[leveloffset=+1]

include::p_adding-jira-connection-watchers.adoc[leveloffset=+1]

include::p_adding-jira-connection-update-issue.adoc[leveloffset=+1]

include::p_adding-jira-connection-transition-issue.adoc[leveloffset=+1]

:context: connectors
