[id='configure-concur-connector-implementation']
= Configure the SAP Concur connector for the implementation site

To develop and test an integration that connects to SAP Concur,
you configure the SAP Concur connector in a {prodname} development environment 
for access to the SAP Concur implementation site. 
This lets you create any number of integrations that connect
to the SAP Concur implementation site. In other words, you need to
configure the SAP Concur connector once in a given
{prodname} environment.

.Prerequisites
You obtained OAuth credentials that authorize your {prodname} 
development environment to access
the SAP Concur implementation site. 

.Procedure

. In a {prodname} development environment, in the left panel, click *Settings*.
. On the *Settings* page, expand the *SAP Concur* entry. 
. In the *Client ID* field, enter the client ID that you received from
SAP Concur.
. In the *Client Secret* field, enter the client secret that you received
from SAP Concur. 
+
{prodname} populates the other fields. For the SAP Concur implementation
site, the values are something like these:
+
* *Authorization URL*: 
`\https://us-impl.api.concursolutions.com/oauth2/v0/authorize`
* *Token URL*: 
`\https://us-impl.api.concursolutions.com/oauth2/v0/token`
* *Scopes*: 
`LIST` is the minimum and it authorizes execution of the SAP Concur list
actions. 
* *API endpoint URL*: 
`\https://us-impl.api.concursolutions.com`

. Click *Save*. {prodname} immediately tries to validate the connector. 
If validation is not successful, correct the input values and try again. 
If validation is successful, you can create a SAP Concur connection,
which you can add to an integration. 
. To create a SAP Concur connection, click the *create a connection* link
in the success message. Or, to create a connection later, click *Ok* to 
contract the SAP Concur entry in the *Settings* page. 

 
