[id='connecting-to-gmail']
= Connecting to Gmail

To trigger an integration when a particular Gmail
account receives an email, add a Gmail connection to an integration as its
start connection. In an integration, to send an email from a
particular Gmail account, add a Gmail connection as the integration's
finish connection, or as a middle connection. 

The general steps for connecting to Gmail in an integration are:

. Register {prodname} as a client application that can access the Gmail API.
. Create a Gmail connection. When you do this you choose the Gmail account that
the connection is authorized to access.
. If your integration sends an email from a Gmail account, 
decide how to populate an email to send.
. Add a Gmail connection to an integration.
. For a Gmail connection that sends an email, optionally map integration
data to the email fields. 

Information and instructions are in the following topics:

* <<register-with-gmail>>
* <<create-gmail-connection>>
* <<alternatives-for-populating-email-to-send>>
* <<add-gmail-connection>>

include::register_with_gmail.adoc[leveloffset=+1]

include::create_gmail_connection.adoc[leveloffset=+1]

include::alternatives_for_populating_email_to_send.adoc[leveloffset=+1]

include::add_gmail_connection.adoc[leveloffset=+1]
