[id='connecting-to-slack']
= Connecting to Slack

As a business user, you can create an integration that connects to Slack. A 
connection to Slack can do either one of the following:

* Trigger execution of the integration when a Slack channel that you specify
receives a message. The integration passes the message to the next
step in the integration. For example, you can monitor a Slack channel 
for keyword instances such as product names. Upon finding messages that
contain those product names, the integration can notify the appropriate contact 
in a Gmail connection. 


* Deliver a message to a particular user or to a channel. For example, this 
behavior is useful when an integration downloads a file from an FTP server and 
processes it in some way. You can finish an integration by 
notifying a Slack channel or user that the process was successful.

To connect to Slack in an integration, create a Slack 
connection and then add the connection to an integration. 
Details are in the following topics:

* <<creating-slack-connections_{context}>>
* <<add-slack-connection-start_{context}>>
* <<add-slack-connection-middle-finish_{context}>>

include::creating_slack_connections.adoc[leveloffset=+1]

include::add_slack_connection_start.adoc[leveloffset=+1]

include::add_slack_connection_middle_finish.adoc[leveloffset=+1]
