[id='connecting-to-concur']
= Connecting to SAP Concur

ifeval::["{location}" == "upstream"]

SAP Concur manages business expenses, travel, and invoices. 
In an integration, you can connect to SAP Concur and perform
any one of 85 actions.  
For example, suppose that you store project codes in a SQL database and
you need the same project codes in SAP Concur so that expenses can be
associated with projects. You can create an integration that 
connects to your SQL database and runs a stored procedure that obtains
any new project codes. The integration can then connect to SAP Concur and
upload the new project codes to the appropriate list. 

endif::[]

ifeval::["{location}" == "downstream"]

SAP Concur manages business expenses, travel, and invoices. 
In an integration, you can connect to SAP Concur to obtain all 
lists, obtain a particular list, create a list, or update a list. 
There are additional, unsupported actions that a SAP Concur connection
can perform. See the note below. 

For example, suppose that you store project codes in a SQL database and
you need the same project codes in SAP Concur so that expenses can be
associated with projects. You can create an integration that 
connects to your SQL database and runs a stored procedure that obtains
any new project codes. The integration can then connect to SAP Concur and
upload the new project codes to the appropriate list. 

[IMPORTANT]
==== 
In this release, the SAP Concur connector is a 
https://access.redhat.com/support/offerings/techpreview/[Technology Preview feature].
====
endif::[]

See the following topics: 

* <<user-roles-for-connecting-to-concur>>
* <<obtain-concur-oauth-credentials-implementation>>
* <<obtain-concur-oauth-credentials-production>>
* <<configure-concur-connector>>
* <<create-concur-connection>>
* <<add-concur-connection>>
* <<identify-concur-fields-for-mapping>>


include::user_roles_for_connecting_to_concur.adoc[leveloffset=+1]

include::obtain_concur_oauth_credentials_implementation.adoc[leveloffset=+1]

include::obtain_concur_oauth_credentials_production.adoc[leveloffset=+1]

include::configure_concur_connector.adoc[leveloffset=+1]

include::create_concur_connection.adoc[leveloffset=+1]

include::add_concur_connection.adoc[leveloffset=+1]

include::identify_concur_fields_for_mapping.adoc[leveloffset=+1]
