[id='create-concur-connection']
= Create a SAP Concur connection

To create a connection to SAP Concur, you must have registered your
{prodname} environment as an application that can access SAP Concur.
If you registered a {prodname} environment with the SAP Concur
implementation site, then a SAP Concur connection can access only the
SAP Concur implementation site. If you registered a {prodname}
environment with the the SAP Concur production site, then 
a SAP Concur connection can access only the SAP Concur production site. 
If you did not already register {prodname}, see <<register-with-concur>>.

When you create a SAP Concur connection, you authorize the connection to access 
SAP Concur with the login credentials that you enter when you create
the connection. After you create a SAP Concur connection, you can 
add it to multiple integrations.

.Prerequisites

* You must know whether you want to create a connection to the SAP
Concur implementation site or the SAP Concur production site.
* You must have a user account for the SAP Concur site that you 
want to connect to. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. A connector is a template that
you use to create one or more connections.
. Click the *SAP Concur* connector.
. In the *Configure Connection* page, click *Connect SAP Concur*, 
which takes you to the SAP Concur site. 
+
If *Connect SAP Concur* does not appear, then your {prodname} installation
is not registered as a SAP Concur client application. See
<<register-with-concur>>. 
+
If `redirect_uri is improper or not previously registered` appears, then 
the registration is incorrect. Return to the {prodname} *Settings* page
to update and validate the registration. See <<register-with-concur>>. 

. On the SAP Concur site: 
.. Enter the email address for the SAP Concur account that you want
this connection to use to access SAP Concur. 
.. Ensure that *Username* is selected. 
.. Click *Continue*. 
.. Enter your SAP Concur password.
.. Click *Sign In*, which returns you to {prodname}. 

. In the {prodname} *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*SAP Concur Test1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample SAP Concur connection to the implementation site.*`
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *SAP Concur Test1* appears as a connection that you can 
choose to add to an integration.
