[id='create-rest-api-connection']
= Create an API client connection

To create a connection to a REST API:

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
available connectors.
. Click the connector for the API that you want to create a connection for.
. Respond to prompts for additional information. The
definition of the API determines what {prodname} prompts for.
For example, for an API that uses
HTTP Basic Authorization, {prodname} prompts for the user name and
password to use to access the API. For an API that uses OAuth,
{prodname} displays a button for you to click so that {prodname}
can verify its registration credentials for connecting to the API.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection.
. In the upper right, click *Create* to see that you can now
choose the connection you
created and add to an integration.
