[id='creating-kafka-connections']
= Create a connection to a Kafka broker

To create a Kafka connection:

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
connectors.  
. Click the *Kafka* connector.
. In the *Kafka bootstraps URI* field, enter a comma separated list
of Kafka broker URIs. Each URI should be in the form _host:port_.
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the input 
parameter and try again.
. If validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, you might enter `Kafka West`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. 
. In the upper right, click *Create* to see that the connection you 
created is now available. If you
entered the example name, you would 
see that *Kafka West* appears as a connection that you can 
choose to add to an integration. 
