[id='creating-slack-connections']
= Create a Slack connection

To create a connection to an instance of Slack:

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *Slack* connector.
. In the *Slack webhook URL* field, enter the webhook URL of the
Slack instance to send messages to. This is the only required parameter. 
. Optionally, enter values for additional parameters:
.. In the *Sending username for messages* field, enter the user name that 
the bot has when it sends messages to Slack.
.. In the *Message avatar emoji* field, specify one emoji, which the bot
uses as the message avatar when it sends a message. Examples:
*`:smile:`*, *`:wave:`*, *`:question:`*.
+
TIP: Search on *emoji cheat sheet* to see some emoji codes.
 
.. In the *Message avatar icon URL* field, specify the URL of 
the avatar that the bot uses when it sends messages to Slack. 

+
If you specify an emoji and an icon URL, then the integration uses the
icon URL. 
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the
connection configuration values and try again.
. If validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Slack for Company Sales*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection.
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *Slack for Company Sales* appears as a connection that you can 
choose to add to an integration.
