[id='identify-concur-fields-for-mapping']
= Map integration data fields to SAP Concur fields

In most integrations, you need to add a data mapping step before a 
connection to SAP Concur. In the data mapping step, you map data fields
that are available from previous integration steps to SAP Concur action
parameters. In the data mapper, the *Target* panel displays the
SAP Concur parameters for the action that you selected when you added
the SAP Concur connection to the integration. 

ifeval::["{location}" == "downstream"]
In this release, the 
https://developer.concur.com/api-explorer/v3-0/Lists.html[supported SAP Concur actions and their parameters] 
are: 

* Get all lists requires the `limit` and `offset` parameters.
* Get a single list requires the `id` parameter.
* Create a new list requires the `content`.
* Update a list requires the `id` and `content` parameters.

endif::[]

Suppose that an integration starts by executing a SQL stored procedure
that obtains new project codes. The integration finishes by adding
new project codes to SAP Concur. 
The following procedure provides an example of a data mapper step before
the SAP Concur connection. 

. In {prodname}, in the left panel, hover over the plus sign that is
between the database connection and the SAP Concur connection to display a pop-up in which
you click *Add a Step*.
. Click *Data Mapper*. When the data fields
appear, the *Sources* panel on the left displays the fields that are
available from the database connection. In this example, the
source fields include `concur-list-id` and `preject-code`.
The *Target* panel on the right displays the SAP Concur `id` and
`content` parameters for the update list action, which the connection
performs. 
. Map the `concur-list-id` source field to the `id` target field.
. Map the `project-code` source field to the `content` target field. 
. In the upper right, click *Done* to add the data mapper step to the integration. 
