[id='obtain-concur-oauth-credentials-production']
= Obtain SAP Concur production site OAuth credentials 

To obtain OAuth credentials that authorize {prodname} to access
the SAP Concur production site, go to the 
https://developer.concur.com/api-reference/authentication/getting-started.html[SAP Concur Developer Center Getting Started] 
page and follow the instructions there. 

////
. Obtain a new set of OAuth credentials that includes: 

** Client ID and client secret values that you will specify in the
{prodname} production environment *Settings* page to configure the 
{prodname} SAP Concur connector.

** The `LIST` scope. Optionally, to obtain permission to perform actions other 
than the list actions, ask for other 
https://developer.concur.com/api-reference/authentication/scopes.html[scopes]. 
** The `Authorization Grant Flow` grant type. 
+
To use a REST client, such as Postman, to send a request to
the SAP Concur production site, you need credentials with  
an OAuth grant type of `Password`.

. Provide the {prodname} callback URL for the environment 
that you want credentials for, which is something like this:
+
`\https://syndesis.my-minishift.syndesis.io/api/v1/credentials/callback`
+
In this URL, `syndesis.my-minishift.syndesis.io` matches the OpenShift
route to your {prodname} environment.
////
