// This module is included in the following assemblies:
// as_connecting-to-kudu.adoc

[id='add-kudu-connection-start_{context}']
= Obtain records from a Kudu data store 

To trigger execution of an integration based on receiving a record
from a Kudu data store, add a Kudu connection as the start connection. When 
the integration is running, the Kudu connection continuously watches for .... 
When the connection finds a ???,
it passes it to the next step in the integration. A Kudu 
connection handles one record at a time. 

.Prerequisite
You created a Kudu connection. 

.Procedure

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the Kudu connection that
you want to use to start the integration. 
. On the *Choose an Action* page, click the *????* action
to receive records from the table that you specify. 
. In the *Kudu table name* field, enter the name of the table
to poll. 
. Click *Done*. 

.Result
The connection appears in the integration flow 
in the location where you added it. 
