// This module is included in the following assemblies:
// as_connecting-to-kudu.adoc

[id='add-kudu-connection-add-record_{context}']
= Add a record to a Kudu table

In an integration, you can add a record to a Kudu table to finish
an integration. To do this, add a Kudu connection as the integration's 
finish connection. To add a record to a Kudu table in the
middle of integration, add a Kudu connection to an integration after
the start connection and before the finish connection. 

.Prerequisites
* You created a Kudu connection.
* You are creating or editing an integration.
* The integration already has a start connection. 

.Procedure

. On the *Choose a Finish Connection* page, do one of the following:
+
* To finish an integration by adding a record to a Kudu table, 
click the Kudu connection that you want to use. 
* To add a record to a Kudu table in the middle of 
an integration, click the connection that you
want to use to finish the integration. Configure that connection. When the
finish connection is part of the integration, in the left panel, hover over
the plus sign where you want to add a Kudu connection and click
*Add a connection*. Click the Kudu connection that you want to use
to add a record to a Kudu table in the middle of an integration. 

. On the *Choose an Action* page, click *Insert a row in a Kudu table*. 
. To configure the action, in the *Table* field, specify the name of the 
table to add a record to.

. Click *Done*. 

.Result
The connection appears in the integration flow 
in the location where you added it. 
