// This module is included in these assemblies:
// as_connecting-to-twitter.adoc

[id='adding-twitter-connection-start_{context}']
= Adding a Twitter connection to trigger integration execution

In a simple integration, the start connection can be a Twitter 
connection that triggers execution of the integration when one of the following 
occurs: 

* There is a tweet that mentions the Twitter handle for the 
Twitter account that the connection is authorized to access. 
* A periodic poll finds one or more direct messages sent to the  
Twitter account that the Twitter connection is authorized to access. 
A Twitter direct message is a private message explicitly sent to a 
user or group. 
* A periodic poll finds one or more tweets that contain a keyword 
that you specify. 

.Prerequisites
* You created a Twitter connection.
* You are creating or editing a simple integration and {prodname} is
prompting you to choose the start connection.

.Procedure

. Click the Twitter
connection that starts the integration. When the integration
uses the selected connection to connect to Twitter, {prodname} uses the
credentials defined in that connection.

. Select the action that you want the connection to perform.
A Twitter connection that you add to an integration performs only
the action that you choose:
+
*  *Mention* triggers execution of the integration when the connection 
finds a tweet that contains the Twitter handle for the Twitter 
account that the connection is authorized to access. The connection 
returns the tweet to the integration.
* *Retrieve* periodically polls Twitter for direct messages sent 
to the Twitter account that the Twitter connection is authorized 
to access, triggers execution of the integration upon finding
a direct message, and returns the direct message to the integration. 
* *Search* periodically polls Twitter for tweets that contain a keyword 
that you specify, triggers execution of the integration upon finding
such tweets, and returns those tweets to the integration. 

. Configure the action that you selected: 
+
* *Mention* does not require any configuration. 
* *Retrieve* 
** *Count* is the maximum number of direct messages to retrieve. 
Direct messages from only the previous 30 days can be returned. 
** *Delay* is the period of time between polls. Twitter enforces
rate limits, so you should not poll too often. The default 
interval is 5 seconds. 
** *Ignore direct messages previously found* returns only new 
messages when selected. 

* *Search*
** *Delay* is the period of time between polls. Twitter enforces
rate limits, so you should not poll too often. The default 
interval is 5 seconds. 
** *Ignore tweets previously found* returns only new 
tweets when selected. 
** *Keywords* is a comma separated list of words that you want 
the connection to monitor tweets for. The connection returns a tweet 
that contains at least one keyword. 

. Click *Done* to add the connection to the integration.

.Result
The connection appears at the beginning of the integration flow.
