// This module is included in these assemblies:
// as_connecting-to-twitter.adoc

[id='adding-twitter-connections_{context}']
= Adding a Twitter connection to trigger integration execution

In an integration, a connection to Twitter can retrieve the direct
messages of the last 30 days, send a direct message, trigger execution of
an integration when a tweet contains your Twitter handle or when
a tweet contains text that you have specified. A connection to
Twitter must be the integration's start connection.

.Prerequisites
* You created a Twitter connection.
* You must be creating or editing an integration and {prodname} is
prompting you to choose the start connection.

.Procedure

. Click the Twitter
connection that you want to add to the integration. When the integration
uses the selected connection to connect to Twitter, {prodname} uses the
credentials defined in that connection.

. Click the action that you want the selected connection to perform.
A Twitter connection that you add to an integration performs only
the action you choose.
+
*  *Mention* triggers execution of the integration when a tweet contains
your handle.
* *Search* triggers execution of the integration when a tweet contains
text that you specify.
* *Retrieve* get the direct messages of the last 30 days.
* *Send* send a direct message to a twitter user.

. Optionally, enter the configuration information that {prodname}
prompts for. For example, the *Search* action prompts you to specify
how often to search and keywords to search for.

. Click *Done* to add the connection to the integration.

.Result
The connection appears at the beginning of the integration flow.
