// This module is included in the following assemblies:
// as_connecting-to-google-calendar.adoc

[id='add-google-calendar-connection-add-event_{context}']
= Add an event to a Google calendar 

In an integration, you can add an event to a Google calendar 
in the middle of the integration or to finish the integration.  
To do this, add a Google Calendar connection to the middle of an integration 
or as the integration's finish connection. 

.Prerequisites
* A Google Calendar connection is available and this connection
is authorized to access the Google calendar to which you want to add an 
event.
* You are creating or editing an integration and {prodname} is prompting you 
to add a finish connection or select the connection that you want to add
in the middle of an integration. 

.Procedure
. Click a Google Calendar connection that is authorized to access
the calendar that you want to connect to.   
. On the *Choose an Action* page, click the *Create Event* action.

. Configure the *Create Event* action: 
+
.. Enter a title for the new event.
.. Enter the name of the Google Calendar to add the event to. 
.. For the other input parameters, you can enter data or you 
might want to map values from an event that you obtained in 
a previous Google Calendar connection. 

. Click *Done* to add the connection to the integration. 
The connection appears in the integration flow in the location where you added it. 
