// This module is included in the following assemblies:
// as_connecting-to-fhir.adoc

[id='adding-fhir-connection-create_{context}']
= Creating a resource on a FHIR server

In an integration, you can create and add a resource to a FHIR server.
When you configure the connection's *Create* action, you specify the 
type of the resource that you want to create. 
For example, you might add new patient resource to a FHIR server. 
To create a resource,  
add a FHIR connection to the middle of a flow, or as a simple 
integration's finish connection. 

When a connection performs the *Create* action to create a new resource on a FHIR server, 
the new resource has an automatically-generated FHIR resource ID. 
If you want to specify the resource 
ID for a new resource, instead of selecting the *Create* action choose the 
xref:adding-fhir-connection-update_fhir[*Update* action] for the connection to perform. 

.Prerequisites
* You created a connection to the FHIR server that you want to add 
a resource to. 
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is prompting you to add a finish connection. 

.Procedure

. Click the FHIR connection to the server that you want to add a resource to.  
. On the *Choose an Action* page, click *Create*. 
. Click in the *Resource Type* field to display a list
of FHIR resource types. Select or enter the type of resource
that you want to create.
. In the *Contained Resource Types* field, if the resource type 
that you want to create contains other resource types, select 
them. Use the *Ctrl* key if you need to select more than one. 
.  Click *Next* to add this connection to the flow. 

.Result
The connection appears in the integration flow 
in the location where you added it. During execution, the connection 
creates a new resource on the FHIR server.  
