// This module is included in the following assemblies:
// as_connecting-to-amazon-s3.adoc

[id='adding-s3-connection-start_{context}']
= Obtaining data from Amazon S3 to trigger integration execution

To start an integration by obtaining data from an Amazon S3 bucket, 
add an Amazon S3 connection as a simple integration's start connection.

.Prerequisite
You created an Amazon S3 connection.

.Procedure

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a connection* page, click the Amazon S3 connection that
you want to use to start the integration.
. On the *Choose an action* page, select the action that you
want the connection to perform:
+
* *Get Object* obtains a file from the bucket that the connection
accesses. In the *File Name* field, enter the name of the file that you want
to obtain. If the specified file is not in the bucket, it is a runtime error.

* *Poll an Amazon S3 Bucket* periodically obtains files from the bucket that the
connection accesses. To configure this action:
.. In the *Delay* field, accept the default of 500 milliseconds as the time
that elapses between polls. Or, to specify a different polling interval,
enter a number and select its time unit. 
.. In the *Maximum Objects to Retrieve* field, enter the largest number of files
that one poll operation can obtain. The default is 10.
+
To have no limit on the number of files that can be obtained, specify
`0` or a negative integer. When *Maximum Objects to Retrieve* is unlimited,
the poll action obtains all files in the bucket.
+
If the bucket contains more than the specified maximum number of files
then the action obtains the files that were most recently
modified or created. 
.. In the *Prefix* field, optionally specify a regular expression
that evaluates to a string. If you specify a
prefix then this action retrieves a file
only when its name starts with that string.

.. Indicate whether you want to  
*Obtain files and then delete them from the bucket*.

. After you configure the action, click *Next* to specify the action's output type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next*. 

.Result
The integration now has a start connection and {prodname} is prompting
you to choose the finish connection. 
