// This module is included in the following assemblies:
// as_connecting-to-fhir.adoc

[id='adding-fhir-connection-patch_{context}']
= Updating record fields on a FHIR server

In an integration, you can update individual fields in 
records that are on a FHIR server. All records that 
this connection updates must be of the same resource type. 
To do this, add a FHIR connection to the middle of a flow
or as a simple integration's finish connection. 

.Prerequisites
* You created a connection to a FHIR server.
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure

. Click the FHIR connection that you want to use
to update individual fields in records that are on a FHIR server. 
. On the *Choose an Action* page, click *Patch*. 
. Click in the *Resource Type* field to display a list
of FHIR resource types. Select or enter the resource type 
of the records whose fields you want to update. You can specify 
only one resource type. 
. In the *Number of Operations* field, specify the number of fields
that you want to update. 
. Leave the *Resource id* field blank if you want to map the value
from a previous step in the flow, which is typically what you want 
to do. Otherwise, specify the resource 
ID of the record whose fields you want to update. Each time this 
integration is executed, this connection updates the same record. 
. Leave the *JSON Patch* field blank if you want to map the value 
from a previous step in the flow. Otherwise, specify a JSON document  
that updates individual fields. The JSON document must have the 
format described in 
link:http://jsonpatch.com/[What is a JSON Patch?]. 
. Click *Done* to add this connection to the flow. 
. Optionally, add a data mapper step before this connection if
you want to map values for the resource ID and for the JSON patch:
.. In the flow visualization panel, click the plus sign that is
before the FHIR connection that you just added. 
.. On the *Choose a Step* page, click *Data Mapper*. 
In the *Target* panel, expand the folder to display three fields 
for `op`, `path`, and `value`.
.. Map ??? to the target `op` field, which defaults to `replace`.
.. Map ??? to the target `path` field. The path identifies the field 
that you want to update. In a path value, a number indicates the 
index of a list field, and a slash leads to a child field. For 
example, map this path `/name/1/given/1/value` to update the value 
of the given name field. 
.. Map ??? to the target `value`. This is the new value that you 
want the field to have. 
.. Click *Done* to add the data mapper step to the flow. 


.Result
The connection appears in the integration flow 
in the location where you added it.  
