// This module is included in the following assemblies:
// as_connecting-to-google-sheets.adoc

[id='add-google-sheets-connection-create-spreadsheet_{context}']
= Create a spreadsheet

In an integration, you can create a new spreadsheet in the middle of
an integration or to finish an integration. To do this, add a 
Google Sheets connection to the middle of an integration
or as the integration's finish connection.

.Prerequisites
* You created a Google Sheets connection that is authorized to
access the Google account in which you want to create the 
spreadsheet. 
* You are creating or editing an integration and {prodname} 
is prompting you to add the integration's finish 
connection or to add a middle connection. 

.Procedure

. Click a Google Sheets connection that is authorized to access
the Google account that you want to use to create the spreadsheet.
. On the *Choose an Action* page, click *Create spreadsheet*.
. To configure the *Create spreadsheet* action:
+
.. In the *Title* field, enter the title of the new spreadsheet.
.. In the *Time Zone* field, enter the time zone that the 
new spreadsheet should use, for example, `India Standard Time`, `Tokyo`.
.. In the *Locale* field, enter the locale of the 
new spreadsheet, for example, `Canada`, `Hong Kong`.

. Click *Done* to add the connection to the integration.
The connection appears in the integration visualization flow in the
location where you added it.

.Result
A connection that creates a spreadsheet returns the spreadsheet ID for 
the new spreadsheet. In subsequent integration steps, you can map 
this spreadsheet ID to the spreadsheet ID in a connection 
that accesses the new spreadsheet, for example, to update it. 
