// This module is included in the following assemblies:
// as_connecting-to-fhir.adoc

[id='adding-fhir-connection-transaction_{context}']
= Creating records of different resource types on a FHIR server

In an integration, you can create two or more records on a 
FHIR server and each record can be of a different resource type. 
For example, you can add a new patient record and a new provider
record in one connection to a FHIR server. To do this, 
add a FHIR connection to the middle of a flow, or as a 
simple integration's finish connection. 

.Prerequisites
* You created a connection to a FHIR server.
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is prompting you to choose a 
finish connection. 

.Procedure

. Click the FHIR connection that you want to use
to create and add new records to a FHIR server. 
. On the *Choose an Action* page, click *Transaction*. 
. In the *Included Resource Types* field, select the  
resource types that this connection can create. 
Use the *Ctrl* key to select multiple resource types. 
.  Click *Next* to add this connection to the flow. 
  
.Result
The connection appears in the integration flow 
in the location where you added it. During execution, the connection 
adds records to the FHIR server and returns a collection 
of objects. Each object represents a created record. 
The only field in each object is the resource ID for that record. 
