// This module is included in the following assemblies:
// as_connecting-to-google-calendar.adoc

[id='add-google-calendar-connection-update-event_{context}']
= Updating an event in a Google Calendar 

In an integration, you can update an event in a Google Calendar
in the middle of a flow or to finish a simple integration.  
To do this, add a Google Calendar connection to the middle of a flow 
or as a simple integration's finish connection. 

[IMPORTANT]
====
In this release, the *Update Event* action requires a value in each event 
field. In most if not all cases, this means that you must add a Google 
Calendar connection that 
link:{LinkFuseOnlineConnectorGuide}#add-google-calendar-connection-to-get-one-event_calendar[obtains the event that you want to update], 
then add the Google Calendar connection that updates the event, and then 
insert a data mapper step between the two Google Calendar connections. 
====

.Prerequisites
* You created a Google Calendar connection that 
is authorized to access the Google Calendar that has the event that
you want to update.
* In the flow, there is an earlier connection to Google Calendar 
and that connection obtains the event that you want to update. 
* You are creating or editing a flow and {prodname} is prompting you 
to add to the integration. Or, {prodname} is prompting you to choose a finish connection.  

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click a Google Calendar connection that is authorized to access
the calendar that has the event that you want to update.   
. On the *Choose an action* page, select *Update Event*. 
. To configure the *Update Event* action: 
+
.. Enter the title of the event that you want to update.
.. Enter content in each event field that you want to update.
Do not enter content in an event field when you want the content 
in that field to remain unchanged. 

. Click *Next* to add the connection to the flow. 
The connection appears in the integration visualization  
where you added it. 
. In the integration visualization, click the plus sign that is 
just before the connection that you just added. 
. Click *Data Mapper*. 
. In the data mapper, for each event field that remains the same in the 
updated event, map that field from the Google Calendar connection that 
obtained the event to the corresponding field in the Google Calendar 
connection that updates the event. 
+
Do not map fields that you are updating. If you map a field and also 
specify an update for that field when you configure the *Update Event* action, 
{prodname} uses the mapped value. 

. In the upper right, click *Done* to add the data mapper step. 
