// This module is included in these assemblies:
// as_connecting-to-ftp.adoc

[id='adding-ftp-finish-middle-connection_{context}']
= Upload files to an FTP or SFTP server

To finish an integration by uploading files to an FTP or SFTP server, 
add an FTP or SFTP connection as the integration's finish connection. You can also
upload files to an FTP or SFTP server in the middle of an integration. To
do this, add an FTP or SFTP connection as a middle connection.  

.Prerequisite
You created an FTP or SFTP connection. 

.Procedure

. Start creating the integration.
. Add and configure the start connection.
. On the *Choose a Finish Connection* page, do one of the following:
+
* To finish an integration by uploading files, click the FTP or SFTP connection that
you want to use. 
* To upload files in the middle of an integration, click the connection you
want to use to finish the integration. Configure that connection. When the
finish connection is part of the integration, in the left panel, hover over
the plus sign where you want to add an FTP or SFTP connection and click
*Add a connection*. Click the FTP or SFTP connection that you want to use
to upload files in the middle of an integration. 

. On the *Choose an Action* page, click *Upload*. 
. In the *File name expression* field, if you want to upload only one
particular file, then enter an 
http://camel.apache.org/simple.html[Apache Camel Simple language]
expression that resolves to a file name. This is the name of the
file that the action uploads to the server. 
You cannot specify a regular expression. To upload more than one
file, leave this field blank. 
. In the *FTP directory* field, enter the absolute or relative name of a server directory.
If the *File name expression* field contains an expression, 
then the connection stores the specified file in this directory. If the
*File name expression* field is blank, then the connection uploads to
this directory all files that were received from the previous integration step. 
. In the *If file exists* field, indicate the behavior when you are 
uploading a file that has the same path and name as a file that is on
the server. Accept the default, *Override*, to overwrite
the file that is on the server with the file that you are uploading. 
Or, select one of the following:
** *Append* adds the content in the file being uploaded to the file
that is on the server. 
** *Fail* throws `GenericFileOperationException`. The integration does
not enter an error state. 
** *Ignore* does not upload the file. The integration continues running
under the assumption that everything is okay.
** *Move* renames one of the files. 
** *TryRename* uploads the file with a temporary name and renames the
file to the desired name. This operation does not check for the 
existence of a file with the desired name, which makes the operation
faster on most servers than when existence checks are done. 
. In the *Temporary file prefix while copying* field, specify a string. 
The connection prepends this string to the name of a file while it is
being uploaded. 
This enables the connection to write to a temporary file on the 
server and then rename that temporary file to have the correct name. 
This is useful for reducing locks when uploading very large files.
. In the *Temporary file name while copying* field, specify a string. 
The connection renames a file being uploaded to have this name 
while it is being uploaded.
This enables the connection to write to a temporary file on the 
server and then rename that temporary file to have the correct name. 
This is useful for reducing locks when uploading very large files.

. Click *Next* to specify the action's input type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and then, at the bottom, click *Done*. You do not need to follow the rest of these
instructions. 
+
Otherwise, select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, suppose you are specifying a JSON schema for
vendors. You can specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization panel and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Done*. 

.Result
The connection appears in the integration flow 
in the location where you added it. 
