// This module is included in the following assemblies:
// as_connecting-to-amqp.adoc

[id='adding-amqp-connection-finish_{context}']
= Finish an integration by publishing AMQP messages

To finish an integration by publishing messages to an AMQP broker,
add an AMQP connection as the finish connection. 

.Prerequisites
* You created an AMQP connection to the broker that you want to publish
messages to.
* You are creating or editing an integration. 
* The integration has its the start connection.

.Procedure

. On the *Choose a Finish Connection* page, click the AMQP connection that
you want to use to finish the integration. 
. On the *Choose an Action* page, click *Publish messages* to
publish messages to the queue or topic you specify. 
. In the *Destination Name* field, enter the name of the queue or 
topic to send messages to. 
. For the *Destination Type*, accept *Queue* or select *Topic*. 
. Select *Persistent* to guarantee message delivery even if
a connection fails. 

. Click *Next* to specify the action's input and output type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and then, at the bottom, click *Done*. You do not need to follow the rest of these
instructions. 
+
Otherwise, select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, suppose you are specifying a JSON schema for
vendors. You can specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization panel and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Done*. 

.Result
The connection appears in the integration flow 
in the location where you added it. 
