// This module is included in the following assemblies:
// as_connecting-to-fhir.adoc

[id='adding-fhir-connection-delete_{context}']
= Deleting records from a FHIR server

In an integration, you can delete records from a FHIR server.
Each deleted record is the resource type that you specify. 
To do this, add a FHIR connection to the middle of a flow
or as a simple integration's finish connection. 

.Prerequisites
* You created a connection to a FHIR server.
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is prompting you to select a 
finish connection. 

.Procedure

. Click the FHIR connection that you want to use
to delete records from a FHIR server. 
. On the *Choose an Action* page, click *Delete*. 
. Click in the *Resource Type* field to display a list
of FHIR resource types. Select or enter the resource type 
of the records that you want to delete. 
. In the *Resource Id* field, if you want to obtain a particular 
record, enter its resource ID. Or, leave this field blank if you 
plan to map it from an earlier step in the integration. 
. In the *Resource version* field, if you specified a resource 
ID, then specification of a resource version is required. 
.  Click *Done* to add this connection to the flow. 

.Result
The connection appears in the integration flow 
in the location where you added it.  
