// This module is included in the following assemblies:
// as_connecting-to-irc.adoc

[id='adding-irc-connections-receive_{context}']
= Adding an IRC connection to trigger integration execution upon receiving messages

An IRC connection that starts an integration triggers execution of the 
integration when the connection finds private messages that are sent to an 
IRC nickname that you specify. 

.Prerequisites

* You created an IRC connection. 
* You have an IRC nickname for receiving and sending messages. 
* You are creating a simple integration and {prodname} is prompting you to 
choose how you want to start the integration. 

.Procedure

. Click the IRC connection that you want to use to start the integration. 
. Select the *IRC Receive Private Message* action.  
. In the *Channels* field, optionally specify one or more IRC channels 
separated with commas. 
. In the *Nickname* field, specify the IRC nickname that the 
integration uses. For any channels that you specify, this 
nickname joins the channel. During execution, the integration 
retrieves messages that are sent to this nickname and passes them
to the next step in the integration. 
. In the *NickServ Password* field, if the specified nickname has 
a password, enter it. 
. Click *Next* to specify the action's output type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next* to add the connection to the flow. 

.Result
The connection is a simple integration's start connection and 
{prodname} prompts you to choose the integration's finish connection. 
