// This module is included in the following assemblies:
// as_connecting-to-jira.adoc

[id='adding-jira-connection-add-comment_{context}']
= Adding a comment to a Jira issue

In the middle of a flow, or to finish a simple integration, 
you can connect to a Jira server to add a comment to an issue. 

.Prerequisites
* You created a Jira connection.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose
a simple integration's finish connection. 

.Procedure

. On the *Add to Integration* page, click the plus sign where you 
want to add a Jira connection. Skip this step if you are adding 
a simple integration's finish connection.  
. Click the Jira connection that you want the integration to use
to connect to a Jira server. 
. On the *Choose an Action* page, select *Add Comment*.
. In the *Comment* field, enter the comment that you want to 
add to the issue. 
. In the *Issue Key* field, enter the Jira identifier for the issue. 
Examples of issue keys: `GATEWAY-1234`, `Enterprise-239`. 
. Click *Next*. 

.Result
The connection appears in the integration flow 
in the location you added it. 
