// This module is included in the following assemblies:
// as_connecting-to-fhir.adoc

[id='adding-fhir-connection-create_{context}']
= Creating records on a FHIR server

In an integration, you can create and add records to a FHIR server.
Each new record is the resource type that you specify. 
For example, you can add new patient records to a FHIR server. To do this, 
add a FHIR connection to the middle of a flow, or as a simple 
integration's finish connection. 

.Prerequisites
* You created a connection to a FHIR server.
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is promping you to add a finish connection. 

.Procedure

. Click the FHIR connection that you want to use
to create and add new records to a FHIR server. 
. On the *Choose an Action* page, click *Create*. 
. Click in the *Resource Type* field to display a list
of FHIR resource types. Select or enter the resource type 
of the records that you want to create.
. In the *Contained Resource Types* field, if the resource type 
of the records that you want to add contains other resource types, select 
them. Use the *Ctrl* key if you need to select more than one. 
.  Click *Next* to add this connection to the flow. 

.Result
The connection appears in the integration flow 
in the location where you added it. During execution, the connection 
creates new records on the FHIR server. Each new record has an 
automatically-generated FHIR resource ID. If you want to specify the resource 
ID for a new record, instead of selecting the *Create* action, choose the 
*Update* action for the connection to perform. In the input to the connection 
that updates records, specify the resource ID. 
