// This module is included in the following assemblies:
// as_connecting-to-kudu.adoc

[id='add-kudu-connection-add-records_{context}']
= Inserting records into a Kudu table

In an integration, you can add records to a Kudu table in the middle 
of a flow or to finish
a simple integration. To do this, add a Kudu connection to the middle of 
a flow or as a simple integration's 
finish connection. 

.Prerequisites
* You created a Kudu connection.
* You are creating or editing an integration and {prodname} is
prompting you to add to the integration. Or, {prodname} is 
prompting you to choose a finish connection.  
* The table that you want to add records to exists. 

.Procedure
. On the *Add to Integration* page, click the plus sign where you 
want to add the connection. Skip this step if {prodname} is
prompting you to choose the finish connection. 
. Click the Kudu connection that you want to use. Note that when 
a Kudu connection inserts data, the connection does not return anything.  

. On the *Choose an action* page, select *Insert data into a Kudu table*. 
. To configure the action, in the *Table* field, specify the name of the 
table to add records to.
+
It is important for you to have an understanding of how the 
Kudu table that you are adding records to is set up. For example, 
a Kudu table that you are adding records to might have 
a unique key. If you try to add a record that contains a key value that
is already in the table, the Kudu connection does not add that record. 

. Click *Next*. 

.Result
The connection appears in the integration visualization where you added it. 

.Next steps
Consider whether you need to split a collection of records  
into individual records that a Kudu connection can add to a table.
To do this, add a split step to the integration. The split step 
executes the subsequent steps in the integration once for each record. 
Also, you probably need a data mapper step before a Kudu 
connection that adds records to a table. 
