// This module is included in the following assemblies:
// as_connecting-to-google-calendar.adoc

[id='add-google-calendar-connection-add-event_{context}']
= Adding an event to a Google calendar 

In an integration, you can add an event to a Google calendar 
in the middle of a flow or to finish a simple integration.  
To do this, add a Google Calendar connection to the middle of a flow 
or as a simple integration's finish connection. 

.Prerequisites
* A Google Calendar connection is available and this connection
is authorized to access the Google calendar to which you want to add an 
event.
* You are creating or editing a flow and {prodname} is prompting you
to choose a step. Or, {prodname} is prompting you to choose a finish connection. 

.Procedure
. Click a Google Calendar connection that is authorized to access
the calendar that you want to add an event to. 
. On the *Choose an Action* page, click the *Create Event* action.

. Configure the *Create Event* action: 
+
.. Enter a title for the new event.
.. Enter the name of the Google calendar to add the event to. 
.. For the other input parameters, you can enter data or you 
might want to map values from an event that you obtained in 
a previous Google Calendar connection. 

. Click *Done* to add the connection to the flow. 
The connection appears in the integration flow in the location where you added it. 
