// This module is included in the following assemblies:
// as_connecting-to-slack.adoc

[id='add-slack-connection-middle-finish_{context}']
= Add a Slack connection to send a message to a Slack channel or user

In an integration, you can send a message to a Slack channel or Slack user to
finish an integration or in the middle of an integration. 

.Prerequisites

* You created a Slack connection.
* You are creating or editing an integration. If you are creating an integration, then
{prodname} might be prompting you to choose a finish connection. 
To add a middle connection, hover over the plus
sign in the left panel in the location where you want to add the
connection and select *Add a connection*. 

.Procedure

. Click the Slack connection that you want to add to the integration. 
. Select the action that you want the connection to perform.
+
* Click *Username* to send a message to one user. To configure this action,
in the *User name* field, specify the Slack name of the user to send the message
to. 
* Click *Channel* to publish a message on a channel. To configure
this action, in the *Channel* field, specify the channel to publish 
the message to. 

. Click *Done* to add the connection to the integration. 
. Optionally, add additional connections to the integration. Whether 
additional connections are needed depends on what you want the integration
to do. The important point is to add all connections before you 
continue. 
. Add a data mapping step just before the Slack connection that you added
in this procedure. In the mapping step, map a string
from a data mapping source to the Slack *message* field. This string 
should contain the message that you want to send to the Slack
user or channel. See
link:{LinkFuseOnlineIntegrationGuide}#add-data-mapping-step_map[Add data mapping step].
