// This module is included in these assemblies:
// as_connecting-to-twitter.adoc

[id='adding-twitter-connection-finish-middle_{context}']
= Adding a Twitter connection that sends a direct message

In the middle of a flow, or to finish a simple integration, you can 
add a Twitter connection that sends a direct message to a Twitter 
user. A direct message is a private message that goes to 
only the specified user. 

.Prerequisites
* You created a Twitter connection.
* You are creating or editing a flow and {prodname} is
prompting you to add to the integration. Or, for a simple integration, 
{prodname} is prompting you to choose a finish connection.

.Procedure

. On the *Add to Integration* page, click the plus sign where you 
want to add a Twitter connection. 
. Click the Twitter
connection that you want to add to the integration. When the integration
uses the selected connection to connect to Twitter, {prodname} uses the
credentials defined in that connection.

. Select the *Send* action.

. In the *Default Message* field, enter the message that you want the 
connection to send when a data mapper step does not map 
the direct message content from a previous step to this Twitter connection. 
While you must enter a message when you configure this Twitter connection, 
a message that you map from a previous step has precedence over the 
message that you specify here. 

. In the *User* field, enter the Twitter handle of the user who you want 
to send a direct message to. For example, both *Aslan* and *@Aslan* are correct.

. Click *Next* to add the connection to the integration.

.Result
The connection appears in the middle or at the end of  
an integration visualization. 
