// This module is included in the following assemblies:
// as_connecting-to-jira.adoc

[id='adding-jira-connection-add-comment_{context}']
= Adding a comment to a Jira issue

In the middle of a flow, or to finish a simple integration, 
you can connect to a Jira server to add a comment to an issue. 

.Prerequisites
* You created a Jira connection.
* You are creating or editing a flow and {prodname} is prompting you
to add to the integration. Or, {prodname} is prompting you to choose
a simple integration's finish connection. 

.Procedure

. On the *Add to Integration* page, click the plus sign where you 
want to add a Jira connection. Skip this step if you are adding 
a simple integration's finish connection.  
. Click the Jira connection that you want the integration to use
to connect to a Jira server. 
. On the *Choose an action* page, select *Add Comment*.
. In the *Comment* field, enter the comment that you want to 
add to the issue or plan to add a data mapper step before this 
connection. In that data mapper step, map the comment from a 
previous integration step to this connection’s *comment* field.
. In the *Issue Key* field, enter the Jira identifier for the issue. 
Examples of issue keys: `GATE-1234`, `Ent-239`. 
. Click *Next*. 

.Result
The connection appears in the integration visualization
where you added it. 

.Next steps
To map the comment from a previous integration step to this connection, 
add the connection that provides the comment content and then add a 
data mapper step before this Jira connection. For example, suppose a 
database connection obtains customer records. In the data mapper step, map the
collection of customer records to the Jira connection’s *comment* field. 
