// This module is included in the following assemblies:
// as_connecting-to-dropbox.adoc

[id='adding-dropbox-connection-finish_{context}']
= Adding files to Dropbox to finish an integration

To finish an integration by uploading files to Dropbox,
add a Dropbox connection as the integration's finish connection.

.Prerequisites
* You created a Dropbox connection. 
* You are creating or editing an integration and {prodname} is prompting
you to choose the finish connection. 

.Procedure

. On the *Choose a connection* page, click the Dropbox connection that
you want to use to finish the integration. 
. On the *Choose an action* page, select the *Upload* 
action to add the current integration data to the
Dropbox account that this connection accesses. 
. In the *Remote Path* field, enter the 
local filename path for file that you want to upload. Dropbox stores the file with the 
same path and name. In this release, you can upload only a single file. 
. For the *Upload mode*:
+
* Select *Add* to upload a file only when a file with the same name is not already
in the same Dropbox folder. If a file with the same name is already
in the same Dropbox folder, then the file is not uploaded and the integration continues.
This is the behavior regardless of whether the content in the file you are trying to
upload has been updated. 
* Select *Force* to ensure that the file is uploaded even if a file with the
same name is present in the same Dropbox folder. Dropbox overwrites the file
that it already has with the file that you are uploading. 
. Click *Next* to specify the action's input type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next*. 

.Result
The connection appears at the end of the integration visualization. 
