// This module is included in the following assemblies:
// as_connecting-to-kudu.adoc

[id='add-kudu-connection-add-table_{context}']
= Add a table to a Kudu data store

In an integration, you can add a table to a Kudu data store to finish
an integration. To do this, add a Kudu connection as the integration's 
finish connection. To add a table to a Kudu data store in the
middle of integration, add a Kudu connection to an integration after
the start connection and before the finish connection. 

.Prerequisites
* You created a Kudu connection.
* You are creating or editing an integration.
* The integration already has a start connection. 

.Procedure

. On the *Choose a Finish Connection* page, do one of the following:
+
* To finish an integration by adding a table to a Kudu data store, 
click the Kudu connection that you want to use. 
* To add a table to a Kudu data store in the middle of 
an integration, click the connection that you
want to use to finish the integration. Configure that connection. When the
finish connection is part of the integration, in the left panel, hover over
the plus sign where you want to add a Kudu connection and click
*Add a connection*. Click the Kudu connection that you want to use
to add to add a table in the middle of an integration. 

. On the *Choose an Action* page, click *Create Kudu table*. 
. Configure the action as follows:
.. In the *Name* field, specify the name of the new table. 
.. In the *Columns* field, specify the names of the table columns by
using this format: 
+
_columnName1_,_type_;_columnName2_,_type_

.. In the *Buckets* field, specify an integer that indicates 
the number of buckets to use to distribute rows to different tablets 
by hash.
.. In the *Hashing key* field, specify the hashing key.

. Click *Done*. 

.Result
The connection appears in the integration flow 
in the location where you added it. 
