// Module included in the following assemblies:
// as_trigger-integration-with-timer.adoc

[id='add-timer-connection_{context}']
= Adding a timer connection to trigger integration execution

To trigger execution of an integration according to a schedule that
you specify, add a timer connection as a simple integration's start
connection. A timer connection cannot be in the middle of a
flow nor at the end of a flow. 

.Procedure

. In {prodname}, on the left, click *Integrations*.
. In the upper right, click *Create Integration*.
. On the *Choose a Start Connection* page, click the *Timer* connection. 
+
{prodname} provides a *Timer* connection; you do not need to create a timer
connection. However, if you inadvertently deleted the provided *Timer*
connection and created a new timer connection then you might have given it
a different name. 

. On the *Choose an Action* page, click *Cron Timer* or *Simple Timer*. 
+
* A `cron` timer requires a `cron` expression that specifies the
schedule for triggering integration execution. 
* A simple timer prompts you to specify a period and its time unit, 
for example, `5 seconds`, `1 hour`. Available units are 
milliseconds, seconds, minutes, hours, days. 
. According the type of timer that you are adding, enter a `cron` expression 
or a period with a selected time unit. 
. Click *Done* to add the *Timer* connection as the integration's 
start connection.  
