// This module is included in these assemblies:
// as_connecting-to-twitter.adoc

[id='adding-twitter-connection-start_{context}']
= Adding a Twitter connection to trigger integration execution

In a simple integration, the start connection can be a Twitter 
connection that triggers execution of the integration when one of the following 
occurs: 

* There is a tweet that mentions the Twitter handle for the 
Twitter account that the connection is authorized to access. 
* A periodic poll finds one or more direct messages sent to the  
Twitter account that the Twitter connection is authorized to access. 
A Twitter direct message is a private message explicitly sent to a 
user or group. 
* A periodic poll finds one or more tweets that 
match Twitter search criteria that you specify. 

.Prerequisites
* You created a Twitter connection.
* You are creating or editing a simple integration and {prodname} is
prompting you to choose the start connection.

.Procedure

. Click the Twitter
connection that starts the integration. When the integration
uses the selected connection to connect to Twitter, {prodname} uses the
credentials defined in that connection.

. Select the action that you want the connection to perform.
A Twitter connection that you add to an integration performs only
the action that you choose:
+
*  *Mention* monitors Twitter for tweets that contain the Twitter 
handle for the Twitter account that the connection is authorized to access.
Upon finding such a tweet, the connection returns it to {prodname}, which triggers
execution of the integration. 
* *Retrieve* periodically polls Twitter for direct messages sent 
to the Twitter account that the Twitter connection is authorized 
to access. Upon finding such messages, the connection returns them to {prodname}, 
which triggers execution of the integration.
* *Search*  periodically polls Twitter for tweets that match criteria 
that you specify. Upon finding such tweets, the connection returns them 
to {prodname}, which triggers execution of the integration. 

. Configure the action that you selected: 
+
* *Mention* does not require any configuration. 
* *Retrieve* 
** *Count* has a default of 100 and you should not need to change 
this value, which affects internal behavior. However, this value 
should never be less than 50. 
+
The *Retrieve* action always returns all previously unreturned 
direct messages received in the last 30 days. If you do not select 
*Ignore direct messages previously found*, then the *Retrieve* action 
returns all messages that have been received in the last 30 days.

** *Delay* is the period of time between polls. Twitter enforces
rate limits, so you should not poll too often. The default 
interval is 5 seconds. 
** *Ignore direct messages previously found* returns only new 
messages when selected. 

* *Search*
** *Delay* is the period of time between polls. Twitter enforces
rate limits, so you should not poll too often. The default 
interval is 5 seconds. 
** *Ignore tweets previously found* returns only new 
tweets when selected. 
** *Query* is a Twitter-formatted search expression that specifies 
the tweets that you want the connection to return. For example: 
+
`"My Product”` obtains tweets that contain an instance of `My Product`.
+
`My Product` obtains tweets that contain both `My` and `Product`, 
but not necessarily `My Product`.  
+
See link:https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators[Twitter document for search operators].

. Click *Done* to add the connection to the integration.

.Result
The connection appears at the beginning of the integration flow.
