// This module is included in the following assemblies:
// as_connecting-to-concur.adoc

[id='add-concur-connection_{context}']
= Add a SAP Concur connection to an integration

In an integration, a connection to SAP Concur is a middle or finish
connection and not a start connection. A connection to SAP Concur can perform
any one of 85 actions.  

.Prerequisites
* You created a SAP Concur connection.

* You are creating an integration or updating an integration to
add a connection to that integration. If you need to, see the 
link:{LinkFuseOnlineIntegrationGuide}#procedure-for-creating-an-integration_create[general procedure for creating an integration]
or see link:{LinkFuseOnlineIntegrationGuide}#updating-integrations_manage[updating integrations].

.Procedure
The instructions below
assume that {prodname} is prompting you to select a
finish connection or a middle connection.

. On the page that displays available connections, click the SAP Concur
connection that you want to add to the integration. When the integration
uses the connection that you select to connect to SAP Concur, {prodname}
uses the credentials defined in that connection.

. Click the action that you want the selected connection to perform.  Each
SAP Concur connection that you add to an integration performs only the action 
you choose.
+
For details about SAP Concur actions, visit the 
https://developer.concur.com/api-explorer/[SAP Concur developer center]
and expand *v3.0*.

. Click *Done* to add the connection to the integration.

.Result
The connection appears in the integration flow 
in the location where you added it. 
