// This module is included in the following assemblies:
// as_connecting-to-rest-apis.adoc

[id='add-api-client-connection_{context}']
= Add an API client connection to an integration

In an integration, to connect to a REST API, add a connection to that
REST API to the integration. 

In this release, in an integration, a connection to a REST API can be
the finish connection or a middle connection. It cannot be the
start connection. 
 
.Prerequisites
* You created a connection to the REST API.
* You are creating or editing an integration.
* The integration already has its start connection. 
* {prodname} is prompting you to select a finish connection
or a connection that is not the start connection.

.Procedure

. On the page that displays available connections, click the REST API
connection that you want to add to the integration.
. Click the action that you want the connection to perform.
The actions that are available are based on the resource operations
specified in the OpenAPI file that was uploaded to {prodname} and that
describes the API you are connecting to.
. Depending on the action you select, enter any parameters that
{prodname} prompts for.
. Click *Done*.

.Result
The connection appears in the integration flow 
in the location where you added it. 
 
