// This module is included in the following assemblies:
// as_connecting-to-dropbox.adoc

[id='adding-dropbox-connection-start_{context}']
= Obtaining files from Dropbox to trigger integration execution

To start an integration by downloading files from Dropbox, 
add a Dropbox connection as the start connection.

.Prerequisite
You created a Dropbox connection. 

.Procedure

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a connection* page, click the Dropbox connection that
you want to use to start the integration. 
. On the *Choose an action* page, select the *Download* action
to obtain one or more files from the Dropbox account that this connection
accesses. 
. To configure the action, in the *Folder or file name path to download* field,
specify the filename path for the content that you want
the integration to obtain. In this release, you can download only a single
file. 
. Click *Next* to specify the action's output type. 

. In the *Select Type* field, if the data type does not need to be known, 
accept *Type specification not required* 
and click *Next*. You do not need to follow the rest of these
instructions. 
+
Otherwise, click in the *Select Type* field and select one of the following as the schema type:
+
* *JSON schema* is a document that describes the structure of JSON data.
The document's media type is `application/schema+json`. 
* *JSON instance* is a document that contains JSON data. The document's 
media type is `application/json`. 
* *XML schema* is a document that describes the structure of XML data.
The document's file extension is `.xsd`.
* *XML instance* is a document that contains XML data. The
document's file extension is `.xml`. 

. In the *Definition* input box, paste a definition that conforms to the
schema type you selected. 
For example, if you select *JSON schema* then you would paste the content of
a JSON schema file, which has a media type of `application/schema+json`.

. In the *Data Type Name* field, enter a name that you choose for the
data type. For example, if you are specifying a JSON schema for
vendors then you might specify `*Vendor*` as the data type name. 
+
You will see this data type name when you are creating 
or editing an integration that uses the connection
for which you are specifying this type. {prodname} displays the type name
in the integration visualization and in the data mapper. 

. In the *Data Type Description* field, provide information that helps you
distinguish this type. This description appears in the data mapper when 
you hover over the step that processes this type. 
. Click *Next*. 

.Result
The connection starts the simple integration and {prodname} prompts
you to choose the finish connection. 
