// This module is included in the following assemblies:
// as_connecting-to-concur.adoc

[id='configure-concur-connector_{context}']
= Configure the SAP Concur connector

To connect to SAP Concur in an integration, you must configure the
{prodname} SAP Concur connector. You can then use the connector
to create a connection to SAP Concur.

.Prerequisites
 
* You know whether you want to configure the SAP Concur connector to
access the SAP Concur implementation site or the SAP Concur
production site. 

* You obtained OAuth credentials that authorize your {prodname} 
environment to access the appropriate SAP Concur site.

.Procedure

. In {prodname}, in the left panel, click *Settings*.
. On the *Settings* page, expand the *SAP Concur* entry. 
. In the *Client ID* field, enter the client ID that you received from
SAP Concur.
. In the *Client Secret* field, enter the client secret that you received
from SAP Concur. 
+
{prodname} populates the other fields. 

. Click *Save*. 
+
{prodname} immediately tries to validate the configuration. 
If validation is not successful, correct the input values and try again. 
If validation is successful, you can create a SAP Concur connection,
which you can add to an integration. 

.Next steps
To create a SAP Concur connection, click the *create a connection* link
in the success message. Or, to create a connection later, click *Ok* to 
contract the SAP Concur entry in the *Settings* page. 

 
