// This module is included in the following assemblies:
// as_connecting-to-jira.adoc

[id='creating-jira-connections_{context}']
= Creating a Jira connection

In an integration, to obtain, create, or update a Jira issue, create a 
Jira connection, which you then add to an integration. You can add the 
same connection to any number of integrations. 

.Prerequisites
* You registered your {prodname} environment as an application that can
access the Jira server that you want the integration to connect to. 

.Procedure

. In {prodname}, in the navigation panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. 
. Click the *Jira* connector.

. In the *Jira URL* field, enter the URL for the Jira server that 
you want an integration to connect to, for example, `https://my_server:8080`.

. If this Jira server uses basic authentication: 
.. In the *User name* field, enter a Jira user name. The connection 
uses this account to operate on the specified Jira server. 
.. In the *Password* field, enter the specified's user's password. 

+ 
Skip the next step if the Jira server does not use OAuth authentication. 
. If the Jira server uses OAuth authentication: 
.. In the *Access Token* field, enter the access token that the Jira
server provided during the procedure for registering your 
{prodname} environment as a Jira client. 
.. In the *Consumer Key* field, enter the consumer key that the Jira 
server provided during the registration procedure. 
.. In the *Private Key* field, enter the private key that was 
generated by the client to encrypt the conversation 
the server.
.. In the *Verification Code* field, enter the 
verification code that Jira generated during the registration procedure. 
  
. Click *Validate*. {prodname} displays a message that indicates whether
it can validate this connection. If validation fails, try again and 
be sure to enter the correct values. 
. When validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Jira Connect 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Jira connection
that uses the jkim account.*`
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *Jira Connect 1* appears as a connection that you can 
choose to add to an integration.
