// This module is included in these assemblies:
// as_connecting-to-gmail.adoc

[id='create-gmail-connection_{context}']
= Create a Gmail connection 

When you create a Gmail connection, you authorize the connection to access one
particular Gmail account. After you create a Gmail connection, you can 
add it to multiple integrations.

.Prerequisite
You registered your {prodname} environment as a Gmail client application. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. A connector is a template that
you use to create one or more connections.
. Click the *Gmail* connector.
. In the *Configure Connection* page, click *Connect Gmail*, 
which takes you to a *Sign in with Gmail* page.
+
If *Connect Gmail* does not appear, then your {prodname} environment
is not registered as a Gmail client application. See
link:{LinkFuseOnlineConnectorGuide}#register-with-gmail_gmail[Register with Gmail].
When you try to create a Gmail connection and your {prodname} environment 
is not registered as a Gmail client application, then {prodname} displays
multiple fields that prompt for authorization information. While you can
create a Gmail connection by entering values in these fields, 
you should register with Gmail first, and then create a Gmail connection
after registration is in place. 
. In the page that is prompting you to sign in to Gmail, 
enter the email address of the Google account that you want this connection to
access from {prodname} and click *Next*. 
. In response to *openshiftapps.com wants to access your Google Account*, 
click *Allow* to return to {prodname}.
. In the {prodname} *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Gmail Connect 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Gmail connection
that uses jkim Gmail account credentials.*`
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *Gmail Connect 1* appears as a connection that you can 
choose to add to an integration.
