// This module is included in the following assemblies:
// as_connecting-to-google-sheets.adoc

[id='create-google-sheets-connection_{context}']
= Create a Google Sheets connection

When you create a Google Sheets connection, you authorize the connection to access
the Google Sheets that are associated with one
particular Google account. After you create a Google Sheets connection, you can
add it to multiple integrations.

.Prerequisite
You registered your {prodname} environment as a Google client
application as described in
link:{LinkFuseOnlineConnectorGuide}#register-with-google-sheets_google-sheets[Register as a Google Sheets client application].

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
the available connectors. A connector is a template that
you use to create one or more connections.
. Click the *Google Sheets* connector.
. In the *Configure Connection* page, click *Connect Google Sheets*,
which takes you to a Google sign-in page.
+
[NOTE]
====
If *Connect Google Sheets* does not appear, then your {prodname} environment
is not registered as a Google client application with the Google Sheets API
enabled. See
link:{LinkFuseOnlineConnectorGuide}#register-with-google-sheets_google-sheets[Register as a Google Sheets client application].
When your environment is not registered with
Google, then when you try to create a Google Sheets connection, {prodname} displays
multiple fields that prompt for authorization information. While you can
create a Google Sheets connection by entering values in these fields,
you should register with Google first, enable the Google Sheets API,
and then create a Google Sheets connection.
====
. In the Google sign-in page,
select the Google account that you want this connection to
access from {prodname} and click *Next*.
. In response to the *openshiftapps.com wants to access your Google Account*
prompt, click *Allow* to return to {prodname}.
. In the {prodname} *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from other connections.
For example, enter `*Google Sheets Work Connection*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample Google Sheets connection
that uses my Google work account.*`
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *Google Sheets Work Connection* appears as a connection that you can
choose to add to an integration.
