// This module is included in the following assemblies:
// as_connecting-to-servicenow.adoc

[id='create-servicenow-import-set_{context}']
= Creating an import set in ServiceNow

In a {prodname} integration, a ServiceNow connection cannot directly 
update a ServiceNow table. To update ServiceNow data in an integration, 
a prerequisite is an import set that stages updates for a ServiceNow table. 

Often, the easiest way to create an import set is for
a ServiceNow administrator to create a ServiceNow 
inbound web service. This implicitly creates a ServiceNow import set. The 
import set is based on the ServiceNow target table that the administrator 
selects when creating the web service. A ServiceNow connection updates 
this import set, and ServiceNow uses the import set to update the 
corresponding ServiceNow table.

.Prerequisites
You must have ServiceNow administrative privileges. 

.Procedure in ServiceNow

. In ServiceNow, search for `web services`. 
. In the results, under *System Web Services* > *Inbound*, click *Create New*. 
. In the *Create Web Service* page:
.. In the *Label* field, specify the display name for the web service. 
The web service's import set will also have this name. 
.. In the *Target table* field, select the ServiceNow table that this service updates. 
.. Select *Copy fields from target table*. This creates an import set that has 
the same schema as the target table. The import set is a staging area for 
updating the target table.
.. Select *Create transform map*. This map enables ServiceNow to copy and 
transform data from the import set to the target table. 

. Click *Create*. 
. In the next display, under *Related Links*, click *Auto Map Matching Fields* to 
display a list of fields in the target table that you selected. 
. Select one target table field to be the correlation (or coalesce) field. 
+
When the value of the correlation field in a record in the import set 
matches the value of a correlation field in the target table, 
ServiceNow updates that record in the target table rather than creating a new record. 

. Select *Coalesce* to identify the field that you just selected
as the correlation field. Without a correlation field, ServiceNow adds each 
record in the import set to the target table.
. Click *Update*.
. Confirm that the transform map was created:
.. In ServiceNow, search for `transform map`. 
.. Under *System Import Sets*, click *Transform Maps* to display a list of transform maps. 
.. In this list, confirm that there is a transform map whose name is 
the value that you specified for the label of the web service that you created. 

.Additional resource
link:https://docs.servicenow.com/bundle/london-platform-administration/page/administer/import-sets/reference/import-sets-landing-page.html[ServiceNow documentation for import sets]
