// This module is included in the following assemblies:
// as_connecting-to-servicenow.adoc

[id='create-servicenow-web-service_{context}']
= Create a ServiceNow inbound web service

In a {prodname} integration, a ServiceNow connection cannot directly 
update a ServiceNow table. To update a ServiceNow table in an integration, 
you must create a ServiceNow inbound web service, which creates a ServiceNow 
info set that is based on the ServiceNow table that you select. A ServiceNow 
connection updates this info set, and ServiceNow uses the info set to 
update the corresponding ServiceNow table. 

.Prerequisites
You must have ServiceNow administrative privileges. 

.Procedure

. In ServiceNow, search for `web services`. 
. In the results, under *System Web Services* > *Inbound*, click *Create New*. 
. In the *Create Web Service* page, enter the required information, including:
.. In the *Label* field, specify the display name for the web service. The web service's info set will also have this name. 
.. In the *Target table* field, select the ServiceNow table that this service updates. 
.. Select *Copy fields from target table*. This creates an import set that is a clone of the target table. 
.. Select *Create transform map*. This enables ServiceNow to copy and transform data from the info set to the target table. 

. Click *Create* to create the web service. 
. In the next display, under *Related Links*, click *Auto Map Matching Fields* to 
display a list of fields in the target table that you selected. 
. Select one target table field to be the correlation field. 
+
When the value of the correlation field of a record in the info set 
matches the value of a correlation field in the target table, 
ServiceNow updates that record in the target table rather than creating a new record. 

. Select the *Coalesce* checkbox to identify the field that you just selected
as the correlation field. 
. Update the web service.
. Confirm that the transform map was created:
.. In ServiceNow, search for `transform map`. 
.. Under *System Import Sets*, click *Transform Maps* to display a list of transform maps. 
.. In this list, confirm that there is a transform map whose name is 
the value that you specified for the label of the web service that you created. 
