// This module is included in the following assemblies:
// as_connecting-to-fhir.adoc

[id='creating-fhir-connections_{context}']
= Creating a connection to a FHIR server

In an integration, to operate on FHIR resources, 
create a connection to a FHIR server and then add that connection to an 
integration.

.Prerequisite
You must know the URL for the FHIR server that you want to connect to. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
connectors.  
. Click the *FHIR* connector.
. In the ** field, enter .
. In the ** field, enter .
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the input 
parameter and try again.
. If validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, you might enter `FHIR West`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. 
. In the upper right, click *Create* to see that the connection you 
created is now available. If you
entered the example name, you would 
see that *FHIR West* appears as a connection that you can 
choose to add to an integration. 
