// This module is included in the following assemblies:
// as_connecting-to-kafka.adoc

[id='creating-kafka-connections_{context}']
= Creating a connection to a Kafka broker

In an integration, to subscribe for data from a Kafka topic 
or publish data to a Kafka topic, 
create a connection to Kafka and then add that connection to an 
integration.

[IMPORTANT]
In this release, connections to Kafka do not support SSL. 
It is expected that this will change in a future release.

.Prerequisite
You must know the URI for the Kafka broker that you want to connect to. 

.Procedure

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
connectors.  
. Click the *Kafka* connector.
. In the *Kafka bootstraps URI* field, enter a comma separated list
of Kafka broker URIs. Each URI should be in the form _host:port_.
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the input 
parameter and try again.
. If validation is successful, click *Next*.
. In the *Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, you might enter `Kafka West`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. 
. Click *Save* to see that the connection you 
created is now available. If you
entered the example name, you would 
see that *Kafka West* appears as a connection that you can 
choose to add to an integration. 
