// This module is included in the following assemblies:
// as_connecting-to-concur.adoc

[id='identify-concur-fields-for-mapping_{context}']
= Example of mapping integration data fields to SAP Concur fields

In most integrations, you need to add a data mapping step before a 
connection to SAP Concur. In the data mapping step, you map data fields
that are available from previous integration steps to SAP Concur action
parameters. In the data mapper, the *Target* panel displays the
SAP Concur parameters for the action that you selected when you added
the SAP Concur connection to the integration. 

Suppose that an integration starts by executing a SQL stored procedure
that obtains new project codes. The integration finishes by adding
new project codes to SAP Concur. 
The following procedure provides an example of a data mapper step before
the SAP Concur connection. The integration visualization displays  
and {prodname} is prompting you to add to the integration.  

. In the integration visualization, click the plus sign that is 
before the SAP Concur finish connection. 
. Click *Data Mapper*. When the data fields
appear, the *Sources* panel on the left displays the fields that are
available from the database connection. In this example, the
source fields include `concur-list-id` and `project-code`.
The *Target* panel on the right displays the SAP Concur `id` and
`content` parameters for the update list action, which the connection
performs. 
. Map the `concur-list-id` source field to the `id` target field.
. Map the `project-code` source field to the `content` target field. 
. In the upper right, click *Done* to add the data mapper step to the integration. 
