// This module is included in the following assemblies:
// as_connecting-to-concur.adoc

[id='obtain-concur-oauth-credentials-implementation_{context}']
= How to Obtain SAP Concur implementation site OAuth credentials

To obtain credentials for accessing the SAP Concur implementation site, 
contact SAP Concur directly and tell them:

* You want to register {prodname} as a new app that is authorized to
access the SAP Concur implementation site.
* You want a new set of OAuth credentials for their implementation site. 
* The credentials must include the `LIST` scope. 
* Optionally, to obtain permission to perform actions other than
the list actions, ask for other 
https://developer.concur.com/api-reference/authentication/scopes.html[scopes]. 
* The OAuth grant type for these credentials should be 
`Authorization Grant Flow`.
+
To use a REST client, such as Postman, to send a request to
the SAP Concur implementation site, you need credentials with  
an OAuth grant type of `Password`.

* The {prodname} callback URL for the environment that that you
want credentials for, which is something like this:
+
`\https://syndesis.my-minishift.syndesis.io/api/v1/credentials/callback`
+
In this URL, `syndesis.my-minishift.syndesis.io` matches the OpenShift
route to your {prodname} environment.

The response from SAP Concur should provide: 

* A username and password for logging in to the SAP Concur implementation
site. 
* Client ID and client secret values that you will specify in the
{prodname} development environment *Settings* page to configure the 
{prodname} SAP Concur connector.
