[id='prerequisites-for-creating-s3-connection']
= Prerequisites for creating an Amazon S3 connection

To create an Amazon S3 connection, you must know the
following:

* Amazon S3 access key ID that is associated with
the Amazon Web Services (AWS) account
that created, or will create, the bucket that you want the connection to access.
+
You can create a connection that accesses a bucket that does not
yet exist. In this case, when the integration starts running then
it use the AWS account associated with this access key ID to try to create
the bucket.
* Amazon S3 secret access key that is associated with the AWS account
that created or will try to create (when the integration starts running)
the bucket that you want the connection to access.
* Name of the bucket that you want to access or its Amazon Resource Name (ARN).
+
If the bucket you specify does not yet exist then the connection
tries to create a bucket with the name that you specify.  
Because S3 allows a bucket to be used as a URL that can be accessed publicly, 
the bucket name that you specify must be globally unique. Also, it must meet
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html[S3 bucket naming requirements].
+
If the bucket you specify does not exist in the AWS account that is
associated with the Amazon S3 access key ID, but it does exist in another
AWS account, then the connection does not create the bucket and an
integration that uses this connection cannot start running. 

* Region in which the bucket is located or the region in which you want
the connection to create the bucket.

A user with the login credentials for the AWS account that created or will
create the bucket obtains the Amazon S3 keys as follows:

. Go to https://aws.amazon.com/s3/.
. Hover over *My Account*, select *AWS Management Console* and sign in to the console
with the AWS account that created the bucket that
you want to access or with
the account that you want the connection to use to create the bucket.
. In the console, in the upper right, click the down arrow next to
the user name and click *My Security Credentials*.
. Expand *Access Keys* and click *Create New Access Keys*.
. Follow the prompts to obtain the keys.
