// This module is included in the following assemblies:
// as_triggering-integrations-with-http-requests.adoc

[id='about-json-schema-for-http-requests_{context}']
= About the JSON schema for specifying request parameters

In an integration, you typically map header and query parameters
in the HTTP request to data fields that the next connection in the
integration can process. To make this possible, when you add the Webhook
connection to the integration, specify the output data type in a JSON schema
that has the following structure:

[source,json]
----
{
  "$schema": "http://json-schema.org/schema#",
   "id": "io:syndesis:webhook",
   "type": "object",
   "properties": {
      "parameters": {
         "type": "object",
         "properties": { <1>
         }
      },
      "body": {
         "type": "object",
         "properties": { <2>
         }
      }
   }
}
----

To add the data structures that you need, in the JSON instance for your HTTP request:

<1> Specify query parameters in the `properties` section under the `parameters` object.
<2> Specify the HTTP body schema in the `properties` section under the `body` object.

While all data that an HTTP client sends is available in the integration,
when a Webhook connection's data shape conforms to this JSON schema,
then query parameters and body content are available for mapping.

For examples, see
link:{LinkFuseOnlineConnectorGuide}#how-to-specify-request_webhook[How to specify HTTP requests].
