[id='user-roles-for-connecting-to-concur']
= User roles for connecting to SAP Concur

SAP Concur has an implementation site for development work and a production
site for live use. The implementation site simulates 
the production site. This lets you create and refine an integration
before you use it in production with the live SAP Concur site. 

At any one time, a {prodname} environment can connect to the SAP Concur implementation site 
or the SAP Concur production site. In other words, a particular 
{prodname} environment does not support connections to both SAP Concur
sites at the same time. Each {prodname} environment requires its own 
credentials for accessing each SAP Concur site and the credentials for 
the implementation site are different from the credentials for the
production site. 

Consequently, the expectation is that someone in a system administrator-like
role would do the following for each {prodname} environment:

. Obtain credentials from SAP Concur for access to the SAP Concur sites. 
. Configure the SAP Connector to access the SAP Concur implementation site
or the SAP Concur production site. 
. Create a SAP Concur connection. 

A business user can then create an integration that uses the 
SAP Concur connection. The system administrator needs to tell the
business user needs whether the connection
is accessing the SAP Concur implementation site or the SAP Concur
production site. However, the procedure for adding a SAP Concur
connection to an integration is the same for both sites. 
