package com.redhat.ipaas.connector.http.springboot;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * iPaaS HTTP connector
 * 
 * Generated by camel-connector-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "http-get")
public class HttpGetConnectorConfiguration {

    /**
     * To use either HTTP or HTTPS
     */
    private String scheme = "http";
    /**
     * The hostname of the HTTP server
     */
    private String hostname;
    /**
     * The port number of the HTTP server
     */
    private Integer port;
    /**
     * The context-path
     */
    private String path;

    public String getScheme() {
        return scheme;
    }

    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    public String getHostname() {
        return hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }
}