@startuml

[*] --> Draft : New
[*] --> Draft : Change existing integration
Draft --> [*] : Delete
Draft -right-> Active : Publish
Draft: Used for design\nand and changing integrations

Active -right-> Inactive : Resume
Active: Integration is running
Inactive -left-> Active : Suspend
Inactive: Integration has been stopped,\nbut pod still running
Inactive --> Undeployed : Undeploy

Active --> Error
Error --> Active
Error: Error occured when running / publishing
Error -right-> Undeployed
Draft --> Error

Undeployed: No pod running
@enduml
