package com.redhat.ipaas.connector.salesforce.springboot;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * The salesforce connector is used for integrating Camel with the massive
 * Salesforce API.
 * 
 * Generated by camel-connector-maven-plugin - do not edit this file!
 */
@ConfigurationProperties(prefix = "camel.connector.salesforce-upsert-contact")
public class SalesforceUpsertContactConnectorConfiguration {

    /**
     * Salesforce login URL defaults to https://login.salesforce.com
     */
    private String loginUrl = "https://login.salesforce.com";
    /**
     * Salesforce connected application Consumer Key
     */
    private String clientId;
    /**
     * Salesforce connected application Consumer Secret
     */
    private String clientSecret;
    /**
     * Salesforce connected application Consumer token
     */
    private String refreshToken;

    public String getLoginUrl() {
        return loginUrl;
    }

    public void setLoginUrl(String loginUrl) {
        this.loginUrl = loginUrl;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }
}