apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syndesises.syndesis.io
  labels:
    app: syndesis
spec:
  group: syndesis.io
  names:
    kind: Syndesis
    listKind: SyndesisList
    plural: syndesises
    singular: syndesis
  scope: Namespaced
  version: v1beta2
  versions:
    - name: v1beta2
      served: true
      storage: true
    - name: v1beta1
      served: true
      storage: false
    - name: v1alpha1
      served: true
      storage: false
  additionalPrinterColumns:
    - JSONPath: .status.phase
      description: The syndesis phase
      name: Phase
      type: string
    - JSONPath: .status.version
      description: The syndesis version
      name: Version
      type: string
