// Module included in the following assemblies:
// trigger_integrations_with_api_calls.adoc

[id='about-api-provider-endpoints_{context}']
= About API Provider endpoints

After you publish an integration that starts with an API Provider 
connection, {prodname} provides the external URL for your REST API
service. This is where {prodname} publishes your REST API service. This 
external URL is the base URL for calls to your REST API service endpoints. 
{prodname} displays this URL in the integration's summary page.

In an integration, each operation that the OpenAPI specification defines has its own 
integration flow. Consequently, each operation can also have its own 
REST API service endpoint. Each endpoint is defined by the base URL 
and optionally by a subpath. REST API calls that trigger execution of a particular 
integration flow specify that operation's endpoint. 

Your OpenAPI specification determines which HTTP commands (such as 
`GET`, `POST`, `DELETE` and so on) you can specify
in calls to your REST API service endpoints. Examples of calls to 
API Provider endpoints are in the 
link:{LinkFuseOnlineIntegrationGuide}#try-api-provider-quickstart_{context}[instructions for trying out the API Provider quickstart].   
