[id='about-connections']
= About {prodname} connections

Before you can create an integration, you must create a connection
to each application or service
that you want to obtain data from or send data to. 
To create a connection,
you select a connector and add configuration information. 
For example, to connect to an AMQ broker in an integration, you create
a connection by selecting the AMQ connector,
and then following prompts to identify the broker to connect to and the
account to use for the connection.

A connection is one specific instance of the connector that
it is created from. You can create any number of connections
from one connector. For example,
you can use the AMQ connector to create three AMQ connections where
each connection accesses a different broker. 

To create an integration, you select a connection to start the integration,
a connection to end the integration, and optionally one or more
connections for accessing additional applications.
Any number of integrations can use the same connection. A particular
integration can use the same connection more than once. 

For details, see <<connecting-to-applications>>.
