[id='about-api-client-connectors']
= Requirements for API client connectors

After you upload an OpenAPI specification to {prodname}, a connector to the API
becomes available. An integrator can select the connector, create
an API client connection, and then add that connection to an integration.

When {prodname} creates an API client connector, it maps each resource
operation in the OpenAPI specification to an action. The action name
and action description comes from documentation in the OpenAPI specification.

{prodname} connectors support OAuth 2.0 and HTTP Basic
Authorization. If access to the API requires Transport Layer Security (TLS)
then the API needs to use a valid certificate that is issued by
a recognized Certificate Authority (CA).

An API that uses OAuth must have an authorization URL that takes a client
callback URL as input. For {prodname} to obtain authorization to access an
API that uses OAuth, you provide the {prodname} callback URL at the client
API authorization URL. The details for doing this are described in
{LinkFuseOnlineConnectorGuide}#connecting-to-rest-apis[{NameOfFuseOnlineConnectorGuide}, Connecting to REST APIs].

{prodname} cannot create connectors for APIs that support the HTTP 2.0
protocol.
