[id='add-database-connection']
= Add a database connection to an integration

You must create a database connection before you can add a database
connection to an
integration. If you did not already create the database connection,
see <<create-database-connection>>.

The procedure for adding a database connection varies according to
whether you want access the database

* To start an integration
* To finish an integration or in the 
middle of the integration

== Starting an integration by accessing a database

To start an integration by accessing a database:

. In the {prodname} panel on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click the
database connection that you want to use to start an integration.
. On the *Choose an Action* page, click one of the following:
+
* *Periodic SQL Invocation* obtains data by periodically invoking the
SQL query you specify.
* *Periodic Stored Procedure* obtains data by periodically invoking
the stored procedure you specify or select.
. If you selected *Periodic SQL Invocation*, in the *Query* field,
enter a SQL `SELECT` statement to obtain one or more records.
The table that contains the data you want must already exist.
+
If you selected *Periodic Stored Procedure*, in the
*Stored Procedure* field, select or enter the stored procedure to
invoke to obtain the data of interest. The stored procedure you specify must
already exist. The database administrator should have created any stored
procedures you need to use in an integration.
. In the *Period* field, enter an integer and indicate whether the unit is
minutes, hours, or days. For example, if you specify `5 minutes` then
the connection invokes the specified query or stored procedure every
five minutes.
. Click *Done*.

{prodname} tries to validate the connection, which includes
checking that a specified SQL query is syntactically correct and
confirming that the query or stored procedure target data exists. If
verfication is successful then {prodname} adds the start connection to
the integration. If verification fails then {prodname} displays a message
about the problem. Update your input as needed and try again.

== Finishing an integration by accessing a database or accessing a database in the middle of an integration

To finish an integration by accessing a database, add a database
connection as the finish connection. To access 
a database in the middle of an integration, add a database connection
between the start and finiah connections.
The instructions below assume that you are
on the {prodname} *Choose a Finish Connection* page or the
*Choose a Connection* page.

To add a database connection:

. Click the database connection for the database you want to access.
. On the *Choose an Action* page, click one of the following:
+
* *Invoke SQL* operates on data by executing the
SQL statement you specify.
* *Invoke Stored Procedure* operates on data by invoking
the stored procedure you specify or select.
. If you selected *Invoke SQL*, in the *SQL Statement* field:
+
For a middle connection, enter a SQL `SELECT` statement that obtains
one record or enter a SQL `INSERT`, `UPDATE`, or
`DELETE` statement that
operates on one or more records.
The table that contains the data must already exist.
+
In this release, when a database connection is a middle connection,
a `SELECT` statement can obtain only one record. You should define
the `SELECT` statement so that it obtains one record.
+
For a finish connection, enter a SQL `INSERT`, `UPDATE` or
`DELETE` statement to
operate on one or more records.
+
If you selected *Invoke Stored Procedure*, in the
*Stored Procedure* field, select or enter the stored procedure to
invoke to operate on the data of interest. The stored procedure you specify must
already exist. The database administrator should have created any stored
procedures you need to use in an integration.
. Click *Done*.

{prodname} tries to validate the connection, which includes
checking that a specified SQL query is syntactically correct and
confirming that the query or stored procedure target data exists. If
verfication is successful then {prodname} adds the connection to
the integration. If verification fails then {prodname} displays a message
about the problem. Update your input as needed and try again.
