[id='adding-s3-connection-start']
= Adding an Amazon S3 connection as the start connection

In an integration, to add an Amazon S3 connection as the start connection: 

. In the {prodname} panel on the left, click *Integrations*. 
. Click *Create Integration*. 
. On the *Choose a Start Connection* page, click the Amazon S3 connection that
you want to use as the integration's start connection. 
. On the *Choose an Action* page, click one of these actions:
* *Get Object* to obtain a file from the bucket that the connection
accesses. To configure this action:

.. To obtain a file and then delete it from the bucket, select
*Delete After Read*. 

.. In the *File Name* field, enter the name of the file that you want
to obtain. 

* *Poll an Amazon S3 Bucket* to periodically obtain files from the bucket that the
connection accesses. To configure this action:

.. To obtain files and then delete them from the bucket, 
select *Delete After Read*.
.. In the *Max Messages Per Poll* field, enter the largest number of files
that one poll operation can obtain. The default is 10. 
+
To have no limit on the number of files that can be obtained, specify 
`0` or a negative integer. When *Max Messages Per Poll* is unlimited, 
the poll action obtains all files in the bucket.
+
If the bucket contains more than the specified maximum number of files 
then the default
behavior is that the action obtains the files that were most recently 
modified or created. This behavior can be changed in AWS.
.. In the *Prefix* field, optionally specify a regular expression
that evaluates to a string. If you specify a 
prefix then this action retrieves a file
only when its name starts with that string. 
.. In the *Delay* field, enter the number of milliseconds that elapse between
polls. The default is 500 milliseconds. 
Alternatively, you can enter something like `3s`, `5m 30s`, or `2h` to
indicate 3 seconds, or 5 minutes 30 seconds, or 2 hours, respecitively.
. Click *Done*. 
