[id='adding-dropbox-connection-middle']
= Accessing Dropbox in the middle of an integration

To download or upload Dropbox files in the middle of an integration,
add a Dropbox connection between the start and 
finish connections. You must be creating or editing an integration.
You must add the start and finish connections first.
Follow these instructions:

. In the integration visualization panel on the left, 
hover over the plus sign that is in the location
where you want to add a Dropbox connection.
. In the popup, click *Add a connection*.
. On the *Choose a Connection* page, click the Dropbox connection that you 
want the integration to use. 

. On the *Choose an Action* page, select one of the following actions:
+
* *Upload a file to Dropbox* to add the current integration data to the
Dropbox account that this connection accesses. To configure this
action:
.. In the *Remote Path* field, to upload multiple files, enter the 
local path for the folder that you want to upload. Dropbox uses the same 
path to store the files. To upload one file, specify the local path and 
file name of the file you want to upload. Dropbox stores the file with the 
same path and name.
.. For the *Upload mode*, 
+
** Select *Add* to upload a file only when a file with the same name is not already
in the same Dropbox folder. If a file with the same name is already
in the same Dropbox folder, then the file is not uploaded and the integration continues.
This is the behavior regardless of whether the content in the file you are trying to
upload has been updated. 
** Select *Force* to ensure that the file is uploaded even if a file with the
same name is present in the same Dropbox folder. Dropbox overwrites the file
that it already has with the file that you are uploading. 
+
* *Download from Dropbox* to obtain one or more files from the Dropbox
account that this connection accesses. To configure this action,
in the *Folder or filename path to download* field, enter the Dropbox
folder path or the Dropbox file path of the content 
you want to obtain. 
. Click *Next* to specify the action's input and output type. See 
<<specifying-connection-input-output-types>>.
