[id='adding-api-connectors']
= Adding REST API client connectors

{prodname} can create connectors for
Representational State Transfer Application Programming Interfaces
(REST APIs)
that support Hypertext Transfer Protocol (HTTP).
To do this, {prodname} requires a valid
OpenAPI 2.0 specification that describes a REST API that you want to connect to.
If the API service provider does not make an OpenAPI specification available
then you must create the OpenAPI specification.

The following topics provide information and instructions for adding
REST API connectors:

* <<about-api-client-connectors>>
* <<about-openapi-specifications>>
* <<creating-api-connectors>>
* <<updating-api-connectors>>
* <<deleting-api-connectors>>

After you create a REST API client connector, for details about using
that connector in an integration, see
{LinkFuseOnlineConnectorGuide}#connecting-to-rest-apis[{NameOfFuseOnlineConnectorGuide}, Connecting to REST APIs].

include::about_api_connectors.adoc[leveloffset=+1]

include::about_openapi_content.adoc[leveloffset=+1]

include::creating_api_connectors.adoc[leveloffset=+1]

include::updating_api_connectors.adoc[leveloffset=+1]

include::deleting_api_connectors.adoc[leveloffset=+1]
