[id='adding-dropbox-connection-finish']
= Adding a Dropbox connection as a finish connection

In an integration, to add a Dropbox connection as the finish connection,
start creating the integration, add and configure the start connection,
and then:

. On the *Choose a Finish Connection* page, click the Dropbox connection that
you want to use as the integration's finish connection. 
. On the *Choose an Action* page, click the *Upload a file to Dropbox* 
action to add the current integration data to the
Dropbox account that this connection accesses. 
. In the *Remote Path* field, to upload multiple files, enter the 
local path for the folder that you want to upload. Dropbox uses the same 
path to store the files. To upload one file, specify the local path and 
file name of the file you want to upload. Dropbox stores the file with the 
same path and name.
. For the *Upload mode*, 
+
* Select *Add* to upload a file only when a file with the same name is not already
in the same Dropbox folder. If a file with the same name is already
in the same Dropbox folder, then the file is not uploaded and the integration continues.
This is the behavior regardless of whether the content in the file you are trying to
upload has been updated. 
* Select *Force* to ensure that the file is uploaded even if a file with the
same name is present in the same Dropbox folder. Dropbox overwrites the file
that it already has with the file that you are uploading. 
. Click *Next* to specify the action's input type. See 
<<specifying-connection-input-output-types>>.
