[id='adding-slack-connections']
= Adding a Slack connection to an integration

In an integration, to send a message to a Slack channel or user, first create
a Slack connection. You can then add that connection to any number
of integrations as a finish connection or as a middle connection. Since the 
integration data becomes the message that is sent to Slack, it does not
make sense to start an integration with a connection to Slack. 

To add a Slack connection to an integration, you must be creating or
editing an integration. If you are creating an integration, then
{prodname} might be prompting you to choose a finish connection. 
To add a middle connection, hover over the plus
sign in the left panel in the location where you want to add the
connection and select *Add a connection*. 

To add a Slack connection:

. Click the Slack connection that you want to add to the integration. 
. Select the action that you want the connection to perform.
+
* Click *User name* to send a message to one user. To configure this action,
in the *User name* field, specify the name of the user to send the message
to. The integration sends the integration data in a message to that user.
* Click *Channel* to publish a message on a channel. To configure
this action, in the *Channel* field, specify the channel to publish 
the message to. The integration sends the integration data in 
a message to that channel. 

. Click *Next* to add the connection to the integration. 
