[id='add-database-connection']
= Add a database connection to an integration

You must create a database connection before you can add a database
connection to an
integration. If you did not already create the database connection, 
see <<create-database-connection>>. 

The procedure for adding a database connection varies according to 
whether you are adding

* Database connections as start connections
* Database connections as middle or finish connections

== Database connections as start connections

In an integration, to add a database connection as the integration's
start connection:  

. In the {prodname} pane on the left, click *Integrations*. 
. Click *Create Integration*. 
. On the *Choose a Start Connection* page, click your 
database connection. 
. On the *Choose an Action* page, click one of the following:
+
* *Periodic SQL Invocation* obtains data by periodically invoking the
SQL query you specify.
* *Periodic Stored Procedure* obtains data by periodically invoking
the stored procedure you specify or select. 
. If you selected *Periodic SQL Invocation*, in the *Query* field,
enter a SQL `SELECT` statement to obtain one or more records.
The table that contains the data you want must already exist.
+
If you selected *Periodic Stored Procedure*, in the
*Stored Procedure* field, select or enter the stored procedure to 
invoke to obtain the data of interest. The stored procedure you specify must 
already exist. The database administrator should have created any stored 
procedures you need to use in an integration. 
. In the *Period* field, enter an integer and indicate whether the unit is
minutes, hours, or days. For example, if you specify `5 minutes` then
the connection invokes the specified query or stored procedure every
five minutes. 
. Click *Done*. 

{prodname} tries to validate the connection, which includes
checking that a specified SQL query is syntactically correct and
confirming that the query or stored procedure target data exists. If
verfication is successful then {prodname} adds the start connection to
the integration. If verification fails then {prodname} displays a message
about the problem. Update your input as needed and try again. 

== Database connections as middle or finish connections

In an integration, you can designate a database connection as the 
finish connection or add a database connection between the start and
finish connections. The instructions below assume that you are 
on the {prodname} *Choose a Finish Connection* page or the
*Choose a Connection* page.

To add a database connection:

. Click your database connection. 
. On the *Choose an Action* page, click one of the following:
+
* *Invoke SQL* operates on data by executing the
SQL statement you specify.
* *Invoke Stored Procedure* operates on data by invoking
the stored procedure you specify or select. 
. If you selected *Invoke SQL*, in the *SQL Statement* field:
+
For a middle connection, enter a SQL `SELECT` statement that obtains
one record or enter a SQL `INSERT`, `UPDATE`, or 
`DELETE` statement that 
operates on one or more records.
The table that contains the data must already exist.
+
In this release, when a database connection is a middle connection, 
a `SELECT` statement can obtain only one record. You should define
the `SELECT` statement so that it obtains one record.
+
For a finish connection, enter a SQL `INSERT`, `UPDATE` or 
`DELETE` statement to 
operate on one or more records.
+
If you selected *Invoke Stored Procedure*, in the
*Stored Procedure* field, select or enter the stored procedure to 
invoke to operate on the data of interest. The stored procedure you specify must 
already exist. The database administrator should have created any stored 
procedures you need to use in an integration. 
. Click *Done*. 

{prodname} tries to validate the connection, which includes
checking that a specified SQL query is syntactically correct and
confirming that the query or stored procedure target data exists. If
verfication is successful then {prodname} adds the connection to
the integration. If verification fails then {prodname} displays a message
about the problem. Update your input as needed and try again.
