[id='create-s3-connection']
= Create an Amazon S3 connection

Before you can create an Amazon S3 connection, you must know the
following:

* Amazon S3 access key ID for the Amazon Web Services (AWS) account
that created the bucket you want to access. 
* Amazon S3 secret access key for the AWS account that created the bucket
you want to access. 
* Name of the bucket you want to access or its Amazon Resource Name (ARN)
* Region in which the bucket is located

If you do not have Amazon access keys, you can obtain new keys as follows:

. Go to https://aws.amazon.com/s3/. 
. Sign in to the console
with the AWS account that created the bucket you want to access. 
. In the console, in the upper right, click the down arrow next to 
the username and click *My Security Credentials*. 
. Expand *Access Keys* and click *Create New Access Keys*.
. Follow the prompts to obtain the keys. 

To create an Amazon S3 connection:

. In {prodname}, in the left pane, click *Connections* to 
display any available connections. 
. In the upper right, click *Create Connection* to display
{prodname} connectors.  
. Click the *Amazon S3* connector. 
. In the *Access Key* field, enter the Amazon S3 access key ID, 
provided by AWS, for the
AWS account that created the bucket you want to access. 
. In the *Bucket Name or Amazon Resource Name* field, enter the name of
the bucket you want this connection to access or enter the bucket's ARN. 
. In the *Region* field, enter the AWS region in which the bucket resides.
. In the *Secret Key* field, enter the Amazon S3 secret access key,
provided by AWS, for the account that created the bucket you want this 
connection to access. 
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether or not
validation is successful. If validation fails, revise the configuration
details as needed and try again. 
. If validation is successful, click *Next*. 
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connection. 
For example, enter `Obtain S3 Data`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample S3 connection
that obtains data from the northeast bucket.*`
. In the upper right, click *Create* to see that the connection you 
created is now available. If you entered the example name, you would 
see that *Obtain S3 Data* is now available. 
