[id='creating-mqtt-connections']
= Create a connection to an MQTT broker

To create an MQTT connection:

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
connectors.  
. Click the *MQTT* connector.
. In the *MQTT broker URL* field, enter the location of the MQTT broker
that you want to send data to or obtain data from. 
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the URL
and try again.
. If validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, you might enter `MQTT West`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. 
. In the upper right, click *Create* to see that the connection you 
created is now available. If you
entered the example name, you would 
see that *MQTT West* now available. 
