// Module included in the following assemblies:
// trigger_integrations_with_api_calls.adoc

[id='create-api-provider-integration_{context}']
= Create an integration that is triggered by an API call

To be able to invoke a call that triggers execution of an integration, you provide
an OpenAPI specification that defines the operations that the integration
can perform. For each operation, you specify an integration flow that
connects to the applications and processes the integration data according to the
requirements for that operation. 

.Prerequisites
* You can provide an OpenAPI specification for the REST API
operations that you want the integration to perform. 
+
To experiment,
https://github.com/syndesisio/syndesis-quickstarts/blob/master/api-provider/task-api.json[download the `task-api.json` file], 
which is an OpenAPI specification for an API provider quickstart. You can
then drag this file in when {prodname} prompts you to provide an OpenAPI
specification. 
* You have a plan for the integration flow for each OpenAPI operation. 
* You created a connection for each application or service that you want
to add to an integration flow. 

.Procedure

. In {prodname}, in the left navigation panel, click *Integrations*. 
. In the upper right, click *Create Integration*. 
. On the *Choose a Start Connection* page, click the *API Provider* card. 
. On the *Start integration with an API call* page, do one of the following: 
+
* Drag and drop a file that contains an OpenAPI 2.0 specification for the
REST API operations. 
* Click *Choose File* to navigate to and upload a file that contains an 
OpenAPI specification. 
* Click *Use a URL* and enter the URL for an OpenAPI specification. 
* Select *Create from scratch* to define an OpenAPI specification. 

. Click *Next*. 
+
If you uploaded a specification then {prodname} gives you an opportunity
to review or edit the operations. Click *Review/Edit* to open the Apicurio editor
in which you can review or update the specification. Click *Next* if
you do not want to review or edit the operations. If you opened the Apicurio
editor, then when you are done, save if necessary, then click *Next*. 
+
If you are defining an OpenAPI specification, then {prodname} opens
the Apicurio editor. Define and save your OpenAPI specification. Then
click *Next*. 
+
In this Technology Preview release, you cannot edit the operation 
description that will appear in the operations list in {prodname}. 


. On the *Give this integration a name* page, enter a name for your integration.
. Optionally, enter a description that helps you distinguish this integration
from other integrations. 
. Click *Save and continue* to display the *Choose Operation* page. You are
ready to define a flow for each operation. 
See <<create-integration-operation-flows_{context}>>.
