[id='creating-ftp-connections']
= Creating an FTP or SFTP connection

To create a connection to an FTP server or an SFTP server:

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *FTP* connector to use File Transfer Protocol or
click the *SFTP* connector to use Secure File Transfer Protocol.
. Configure the connection. 
+
* For an FTP connection, *Host* is the only parameter that you must
specify. Enter the host name of the server you want to connect to.
* For an SFTP connection, you must specify these parameters:
+
** *Host*
** *User name* is the name of the account you want to 
use to access the server.
** *Password* associated with that user name

+
All other parameters have default values. Descriptions of these 
parameters are after this procedure. 

. Click *Validate*. {prodname} immediately tries to validate the
connection and displays a message that indicates whether or not
validation is successful. If validation fails, revise the configuration
details as needed and try again.
. When validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*XLight FTP Server*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection.
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *XLight FTP Server* is now available.

.Descriptions of other parameters

* *Binary file transfer mode* is used by default.  
Select *No* for ASCII transfer mode.
* *Connect timeout* defaults to *10000* milliseconds and 
indicates a maximum wait of 10 seconds to establish 
the connection. If 10 seconds elapse without a connection then
{prodname} waits for the number of milliseconds defined by
*Reconnect delay* and then tries to reconnect.  
* *Disconnect from server* defaults to *No*. The connection 
remains established after it performs the action. Select *Yes*
if you want to disconnect from the server after the connection
performs the upload or download. 
* *Maximum reconnect attempts* defaults to *3*. {prodname} tries as many as 3 times
to establish a connection.
* *Passive connection mode* defaults to *Yes*, which is usually the preferred
mode. In passive mode, the client opens communication channels with the server
as a way to avoid firewall issues. If you select *No* then active mode is
used.
* *Port* specifies the port that the server is listening on. 
For an FTP server, the default port is *21*. For an SFTP server, the
default port is *22*
* *Reconnect delay* defaults to *1000* milliseconds and indicates the
wait time before trying to reconnect again. 
* *Data timeout* defaults to *30000* milliseconds and indicates the maximum
length of time that {prodname} waits for a reply. 
. 

.

.
