[id='creating-api-connectors']
= Creating API client connectors

To create an API client connector:

. In the {prodname} navigation panel, click *Customizations* to display
the *API Client Connectors* tab. Any API client connectors that are
already available are listed here.
. Click *Create API Connector*.
. On the *Create API Client Connector* page, do one of the following:
+
* Click *Browse* and select the OpenAPI file that you want to upload.
* Select *Use a URL* and paste the URL for your OpenAPI specification
in the input field. 

. Click *Next*. If there is invalid or missing content, {prodname}
displays information about what needs to be corrected. Select a different
OpenAPI file to upload or click *Cancel*,
revise the OpenAPI file, and upload the updated file.
+
If the specification is valid and complete, {prodname} displays a summary of
the actions that the connector will provide. This might include errors and
warnings about the action specifications.

. To revise the OpenAPI file,
click *Cancel*, revise the OpenAPI file, and upload the updated file.
+
If you are satisfied with the action summary, click *Next*.
. Indicate the API's security requirements by selecting one of the
following:
.. *No Security*
.. *HTTP Basic Authorization* -- Enter the user name and password you
want to use to access the API.
.. *OAuth* -- {prodname} prompts you to enter:
... *Authorization URL* is the location for registering {prodname} as
a client of the API. Registration authorizes {prodname} to access the API.
See 
{LinkFuseOnlineConnectorGuide}#connecting-to-rest-apis[{NameOfFuseOnlineConnectorGuide}, Connecting to REST APIs].
The OpenAPI specification or other
documentation for the API should specify this URL. If it does not then
you must contact the service provider to obtain this URL.
... *Access Token URL* is required for OAuth authorization. Again, the
OpenAPI specification or other documentation for the API should provide
this URL. If it does not then you must contact the service provider.
. Click *Next*. {prodname} displays the connector's name,
description, host, and base URL as indicated by the OpenAPI file.
For connections that you create from this connector,
+
** {prodname}
concatenates the host and base URL values to define the endpoint for
the connection. For example, if the host is `https://example.com` and
the base URL is `/api/v1` then the connection endpoint is
`https://example.com/api/v1`.
** {prodname} applies the schema specified in the OpenAPI file to data
mapping steps. If the OpenAPI file supports more than one schema then {prodname}
uses the TLS (HTTPS) schema.
. Review the connector details and optionally upload an icon for the connector.
If you do not upload an icon, {prodname} generates one.
You can upload an icon at a later time. When {prodname} displays
the flow of an integration, it displays a connector's icon
to represent connections that are created from that connector.
+
To override a value obtained from
the OpenAPI file, edit the field value that you want to change.
After {prodname} creates a connector,
you cannot change it. To effect a change, you need to upload an updated
OpenAPI file so that {prodname} can create a new connector.
. When you are satisfied with the connector details, click *Create API Connector*.
{prodname} displays the new connector with the other connectors. 

For details about using your new API connector, see
{LinkFuseOnlineConnectorGuide}#connecting-to-rest-apis[{NameOfFuseOnlineConnectorGuide}, Connecting to REST APIs].
