[id='creating-slack-connections']
= Create a Slack connection

To create a connection to an instance of Slack:

. In {prodname}, in the left panel, click *Connections* to
display any available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *Slack* connector.
. In the *Slack webhook URL* field, enter the webhook URL of the
Slack instance to send messages to.
. In the *Sending user name for messages* field, enter the user name that 
the bot has when it sends messages to Slack.
. In the *Message avatar emoji* field, specify the emoji that the bot
uses for the message avatar.  
. In the *Message avatar icon URL* field, specify the URL of 
the emjoi avatar that the bot uses when it sends messages to Slack. 
. Click *Validate*. {prodname} immediately tries to validate the 
connection and displays a message that indicates whether 
validation is successful. If validation fails, revise the
connection configuration values and try again.
. If validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*Slack for Company Sales*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection.
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *Slack for Company Sales* is now available.
