[id='deleting-extensions']
= Deleting extensions

You can delete an extension even if a running integration uses a step that is
provided by that extension or uses a connection that was created from a 
connector that was 
provided by that extension. After you delete an extension, you cannot 
start an integration that uses a customization that was provided by
that extension. 

To delete an extension:

. In the left {prodname} panel, click *Customizations*.                         
                            
. At the top, click *Extensions*.                         
                            
. In the list of extensions, find the entry for the extension that 
you want to delete and click *Delete*, which appears at the right of the 
entry. 

There might be stopped or draft integrations that use a customization 
provided by an extension that you delete. 
To run one of these integrations, you will need to edit the
integration to remove the customization. 
See <<identifying-extension-use>> and <<updating-integrations>>. 
