[id='description-kinds-extensions']
= Description of the kinds of extensions

An extension defines one of the following:

* One or more custom steps that operate on integration data between
connections.

* A library resource that an integration runtime uses. For example, 
a library extension can provide a JDBC driver for connecting to a proprietary 
SQL database, such as Oracle. 

* A single custom connector for creating connections to a particular application
or service that you want to integrate.
+
NOTE: {prodname} can use an OpenAPI specification to create a connector 
for a REST API client. See <<developing-rest-api-client-connectors>>.

A business integrator shares requirements with a developer who codes the extension.
The developer provides a `.jar` file that contains the extension.
The business integrator uploads the `.jar` file in {prodname} to make the custom connector, 
custom step(s), or library resource available for use within {prodname}.

An extension `.jar` file that you upload to {prodname} always contains 
exactly one extension.  

For an example of uploading and using an extension that provides a step
that operates on data between connections, see the 
{LinkFuseOnlineTutorials}#amq-to-rest-api[AMQ to REST API sample integration tutorial].
