[id='guidelines-for-openapi-specifications']
= Guidelines for OpenAPI specifications

The more detail that the OpenAPI specification provides, the more support
{prodname} can offer when connecting to the API. For example,
the API definition is not required to declare data types for requests
and responses. Without type declarations, {prodname}
defines the corresponding connection action as typeless. However, in an
integration, you cannot add a data mapping step immediately before or
immediately after an API connection that performs a typeless action.

One remedy for this is to add more information to the OpenAPI specification
before you upload it to {prodname}. Identify the OpenAPI resource operations that
will map to the actions you want the API connection to perform. In the
OpenAPI specification, ensure that there is a JSON schema that specifies
each operation's request and response types.

If the OpenAPI specification for the API declares support for
`application/json` content type and also `application/xml` content type
then the connector uses the JSON format. If the OpenAPI specification
specifies `consumes` or `produces` parameters that define both
`application/json` and `application/xml`, 
then the connector uses the JSON format.
