[id='obtaining-authorization-to-access-applications']
= Obtaining authorization to access applications

:context: ug
In an integration, you might want to connect to an application that uses
the OAuth protocol to authenticate access requests. To do this,
you must register your installation of {prodname} for access to that application.
Registration authorizes all connections from your {prodname} installation
to a given application. For example, if you register your {prodname}
installation with Salesforce, all connections from your {prodname}
installation to Salesforce use the same client ID and the same client secret.

In each {prodname} environment, for each application that uses OAuth,
there can be only one registration
of {prodname} as a client. For example, you cannot log into one Twitter
account, register {prodname} as a client that uses those credentials, and then
log into a second Twitter account to also register {prodname} as a client
that uses the credentials for the second Twitter account.

[NOTE]
====
For information about using custom connectors that let 
you access applications that use the
OAuth protocol, see <<creating-connections-from-custom-connectors>>. 
====

For details, see the following topics:

* <<general-procedure-for-obtaining-authorization>>
* <<about-connection-validation>>

include::general_procedure_for_obtaining_authorization.adoc[leveloffset=+1]

include::about_connection_validation.adoc[leveloffset=+1]
