[id='obtaining-authorization-to-access-applications']
= Obtaining authorization to access applications

:context: ug
In an integration, you might want to connect to an application that uses
the OAuth protocol to authenticate access requests. To do this,
you must register your {prodname} environment for access to that application.
Registration authorizes all connections from your {prodname} environment
to a given application. For example, if you register your {prodname}
environment with Salesforce, all connections from your {prodname}
environment to Salesforce use the same client ID and the same client secret.

In each {prodname} environment, for each application that uses OAuth,
only one registration of {prodname} as a client is required. This 
registration lets you create multiple connections and each connection can
use different user credentials. 

For details, see the following topics:

* <<general-procedure-for-obtaining-authorization>>
* <<about-connection-validation>>

For information about using custom connectors that let 
you access applications that use the
OAuth protocol, see <<creating-connections-from-custom-connectors>>. 

include::general_procedure_for_obtaining_authorization.adoc[leveloffset=+1]

include::about_connection_validation.adoc[leveloffset=+1]
