[id='prerequisites-for-creating-s3-connection']
= Prerequisites for creating an Amazon S3 connection

To create an Amazon S3 connection, you must know the
following:

* Amazon S3 access key ID that is associated with
the Amazon Web Services (AWS) account
that created the bucket that you want the connection to access.
+
You can create a connection that accesses a bucket that does not
yet exist. In this case, when the integration starts running then
it use the AWS account associated with this access key ID to create
the bucket.
* Amazon S3 secret access key that is associated with the AWS account
that created or will create (when the integration starts running)
the bucket that you want the connection to access.
* Name of the bucket that you want to access or its Amazon Resource Name (ARN).
The connection creates this bucket if it does not already exist.
* Region in which the bucket is located or the region in which you want
the connection to create the bucket.

A user with the login credentials for the AWS account that created or will
create the bucket obtains the Amazon S3 keys as follows:

. Go to https://aws.amazon.com/s3/.
. Sign in to the console
with the AWS account that created the bucket that
you want to access or with
the account that you want the connection to use to create the bucket.
. In the console, in the upper right, click the down arrow next to
the username and click *My Security Credentials*.
. Expand *Access Keys* and click *Create New Access Keys*.
. Follow the prompts to obtain the keys.
