// This module is included in these assemblies:
// managing_integrations.adoc

[id='putting-integrations-into-service_{context}']
= Put integrations into and out of service
:context: service

After you create an integration, you can save it as a draft or 
publish it to start running it. When you publish
an integration, {prodname} assembles the needed resources, 
builds the integration runtime, deploys the OpenShift pod that will
run the integration, and then starts running the integration. 

At any time, you can click a button to stop running the integration. 
When you want to start the integration again, {prodname} already
has what it needs so starting it takes less time
than when you published it to run it for the first time. 

The process of starting a version of an integration for the first time is 
referred to as publishing the integration. The following topics 
provide details:

* <<publishing-integrations_{context}>>
* <<stopping-integrations_{context}>>
* <<starting-integrations_{context}>>
* <<restarting-older-integration-versions_{context}>>

include::publishing_integrations.adoc[leveloffset=+1]

include::stopping_integrations.adoc[leveloffset=+1]

include::starting_integrations.adoc[leveloffset=+1]

include::restarting_older_integration_versions.adoc[leveloffset=+1]

:context: manage
