[id='register-with-rest-api']
= Register {prodname} as an API client

Before {prodname} creates an API client
connector, it prompts you to indicate the API's security requirements.
For APIs that use OAuth, when {prodname} creates the connector it also
adds an entry for the API to the {prodname} *Settings* page. This is
where you provide the API client ID and the API client secret that
authorize {prodname} to access the API.

If the API you want to connect to does not use OAuth, skip this
section and see <<create-rest-api-connection>>.

To register {prodname} as an authorized API client:

. In {prodname}:
.. In the left panel, click *Settings*.
.. Near the top of the *OAuth Application Management* page, where you see
`*During registration, enter this callback URL:*`, copy that URL to the
clipboard.
.. Look for the name of the API you want to connect to and click its
*Register* button to display its client ID and client secret fields.

. In another browser window, you must register {prodname} as an OAuth
client of the API you want to connect to. The exact steps for doing this
vary for each API service. Typically, the API service provides an OAuth
custom application setting page. Go to that page.

. On that page:
.. Provide the {prodname} callback URL, which you copied at the beginning
of this procedure.
.. Obtain the client ID and client secret that the API service assigns to
your installation of {prodname}.

. In the {prodname} *Settings* page, in the entry for the 
API service you are registering with, 
paste the assigned client ID and the client secret.

. Click *Save*.
