// Module included in the following assemblies:
// trigger_integrations_with_api_calls.adoc

[id='try-api-provider-quickstart_{context}']
= Try out the Task API quickstart integration

When the {prodname} Task API quickstart integration is running, you can
invoke `curl` utility commands that send HTTP requests to the Task API service.
How you specify the HTTP request determines which integration flow the call
triggers.  

.Prerequisites

* {prodname} indicates that the Task API is *Running*. 

.Procedure

. In {prodname}, in the left navigation panel, click *Integrations*. 
. Click the *Task API* integration to display its summary. 
. Copy the integration's external URL. 
. In a terminal, invoke a command such as the following to assign the
integration's external URL to the `externalURL` environment variable.
Be sure to replace the URL in this sample command with the URL you copied: 
+
`export externalURL="https://i-task-api-proj319352.6a63.fuse-ignite.openshiftapps.com"`

. Invoke a `curl` command that triggers execution of the integration
flow for the *Create Task* operation: 
+
----
curl -k --header "Content-Type: application/json" --request POST --data '{ "task":"my new task!"}' $externalURL/api/todo 
----
+
* `-k` allows `curl` to proceed and operate even for server connections 
that are otherwise considered insecure.
* `--header` indicates that the command is sending JSON format data.
* `--request` specifies the HTTP `POST` command, which stores data.
* `--data` specifies the JSON format content to be stored. In this example the  
content is `{ "task":"my new task!"}`.
* `$externalURL/api/todo` is the endpoint to invoke. 

+
This command sends an HTTP `POST` request to the Task API service, which
triggers execution of the *Create Task* operation's integration flow. The
integration flow adds a new task to the sample database and returns a message
such as the following to indicate what it did:

+
----
{"completed":false,"id":1,"task":"my new task!"}
----

. Invoke a `curl` command that triggers execution of the integration
flow for the *Get Task by ID* operation:
+
----
curl -k $externalURL/api/todo/1 
----
+
To obtain a task, the `curl` command needs to specify only the endpoint. The
HTTP `GET` command is the default request. The last part of the endpoint
specifies the ID of the task to get. 

. Invoke a `curl` command that triggers execution of the integration
flow for the *Delete Task for ID* operation:
+
----
curl -k -X DELETE $externalURL/api/todo/1
----
+
This command invokes the HTTP `DELETE` command with the same endpoint as the
command that obtained a task by its ID. 
