[id='understanding-integration-states']
= Understanding integration states

Each version of an integration is always in one of the following states:

[cols="2*"]
|===
|*State*
|*Description*

|*Draft*
|*Draft* is always the initial state of a new version of an integration.  
Only one version of an integration can be in the *Draft* state. That 
is, you can update one version of an integration at a time.  

|*Active*
|An *Active* version is running. When you publish an integration, 
{prodname} builds the integration and starts running it. Only one version 
of an integration can be running. That is, only one 
version at a time can be in the *Active* state. 

|*Inactive*
|An *Inactive* version has suspended execution. It is still deployed but
it is not running. Activating an *Inactive* integration is faster than 
publishing a *Draft* or *Undeployed* integration. 

|*Error*
|An integration version that is in the *Error* state 
encountered an error while being published or while running. The error
suspended publication or execution.  If this happens, try activating or 
republishing an earlier integration version that ran correctly. 
Alternatively, you  can contact technical support for help. 

|*Undeployed*
|An *Undeployed* version is no longer deployed. You can republish
an undeployed version to redeploy it. The version number does not
change when you republish an undelployed version. 


|===
