[id='understanding-integration-versions']
= Understanding integration versions

In each {prodname} environment, each integration can have multiple
versions. For example, suppose you publish the
Twitter to Salesforce sample integration. After it has been
running, you update the integration to use a different 
account to connect to Twitter. You then deactivate the running 
integration and publish the updated integration. 

The initial integration that was running 
is version 1. The updated integration that is now running is
version 2. If you edit either version 1 or version 2, for example to
use a different account to connect to Salesforce, and you publish that
version then it becomes version 3 of the integration. 

Each time you edit a version of an integration and then publish the
updated integration, {prodname} assigns the next number as the version of that
integration. 

The benefit of multiple integration versions is that you can return to the
last successful deployment. While creating an integration, you might
deploy a version that does not work the way you want it to. If that 
happens then you can deactivate that version and republish a version
that runs the way you want it to. See 
<<republishing-older-integration-versions>>. 
