[id='updating-api-connectors']
= Updating API client connectors

You cannot update an API client connector. If there is
an update to the API's OpenAPI specification, 
then you must do one of the following:

* Upload the updated OpenAPI specification and create a new API client connector.
* Upload the out-of-date specification again, update it in Apicurio Studio, 
and create a new API client connector. 

To update integrations to use connections that are based on 
the updated OpenAPI specification:

. Create a new API client connector based on the updated OpenAPI specification.
To easily distinguish between the old connector and the new connector, 
you  might want to specify a version number in the connector name or 
the connector description. 
. Create a new connection from the new connector. Again, you want to be
able to easily distinguish between connections created from the old
connector and connections created from the new connector. A version number
in the connection name or connection description is helpful.
. Edit each integration that uses a connection that was created from the
old connector by removing the old connection and adding the new connection.
. Publish each updated integration.
. Recommended, but not required: delete the old connector and the old
connections. 
