[id='updating-extensions']
= Updating extensions

To update an extension:

. Obtain an updated `.jar` file for the extension from the developer.
. In {prodname}, in the left panel, click *Customizations*.
. Click the *Extensions* tab. 
. At the right of the entry for the extension that you want to update, 
click *Update*. 
. Click *Browse*, select the updated `.jar` file, and click *Open*.
. Confirm that the extension details are correct and click *Update*. 
. In the details page for the updated extension, determine which integrations
use the connector or custom step(s) defined in the extension. 

It is up to you to 
know exactly what is required to update each integration that uses a 
custom connector or a 
custom step from the updated extension.  At the very least, you must
stop and restart (click *Start*) each 
integration that uses a customization defined in the updated extension.
See <<stopping-integrations>>. 

In some cases, you might need to edit the integration to change
or add configuration details for a customization. You must communicate
with the extension developer to understand how to update integrations. 
