[id='viewing-integration-activity-information']
= Viewing information about an integration's activity

{prodname} provides activity information for each execution of an integration. 
To see this information:

. In the left panel, click *Integrations*.
. Click the entry for the integration for which you want to view log
information.
. In the integration's summary page, click the *Activity* tab.
. Optionally, enter date and/or keyword filters to limit the executions
listed.
. Click the integration execution for which you want to view log information.

For each integration step, {prodname} provides:

* The date and time that the step was executed
* How long it took to execute the step
* Whether execution was successful
* The error message if execution was not successful

To obtain additional information between any two steps, you can
add a log step to the
integration. A log step provides information about each message it
receives and can provide custom text that you specify.
If you add a log step, then it appears as one of the integration's
steps when you expand the integration execution that you want to view activity
information for. You view {prodname} information for a log step in the 
same way that you view {prodname} information for any other step. 

.Additional resources
* To add a log step, see <<add-log-step>>.
* To finish an integration by logging message information, 
link:{LinkFuseOnlineConnectorGuide}#connecting-to-log[add a log connection.]
