// Module included in the following assemblies:
// trigger_integrations_with_api_calls.adoc

[id='view-try-api-provider-quickstart_{context}']
= View and try out API Provider quickstart integration

Short description of the procedure.

.Prerequisites

* 
.Procedure

. 


Example uses the database and everyone needs to connect to the database in their own environment. 
The password is internal 

Import zip
Configuration Required messsage

Everyone's db pw is different.
The imported integration needs to connect to your connections which is why config required is appearing

Click Edit Integration
Then it will reevaluate your connections. 
Select a flow, Create Task
Publish now and it should work. 
PW is an internal thing and they do not need to know the value. 
The pw is stored in the connection.
Got to Connections
Go to DB and you can see the encoded pw
This came ootb so we generate a password for you. 

It picks up your particular password when you publish the integration. 

Click on the Task API. 
Click on Edit Integration. 
Look at the Get task by ID. 
a call comes in over REST
Then it calls into the database 
If you click on the database connection you can see the query. 
Based on the ID that you are passing in, it queries the db. The next thing 
you might want to do is call some other connection that you have. or even as 
a replacement for this. It does not have to be the db. Kurt picked it because 
we already have it and the user does not need to do anything. 


Go back to the readme. 
Under "Create Task" it instructs you to use curl which is a little utility that you use from the command line. 
Open a terminal.

export external URL = 
copy the URL from my Syndesis environment
invoke the export command with my URL in a terminal
does it matter where I am?
No

put in quotation marks (the URL)
double quotes. 
where am I exporting it to
Into my environment

echo $ externalURL 
then it will display the value of that parameter. 
"exportURL" is now an environment variable because I exported it. 

Back to the readme.
Now we are read for the first curl command
curl is a little utility that can execute HTTP commands.

We'll start off the bat with the most complex one because without any data in the database, we can't do anything. 
So we will use POST and a POST usually sends a body. 
A GET request usually does not send anything except for what you put on the URL, such as an ID or parameters. But with a POST, you send a body in. 

This is the curl command from the README:
curl -k --header "Content-Type: application/json" --request POST --data '{ "task":"my new task!"}' $externalURL/api/todo

the body's content type is JSON
we're going to send a header that tips the receiver off that whatever is coming is in json format. 

the request is of type POST
then we say what the data in the body is (--data) and what is between the single quotes is the body content, in json format. 

and then we are going to send it to the endpoint that the service is running on, which is made up of the external URL, with /api/todo appended. 
without it, that is not enough because the API is runing under api/todo. 

In the terminal, invoke the curl command.
This creates an entry in the database. 
The response is an indicatation of what it created in the database. 

Now if you go back to the browser,
the second thing is get task by api.
Go to browser, and add "/api/todo/1"
The id it created is 1 and that shoujld bring back the first record. 

We can do the same thing with a curl command, 
Copy the curl command under step 2 into a terminal and it should respond with the same thing that I saw in my browser. 

This is using the db. You can see that if I have a SF integration that I could put up an integration that checks a database, gets the details and uses them to and creates a SF request that could for example,  create me in SF. 
I as a Fuse Online user I do not need to know the details of how to create a user in Salesforce. 

We have to assign some extra options to curl in order to see the return codes. I think I need to ask Kurt about these extra options. 

Syndesis URL
copy it 
the base URL
put it in a new window.
after //
go back to terminal
oc get routes
there's my URL the second one, todo.project
copy it and put it in the browser.
This should display the todo app that we provide 

Can we use this as part of showing the commands?
No because this is looking in the database directly. 
The Todo app does not use the API. 

In the todo app you can check the green box for a task and click Update and you get a message. 
You can do the curl command in a terminal and you should see the same message. 

You must define the flow for each operation. 
.Additional resources

* 
