[id='viewing-log-information']
= Viewing an integration's log

{prodname} provides log information for each execution of an integration. 
To see this information:

. In the left panel, click *Integrations*.
. Click the entry for the integration for which you want to view log
information.
. In the integration's summary page, click the *Activity* tab.
. Optionally, enter date and/or keyword filters to limit the executions
listed.
. Click the integration execution for which you want to view log information.

For each integration step, {prodname} provides:

* The date and time that the step was executed
* How long it took to execute the step
* Whether execution was successful
* The error message if execution was not successful

To log additional information between any two steps, you can
add a log step to the
integration. A log step provides information about each message it
receives and can provide custom text that you specify.
If you add a log step, then it appears as one of the integration's
steps when you expand the integration execution that you want to view log
information for. You view {prodname} information for a log step in the 
same way that you view {prodname} information for any other step. 

To add a log step, see <<add-log-step>>.
