// Module included in the following assemblies:
// trigger_integrations_with_api_calls.adoc

[id='workflow-api-providers_{context}']
= General workflow for creating integrations that are triggered by API calls

In {prodname}, after you click *Create Integration*, the workflow for 
creating an integration that starts with an API Provider connection is
as follows.

. On the *Choose a Start Connection* page, click the *API Provider* card.
. On the *Start integration with an API call* page, upload a file that
contains an OpenAPI 2.0 specification or indicate that you want to 
create the specification now. If you upload a file, you can review and
edit it. If you choose to create it now, {prodname} opens an editor
that supports creation of OpenAPI specifications. 
. Give the integration a name and save it. 
. On the *Choose operation* page, for each operation that the OpenAPI 
specification defines, create the integration flow for that operation:
.. Click an operation to display the *Add to Integration* page. 
.. Add the connections that are required to implement the selected operation. 
.. Add additional steps that process data between connections. For example, 
in the visual representation of this integration flow, check for data type
mismatch indications. For each data type mismatch, add a step that maps 
data fields. 
.. In the visual representation of this integration flow, click the flow's 
finish connection and specify a return code. When
{prodname} executes this integration flow and reaches this connection, 
{prodname} sends the return code to your API service, which in turn sends
a response to the caller that invoked the API that triggered the integration. 
+
In this release, because an API Provider connection is a 
Technology Preview feature, the integration flow always returns the
code that you select. Error handling is not yet supported. 

. Publish the integration. 
+
{prodname} provides the URL where your REST API service is available.

. Optionally, use the `curl` utility to test the integration flows. 
