/*
 * Copyright (C) 2016 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Camel EndpointConfiguration generated by camel-api-component-maven-plugin
 * Generated on: Thu Oct 11 18:45:59 UTC 2018
 */
package org.apache.camel.component.olingo4;

import org.apache.camel.spi.UriParam;
import org.apache.camel.spi.UriParams;

/**
 * Camel EndpointConfiguration for org.apache.camel.component.olingo4.api.Olingo4App
 */
@UriParams
public final class Olingo4AppEndpointConfiguration extends Olingo4Configuration {

    @UriParam
    private Object data;

    @UriParam
    private org.apache.olingo.commons.api.edm.Edm edm;

    @UriParam
    private java.util.Map<String,String> endpointHttpHeaders;

    @UriParam
    private String keyPredicate;

    @UriParam
    private java.util.Map<String,String> queryParams;

    @UriParam
    private String resourcePath;

    @UriParam
    private org.apache.camel.component.olingo4.api.Olingo4ResponseHandler<?> responseHandler;

    public Object getData() {
        return data;
    }

    public void setData(Object data) {
        this.data = data;
    }

    public org.apache.olingo.commons.api.edm.Edm getEdm() {
        return edm;
    }

    public void setEdm(org.apache.olingo.commons.api.edm.Edm edm) {
        this.edm = edm;
    }

    public java.util.Map<String,String> getEndpointHttpHeaders() {
        return endpointHttpHeaders;
    }

    public void setEndpointHttpHeaders(java.util.Map<String,String> endpointHttpHeaders) {
        this.endpointHttpHeaders = endpointHttpHeaders;
    }

    public String getKeyPredicate() {
        return keyPredicate;
    }

    public void setKeyPredicate(String keyPredicate) {
        this.keyPredicate = keyPredicate;
    }

    public java.util.Map<String,String> getQueryParams() {
        return queryParams;
    }

    public void setQueryParams(java.util.Map<String,String> queryParams) {
        this.queryParams = queryParams;
    }

    public String getResourcePath() {
        return resourcePath;
    }

    public void setResourcePath(String resourcePath) {
        this.resourcePath = resourcePath;
    }

    public org.apache.camel.component.olingo4.api.Olingo4ResponseHandler<?> getResponseHandler() {
        return responseHandler;
    }

    public void setResponseHandler(org.apache.camel.component.olingo4.api.Olingo4ResponseHandler<?> responseHandler) {
        this.responseHandler = responseHandler;
    }
}
