[id='amq-to-rest-api']
= Implement an AMQ to REST API sample integration

:context: amq2api
This sample integration connects to an AMQ broker to obtain item
delivery records for a hypothetical enterprise. The integration then executes
a custom step that operates on the records to identify any
items that were damaged when they were received. After a simple data mapping,
the integration connects to
a REST API to obtain and provide contact information for vendors of
damaged items.

The other sample integrations use connectors and data operations that are built
into {prodname}. This integration also does that, but in addition,
it provides instructions for customizing
and extending {prodname} by leading you through the procedures for:

* Adding a custom data operation by uploading an extension.
* Adding a custom REST API client connector by uploading an OpenAPI (Swagger) file.

{prodname} provides the extension file and the OpenAPI file.

To implement the AMQ to REST API sample integration, the main steps are:

. <<amq2api-create-amq-connection>>
. <<amq2api-create-custom-step>>
. <<amq2api-create-rest-api-connector>>
. <<amq2api-upload-todo-app-icon>>
. <<amq2api-create-rest-api-connection>>
. <<amq2api-create-integration>>
. <<amq2api-confirm-works>>
. <<cleanup_{context}>>

include::amq2api_create_amq_connection.adoc[leveloffset=+1]

include::amq2api_create_custom_step.adoc[leveloffset=+1]

include::amq2api_create_rest_api_connector.adoc[leveloffset=+1]

include::amq2api_upload_todo_app_icon.adoc[leveloffset=+1]

include::amq2api_create_rest_api_connection.adoc[leveloffset=+1]

include::amq2api_create_integration.adoc[leveloffset=+1]

include::amq2api_confirm_works.adoc[leveloffset=+1]

include::clean_up.adoc[leveloffset=+1]
