[id='amq2api-create-custom-step']
= Make a custom step available

{prodname} provides a number of steps that operate on 
integration data between connections. If {prodname} does not provide a
between-connections step that meets your need,
a developer can code an extension that defines one or more
custom steps that operate on data between connections. 
The developer gives you a `.jar` file that contains the extension.
You then upload the extension in {prodname} to make the custom step(s)
available for use in integrations. 

The AMQ to REST API sample integration uses a custom step that 
operates on data between connections to
identify items that were damaged when they were received. 

To make the *Damage Reporter* custom step available: 
 
. In a new browser tab, go to 
https://github.com/syndesisio/fuse-online-tp3-sample-extension/releases. 
                    
. Download the extension’s `.jar` file.     
                            
. In {prodname}, in the left panel, click *Customizations*. 
. At the top, click *Extensions*. 
. Click *Import Extension*. 
. Click *Browse* and select the downloaded `.jar` file that contains the 
extension. 
{prodname} validates the file, extracts and displays the extension's 
name, ID, and description, and lists *Damage Reporter* as the custom step
that the extension defines. 
. Click *Import*. {prodname} makes the custom step available and displays
the extension details page. 

[NOTE]
.Extension feature will change
====
The files in the `fuse-online-tp3-sample-extension` folder provide an example 
of how to implement an extension in this technology preview. 
For more information about coding an extension and creating its `.jar` file, see the 
link:https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html/tooling_user_guide/igniteextension/[10.2 _JBoss Fuse Tooling Guide_].
However, the extension feature is continuing to evolve and will change in 
the next release. To develop an extension now, note the following about 
the content of the extension’s `.json` file:

* For an extension based on a Camel route and not a bean, 
the entrypoint must correspond to the Camel endpoint.

* For an extension that changes the type of the data it operates on,  
you must specify the input data shape and the output data shape. 

To ask questions about developing extensions, send a message to 
fuse-online-tech-preview@redhat.com. 
====
