[id='amq2api-confirm-works']
= Confirm that the AMQ to REST API integration works

To confirm that the AMQ to REST API integration is working:

. In the left panel, click *Integrations*.
. Confirm that your AMQ to REST API integration is *Running*. 
The integration must be *Running* before you continue with 
these instructions.

. In a new browser window, go to the To Do app display by
inserting `*todo-*` in front of the URL
for your {prodname} installation. For example: 
`\https://todo-app-proj7614.6a63.fuse-ignite.openshiftapps.com/`.
. In the To Do app display, click *Show JMS Form* to display an
input box that contains an XML message.
. Click *Send JMS Message* to send that message
to the AMQ broker in your OpenShift project.
+
Successful execution returns a task from the To Do app client API. The task
identifies the ID of the damaged item and the contact information for its
vendor.
. Edit the XML message to specify two damaged items:
.. Click *Show JMS Form* to display the message input box again.
.. In the XML message, change the entry for the undamaged item to
specify `damaged="true"`.
.. Click *Send JMS Message*. The To Do app client API returns a new
task that contains IDs for two damaged items and contact information for
the two vendors.
. Edit the XML message to specify an unknown vendor:
.. Click *Show JMS Form*.
.. In the XML message, for an item that has `damaged="true"`, change the name
of the vendor.
.. Click *Send JMS Message*. The To Do app client API returns a new
task that indicates that there is no contact information for the vendor of
a damaged item. The To Do app accesses a database that has only two vendors.
