[id='amq2api-create-connection-to-amq-broker']
= Create a connection to that AMQ broker

To create a connection to the AMQ broker that is running in your
Fuse Online project in OpenShift:

. In {prodname}, in the left panel, click *Connections* to display any
available connections.
. In the upper right, click *Create Connection* to display
{prodname} connectors.
. Click the *AMQ* connector.
. Configure the connection by entering:
+
.. In the *Broker URL* field, enter `*tcp://broker-amq-tcp:61616*`
as the location to obtain data from.
.. In the *Username* field, enter `*amq*` as the user name for
the account that accesses this AMQ broker.
.. In the *Password* field, enter `*topSecret*` as the password for
the account that accesses this AMQ broker.
.. Leave the other fields blank.
. Click *Validate*. {prodname} immediately tries to validate the
connection and displays a message that indicates whether
validation is successful. If validation fails, check the values you
entered and try again.
. When validation is successful, click *Next*.
. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*AMQ Broker 1*`.
. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample AMQ connection
that uses the provided broker.*`
. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *AMQ Broker 1* is now available.
