// Module included in the following assemblies:
// amq2api_intro.adoc

[id='amq2api-create-amq-connection_{context}']
= Create an AMQ connection

The AMQ to REST API sample integration starts by connecting to an
AMQ broker that is provided in your OpenShift Online  project. Before you
start to create the integration itself, you must start the broker
and create an AMQ connection to that broker. 

.Procedure

. Start the broker:

.. In a browser, go to the 
https://console.fuse-ignite.openshift.com/console/[OpenShift Online Web Console]. 
Your {prodname} environment runs on OpenShift Online.

.. In the console, on the right, under *My Projects*, click *Fuse Online* to
display the project's overview. 
+
Your project's name is something like `proj123456`.

.. In the overview, click the *>* to the left of the first entry, 
*broker-amq, #1*, to expand the entry for the
provided AMQ broker.

.. On the right, click the up caret to scale up to running 1 pod. This starts
the AMQ broker.

. Create the AMQ connection:

.. In {prodname}, in the left panel, click *Connections* to display any
available connections.
.. In the upper right, click *Create Connection* to display
{prodname} connectors.
.. Click the *AMQ* connector.
.. Configure the connection by entering:
+
... In the *Broker URL* field, enter `*tcp://broker-amq-tcp:61616*`
as the location to obtain data from.
... In the *Username* field, enter `*amq*` as the user name for
the account that accesses this AMQ broker.
... In the *Password* field, enter `*topSecret*` as the password for
the account that accesses this AMQ broker.
... Leave the other fields blank.
.. Click *Validate*. {prodname} immediately tries to validate the
connection and displays a message that indicates whether
validation is successful. If validation fails, check the values you
entered and try again.
.. When validation is successful, in the upper right, click *Next*.
.. In the *Connection Name* field, enter your choice of a name that
helps you distinguish this connection from any other connections.
For example, enter `*AMQ Broker 1*`.
.. In the *Description* field, optionally enter any information that
is helpful to know about this connection. For example,
enter `*Sample AMQ connection
that uses the provided broker.*`
.. In the upper right, click *Create* to see that the connection you
created is now available. If you entered the example name, you would
see that *AMQ Broker 1* is now available.
