[id='amq2api-create-custom-step']
= Make a custom step available

{prodname} provides a number of built-in steps for operating on 
integration data. If {prodname} does not provide a needed step,
a developer can code an extension that defines one or more
custom steps. The developer gives you a `.jar` file that contains the extension.
You then upload the extension in {prodname} to make the custom step(s)
available for use in integrations. 

The AMQ to REST API sample integration uses a custom step that 
identifies items that were damaged when they were received. 

To make the *Damage Reporter* custom step available: 
 
. In a new browser tab, go to 
https://github.com/syndesisio/fuse-online-tp3-extension. 
+
This folder contains the `.jar` file you want to upload to {prodname}.
It also contains the files that make up the extension, which you can
examine if you want to. 

. Above the content list, you can see a line that starts with the 
number of commits and branches. Just to the right, click *1 release*. 

. Download the extension's  `jar` file from the releases folder.
. In {prodname}, in the left panel, click *Customizations*. 
. At the top, click the *Extensions* tab. 
. Click *Import Extension*. 
. Click *Browse* and select the downloaded `.jar` file that contains the 
extension. 
{prodname} validates the file, extracts and displays the extension's 
name, ID, and description, and lists *Damage Reporter* as the custom step
that the extension defines. 
. Click *Import*. {prodname} makes the custom step available and displays
the extension details page. 

[NOTE]
.Extension feature will change
====
The files in the `fuse-online-tp3-extension` folder provide an example 
of how to implement an extension in this technology preview. 
For more information about coding an extension and creating its `.jar` file, see the 
link:https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html/tooling_user_guide/igniteextension/[10.2 _JBoss Fuse Tooling Guide_].
However, the extension feature is continuing to evolve and will change in 
the next release. To develop an extension now, note the following about 
the content of the extension’s `.json` file:

* For an extension based on a Camel route and not a bean, 
the entrypoint must correspond to the Camel endpoint.

* For an extension that changes the type of the data it operates on,  
you must specify the input data shape and the output data shape. 

To ask questions about developing extensions, send a message to 
fuse-online-tech-preview@redhat.com. 
====
