// Module included in the following assemblies:
// as_sf2db-create-integration.adoc

[id='sf2db-choose-start-connection_{context}']
= Choose the start connection

In {prodname}, to create the sample Salesforce to database integration, 
the first task is to choose the start connection. 

.Prerequisites

* You created a Salesforce connection. 

.Procedure

. In {prodname}, on the left, click *Integrations*.
. Click *Create Integration*.
. On the *Choose a Start Connection* page, click your
Salesforce connection. If you specified the example name,
you would click *SF Connect 1*.
. On the *Choose an Action* page, click *On create*.
. In the *Object name* field, select *Lead*.
. Click *Done* to add the start connection to the integration.

.Next step
When the integration is running, after connecting to Salesforce, 
the integration watches for notifications that a Salesforce *Lead*
record was created.
When the integration finds such a notification, it passes the new
lead's data to the next step in the integration.
However, before you can add the next step, you must choose the
integration's finish connection.
