// Module included in the following assemblies:
// as_t2sf-create-integration.adoc

[id='t2sf-add-basic-filter-step_{context}']
= Add a basic filter step

In {prodname}, to continue creating the Twitter to Salesforce sample
integration, add a basic filter step that checks tweets that mention you
for particular content. At integration execution time, processing 
continues only if that content is present.

.Prerequisites
* You added the Twitter connection as the integration's start connection. 
* You just added the Salesforce connection as the integration's finish connection. 

.Procedure

. In the main panel, click *Add a step*.
. Click *Basic Filter*.

. In the first field (*The data you want to evaluate*), start to enter 
`*text*` and when `text`
appears below the field, click it. This indicates that the content to
filter for is in the Twitter `text` field, which contains the text of the tweet.

. Accept *contains* as the condition to be met for the integration to
continue.
. In the last field, enter `*#RedHatIsGreat*` or some other text you choose.
A tweet that mentions you must contain the text you enter here for
the integration to continue operating on this data.
. Click *Done* to complete the basic filter step.
