[id='sf2db-confirm-working']
= Confirm that the Salesforce to database integration works

To confirm that the Salesforce to database integration is working:

. In the left panel, click *Integrations*.
. If necessary, wait until your sample integration is a *Running* integration.
 If you used the example name, you would see that 
*Salesforce to Database Sample Integration* is *Running*.

. In your Salesforce installation, create a new lead. Be
sure to enter data
in the fields that you mapped: *Company*, *Email*, *FirstName*,
*LastName*, *LeadSource*, *Status*, *Phone*, and *Rating*.
. In a new browser window, insert `*todo-*` in front of the URL
for your {prodname} installation. For example: 
`\https://todo-app-proj7614.6a63.fuse-ignite.openshiftapps.com/`.
+
Your {prodname} installation provides the To Do app, which has a 
REST API for accessing a database that contains tasks. In the AMQ to REST 
API sample integration tutorial, there are instructions for uploading an
OpenAPI (Swagger) file for the To Do app to create an API client connector. 

. In the *To Do App* display, you should see a notification that a new 
lead was created in the database. 
