[id='salesforce-to-db']
= Implement a Salesforce to database sample integration

:context: sf2db
This sample integration captures updates in Salesforce and then
calls a database
stored procedure, which synchronizes that database
with the Salesforce updates.

To implement, deploy, and test this sample integration, the main steps are:

. <<register-with-salesforce_{context}>>
. <<create-salesforce-connection_{context}>>
. <<create-sf-db-integration>>
. <<sf2db-confirm-working>>
. <<cleanup_{context}>>

If you already created the Twitter to Salesforce sample integration:

* {prodname} is already registered as a Salesforce client.
You do not need to do this again.
* You already have a Salesforce connection, which you can reuse in
this sample integration.

If you did not already create the Twitter to Salesforce sample
integration, then you must register {prodname} as a Salesforce client
and create a Salesforce connection in order to complete the
Salesforce to database sample integration.

Before you implement
this sample integration, see <<sf2db-prerequisites>>.

include::sf2db_prereqs.adoc[leveloffset=+1]

include::shared/register_with_sf.adoc[leveloffset=+1]

include::shared/create_sf_connection.adoc[leveloffset=+1]

include::sf2db_create_integration.adoc[leveloffset=+1]

include::sf2db_confirm_works.adoc[leveloffset=+1]

include::clean_up.adoc[leveloffset=+1]
