// Module included in the following assemblies:
// t2sf_intro.adoc

[id='t2sf-confirm-working_{context}']
= Confirm that the Twitter to Salesforce integration works

To confirm that the Twitter to Salesforce sample integration is working,
tweet some messages and check for results in Salesforce. 

.Prerequisites

* In {prodname}, *Running* appears next to the name that you specified
for the Twitter to Salesforce sample integration when you published it.
* You can access your Twitter and Salesforce accounts. 

.Procedure
. In {prodname} in the panel on the left, click *Integrations* to see that the integration you
created is a *Running* integration. If you entered the example name, you
would see that *Twitter to Salesforce Sample Integration* is running.

. Confirm that the integration does not create a contact record when a
tweet does not contain the text you specified in the basic filter
step:
.. In Twitter, send a tweet that:
* Mentions your Twitter handle
* Does not contain the text you specified in the basic filter step
+
For example: `*@Aslan #likesRedHat.*`
.. Wait for the polling interval to elapse, which can be 30 - 60 seconds.
.. In Salesforce, confirm that a contact record with your
name does not exist.
. Confirm that the integration creates a new contact record when it should:
.. In Twitter, send a tweet that:
* Mentions your Twitter handle
* Contains the text you specified in the basic filter step
+
For example: `*@Aslan knows #RedHatIsGreat.*`
.. Wait for the polling interval to elapse.
.. In Salesforce, locate a contact record that has
your name, the text of your tweet in the
`Description` field, and your Twitter screen name
in the `Title` field.
