apiVersion: syndesis.io/v1beta2
kind: Syndesis
metadata:
  name: app
  labels:
    app: syndesis
spec:
  addons:
    jaeger:
      enabled: true
    ops:
      enabled: false
    publicApi:
      enabled: false
    todo:
      enabled: false
status: {}
