apiVersion: syndesis.io/v1beta1
kind: Syndesis
metadata:
  name: app
spec:
  components:
    database:
      resources:
        volumeCapacity: 5Gi
    server:
      features:
        integrationLimit: 5
        testSupport: true
