#!/bin/bash

restart_all::label() {
  echo "Restart all deployments"
}

restart_all::doc() {
  cat <<EOT
After a successful upgrade all deployments are scaled back to one

.Rollback
No rollback
EOT
}

restart_all::run() {
    local deployments=$(syndesis_deployments)
    scale_deployments 1 ${deployments}
}

restart_all::rollback() {
    sleep 1
}
