name: Backport

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport pull request
    steps:
    - uses: tibdex/backport@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
