def mavenVersion='3.3.9'

slave {
    withOpenshift {
            withMaven(mavenImage: "maven:${mavenVersion}", serviceAccount: "jenkins", mavenRepositoryClaim: "m2-local-repo", mavenSettingsXmlSecret: 'm2-settings') {
                inside {
                    checkout scm
                    stage 'Build'
                    container(name: 'maven') {
                        sh "mvn clean install"
                    }
                }
        }
    }
}
